package http

// Header constants
const (
	HeaderContentType            = "Content-Type"
	HeaderAuthorization          = "Authorization"
	HeaderAuthentication         = "Authentication"
	HeaderMeeshoCountry          = "MEESHO-ISO-COUNTRY-CODE"
	HeaderMeeshoLanguage         = "MEESHO-ISO-LANGUAGE-CODE"
	HeaderMeeshoUserId           = "MEESHO-USER-ID"
	HeaderMeeshoUserContext      = "MEESHO-USER-CONTEXT"
	HeaderAppVersionCode         = "APP-VERSION-CODE"
	HeaderMeeshoUserCity         = "MEESHO-USER-CITY"
	HeaderMeeshoUserPincode      = "MEESHO-USER-PINCODE"
	HeaderMeeshoUserLatitude     = "MEESHO-USER-LATITUDE"
	HeaderMeeshoUserLongitude    = "MEESHO-USER-LONGITUDE"
	HeaderMeeshoUserAddressId    = "MEESHO-USER-ADDRESS-ID"
	HeaderMeeshoUserStateCode    = "MEESHO-USER-STATE-CODE"
	HeaderMeeshoParentCatalogId  = "MEESHO-PARENT-CATALOG-ID"
	HeaderRealEstate             = "REAL-ESTATE"
	HeaderUpstream               = "UPSTREAM"
	HeaderMeeshoClpId            = "MEESHO-CLP-ID"
	HeaderMeeshoClientId         = "MEESHO-CLIENT-ID"
	HeaderTenantContext          = "TENANT-CONTEXT"
	HeaderValueApplicationJson   = "application/json"
	HeaderRankingHoldoutAudience = "RANKING-HOLDOUT-AUDIENCE"
	HeaderMeeshoFeedSession      = "MEESHO-FEED-SESSION-ID"
	HeaderAppSession             = "APP-SESSION-ID"
	HeaderMeeshoInstanceId       = "INSTANCE-ID"
	HeaderMeeshoSessionId        = "SESSION-ID"
	HeaderAppUserLocation        = "APP-USER-LOCATION"
	HeaderMeeshoXoToken          = "Xo"
)
