use axum::{
    extract::State,
    http::StatusCode,
    response::Json,
    routing::post,
    Router,
};
use serde::{Deserialize, Serialize};
use std::{collections::HashMap, sync::Arc, time::Duration};
use tonic::{
    metadata::AsciiMetadataValue,
    transport::{Channel, Endpoint},
};
use tower_http::cors::CorsLayer;

pub mod retrieve {
    tonic::include_proto!("retrieve");
}

use retrieve::feature_service_client::FeatureServiceClient as RetrieveClient;
use retrieve::{FeatureGroup, Keys, Query};

#[derive(Serialize, Deserialize)]
struct ApiResponse {
    success: bool,
    data: Option<String>,
    error: Option<String>,
    message: String,
}

#[derive(Clone)]
struct AppState {
    client: RetrieveClient<Channel>,
    // Pre-built metadata values to avoid allocations on every request
    auth_token: AsciiMetadataValue,
    caller_id: AsciiMetadataValue,
}

impl AppState {
    fn new(client: RetrieveClient<Channel>) -> Result<Self, Box<dyn std::error::Error>> {
        // Pre-build metadata values once using static strings
        // This avoids string allocations on every request
        // AsciiMetadataValue::from_static uses static string references - zero allocation
        let auth_token = AsciiMetadataValue::from_static("atishay");
        let caller_id = AsciiMetadataValue::from_static("test-3");
        
        Ok(Self {
            client,
            auth_token,
            caller_id,
        })
    }
}

async fn retrieve_features(State(state): State<Arc<AppState>>)
    -> Result<Json<ApiResponse>, (StatusCode, Json<ApiResponse>)>
{
    // Don't clone client - use it directly with mutable reference
    // The client internally uses Arc, so concurrent access is safe
    match retrieve_features_internal(
        &state.client,
        &state.auth_token,
        &state.caller_id,
    ).await {
        Ok(_result) => Ok(Json(ApiResponse {
            success: true,
            data: Some("Features retrieved successfully".to_string()),
            error: None,
            message: "Features retrieved successfully".to_string(),
        })),
        Err(e) => {
            eprintln!("❌ gRPC Error: {}", e);
            Err((
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(ApiResponse {
                    success: false,
                    data: None,
                    error: Some(e.to_string()),
                    message: "Failed to retrieve features".to_string(),
                }),
            ))
        }
    }
}

async fn retrieve_features_internal(
    client: &RetrieveClient<Channel>,
    auth_token: &AsciiMetadataValue,
    caller_id: &AsciiMetadataValue,
) -> Result<retrieve::Result, Box<dyn std::error::Error>> {
    // Build query with all feature labels
    // Convert static string slice to owned Vec<String> for protobuf
    let feature_labels: Vec<String> = &[
        "max_product_price_percentile",
        "orders_by_views_56day_percentile",
        "catalog__platform_orders_by_clicks_28_days_percentile_bin",
        "orders_by_views_28day_bin_percentile",
        "min_product_price_percentile",
        "orders_14day_percentile",
        "total_rated_orders_bin_percentile",
        "orders_28day_percentile",
        "clicks_by_views_1day_percentile",
        "min_product_price_bin_percentile",
        "clicks_by_views_3day_percentile",
        "log_orders_1day",
        "total_rated_orders_percentile",
        "clicks_by_views_5day",
        "views_56day_percentile",
        "log_clicks_7day",
        "views_3day_percentile",
        "orders_by_views_28day_percentile",
        "orders_7day_percentile",
        "orders_by_clicks_14day_percentile",
        "clicks_by_views_5day_percentile",
        "log_clicks_56day",
        "orders_by_clicks_28day_percentile",
        "orders_3day_percentile",
        "clicks_by_views_56day_percentile",
        "log_orders_14day",
        "log_views_5day",
        "max_product_price_percentile_bin",
        "log_clicks_3day",
        "views_7day_percentile",
        "orders_by_views_14day_percentile",
        "log_clicks_28day",
        "log_views_1day",
        "log_orders_7day",
        "clicks_by_views_1day__bin_percentile",
        "clicks_56day_percentile",
        "clicks_5day_percentile",
        "catalog__platform_orders_by_clicks_3_days",
        "orders_by_clicks_3day_percentile",
        "orders_by_clicks_1day_percentile",
        "orders_by_clicks_5day_percentile",
        "log_clicks_1day",
        "orders_by_clicks_7day_percentile",
        "log_orders_3day",
        "log_orders_56day",
        "clicks_7day_percentile",
        "orders_by_views_3day_percentile",
        "log_views_56day",
        "clicks_3day_percentile",
        "orders_by_views_7day_percentile",
        "clicks_1day_percentile",
        "orders_by_views_5day_percentile",
        "log_clicks_14day",
        "clicks_by_views_7day_percentile",
        "clicks_28day_percentile",
        "orders_5day_percentile",
        "orders_by_views_1day_percentile",
        "log_orders_28day",
        "clicks_by_views_28day_bin_percentile",
        "log_views_7day",
        "views_5day_percentile",
        "views_28day_percentile",
        "log_views_28day",
        "views_1day_percentile",
        "orders_1day_percentile",
        "log_views_3day",
        "orders_by_clicks_56day_percentile",
        "log_clicks_5day",
        "orders_56day_percentile",
        "clicks_by_views_14day_percentile",
        "clicks_by_views_28day_percentile",
        "ctr_bin_normalized_clicks_by_views_1_days",
        "sscat_normalized_clicks_by_views_1_days",
        "position_coec_7_days",
        "pdp__hour_coec_7_days",
        "hour_coec_1_days",
        "pdp__sscat_normalized_clicks_by_views_7_days",
        "search__clicks_by_views_1_days",
        "pdp__position_coec_7_days",
        "search__clicks_by_views_3_days",
        "hour_coec_30_days",
        "search__active_days_normalized_clicks_by_views_3_days",
        "pdp__clicks_by_views_7_days",
        "clicks_by_views_14_days",
        "hour_coec_14_days",
        "search__sscat_normalized_clicks_by_views_1_days",
        "search__hour_coec_1_days",
        "clicks_by_views_30_days",
        "position_coec_3_days",
        "search__active_days_normalized_clicks_by_views_1_days",
        "search__position_coec_7_days",
        "clicks_by_active_days_14_days",
        "search__clicks_by_active_days_7_days",
        "pdp__hour_coec_14_days",
        "search__active_days_normalized_clicks_by_views_7_days",
        "search__hour_coec_14_days",
        "hour_expected_clicks_1_days",
        "position_coec_14_days",
        "search__clicks_by_views_7_days",
        "search__hour_coec_3_days",
        "position_expected_clicks_1_days",
        "clicks_by_views_3_days",
        "pdp__sscat_normalized_clicks_by_views_30_days",
        "search__position_coec_30_days",
        "pdp__clicks_by_active_days_7_days",
        "search__position_coec_3_days",
        "search__active_days_normalized_clicks_by_views_14_days",
        "search__clicks_by_views_14_days",
        "pdp__clicks_by_views_1_days",
        "search__sscat_normalized_clicks_by_views_30_days",
        "pdp__clicks_by_views_14_days",
        "hour_coec_7_days",
        "pdp__hour_coec_30_days",
        "search__hour_coec_7_days",
        "search__sscat_normalized_clicks_by_views_7_days",
        "sscat_normalized_clicks_by_views_7_days",
        "pdp__clicks_by_views_3_days",
        "search__position_coec_1_days",
        "search__sscat_normalized_clicks_by_views_14_days",
        "search__clicks_by_views_30_days",
        "clicks_by_views_1_days",
        "pdp__position_coec_30_days",
        "clicks_by_views_7_days",
        "position_coec_1_days",
        "pdp__hour_coec_1_days",
        "search__hour_coec_30_days",
        "sscat_normalized_clicks_by_views_30_days",
        "search__sscat_normalized_clicks_by_views_3_days",
        "position_coec_30_days",
        "pdp__clicks_by_views_30_days",
        "orders_by_clicks_laplace_28day",
        "clicks_by_views_laplace_7day",
        "orders_by_views_laplace_1day",
        "clicks_by_views_laplace_3day",
        "clicks_by_views_laplace_56day",
        "catalog__ads_orders_by_clicks_14_days__te_laplace",
        "orders_by_clicks_laplace_3day",
        "orders_by_views_laplace_28day",
        "orders_by_clicks_laplace_56day",
        "orders_by_clicks_laplace_7day",
        "orders_by_views_laplace_5day",
        "clicks_by_views_laplace_5day",
        "orders_by_views_laplace_3day",
        "orders_by_views_laplace_56day",
        "catalog__ads_orders_by_views_14_days__te_laplace",
        "orders_by_clicks_laplace_5day",
        "clicks_by_views_laplace_1day",
        "orders_by_clicks_laplace_1day",
        "orders_by_views_laplace_7day",
        "clicks_by_views_laplace_28day",
        "laplace_cbyv_by_platform_cbyv_7day",
        "laplace_cbyv_by_platform_cbyv_56day",
        "laplace_obyv_by_platform_obyv_1day",
        "laplace_cbyv_by_platform_cbyv_3day",
        "laplace_obyv_by_platform_obyv_56day",
        "laplace_obyc_by_platform_obyc_56day",
        "laplace_obyc_by_platform_obyc_7day",
        "laplace_obyv_by_platform_obyv_5day",
        "laplace_obyc_by_platform_obyc_3day",
        "laplace_obyc_by_platform_obyc_28day",
        "laplace_obyv_by_platform_obyv_28day",
        "laplace_cbyv_by_platform_cbyv_5day",
        "laplace_obyc_by_platform_obyc_5day",
        "laplace_cbyv_by_platform_cbyv_1day",
        "laplace_cbyv_by_platform_cbyv_28day",
        "laplace_obyv_by_platform_obyv_3day",
        "catalog__base_cpc",
        "laplace_obyv_by_platform_obyv_7day",
        "laplace_obyc_by_platform_obyc_1day",
        "orders_by_views_3_days_percentile",
        "views_7_days_percentile",
        "orders_by_clicks_56_days_percentile",
        "orders_by_clicks_5_days_percentile",
        "clicks_by_views_28_days_percentile",
        "orders_1_days__te_log",
        "search__orders_by_views_3_days_percentile",
        "orders_3_days__te_log",
        "orders_1_days_percentile",
        "orders_7_days_percentile",
        "orders_7_days__te_log",
        "search__orders_by_clicks_3_days_percentile",
        "search__clicks_by_views_1_days_percentile_bin",
        "search__clicks_56_days_percentile",
        "search__orders_by_views_28_days_percentile_bin",
        "orders_by_views_7_days_percentile_bin",
        "orders_by_clicks_3_days_percentile",
        "search__clicks_by_views_1_days_percentile",
        "search__orders_by_clicks_1_days_percentile_bin",
        "orders_by_views_14_days_percentile",
        "search__orders_by_views_28_days_percentile",
        "search__orders_by_views_56_days_percentile_bin",
        "orders_by_views_1_days_percentile",
        "orders_by_clicks_14_days_percentile",
        "search__orders_by_views_14_days_percentile",
        "search__orders_by_views_1_days_percentile",
        "clicks_by_views_14_days_percentile",
        "search__orders_by_views_5_days_percentile_bin",
        "clicks_3_days_percentile",
        "clicks_by_views_3_days_percentile",
        "orders_by_clicks_28_days_percentile",
        "search__orders_by_clicks_56_days_percentile",
        "search__clicks_by_views_28_days_percentile",
        "search__orders_by_clicks_7_days_percentile_bin",
        "search__clicks_by_views_14_days_percentile_bin",
        "orders_by_clicks_7_days",
        "orders_by_clicks_3_days_percentile_bin",
        "orders_by_views_3_days_percentile_bin",
        "views_28_days_percentile",
        "clicks_by_views_7_days_percentile",
        "clicks_by_views_1_days_percentile",
        "clicks_56_days__te_log",
        "orders_by_views_28_days_percentile",
        "search__orders_by_clicks_7_days_percentile",
        "search__orders_by_clicks_1_days_percentile",
        "orders_by_clicks_1_days_percentile",
        "orders_by_clicks_7_days_percentile",
        "orders_by_views_5_days_percentile",
        "search__orders_by_views_14_days_percentile_bin",
        "search__orders_by_clicks_3_days_percentile_bin",
        "search__orders_by_views_5_days_percentile",
        "clicks_7_days_percentile",
        "views_56_days_percentile_bin",
        "orders_by_clicks_7_days_percentile_bin",
        "search__orders_1_days_percentile",
        "clicks_28_days__te_log",
        "orders_by_views_56_days_percentile",
        "orders_by_clicks_1_days_percentile_bin",
        "search__orders_by_views_56_days_percentile",
        "views_3_days_percentile",
        "orders_by_views_7_days_percentile",
        "search__orders_by_views_7_days_percentile",
        "clicks_28_days_percentile",
        "search__orders_by_views_1_days_percentile_bin",
        "orders_3_days_percentile",
        "orders_28_days_percentile",
        "clicks_by_views_56_days_percentile",
        "num_rating_3_By_num_rating",
        "qr_orders_by_sub_orders_28day",
        "num_rating_4_By_num_rating",
        "catalog__nqd_28_days",
        "catalog__num_rating_3_By_num_rating_56_days",
        "rtos_by_net_orders",
        "nqp_28day",
        "net_orders_by_gross_orders_28day",
        "catalog__qr_orders_By_return_orders_90_days",
        "rating_avg",
        "rtos_by_gross_orders",
        "net_orders_by_gross_orders_90day",
        "num_review_By_num_rating",
        "catalog__wfr_orders_By_return_orders",
        "catalog__num_rating_3_By_num_rating_90_days",
        "catalog__mean_price_90_days",
        "rtos_by_net_orders_90day",
        "catalog__num_rating_3_By_num_rating_28_days",
        "num_img_review_by_num_review",
        "avg_ratings_7day",
        "num_review_By_num_rating_7day",
        "nqp_by_nqd_90day",
        "nqp",
        "nqd",
        "catalog__avg_ratings_28_days",
        "net_orders_by_gross_orders_56day",
        "catalog__nqp_90_days",
        "user_cancelled_by_net_orders_7day",
        "return_orders_by_sub_orders",
        "cancellations_by_gross_orders_90day",
        "cancellations_by_net_orders_7day",
        "qr_orders_by_sub_orders",
        "catalog__total_helpful_review_By_num_review",
        "catalog__total_o2d_delay_By_total_orders_28_days",
        "return_orders_by_sub_orders_90day",
        "nqp_By_nqd_7day",
        "nqp_by_nqd_28day",
        "catalog__user_cancelled_By_net_orders",
        "cancellations_by_net_orders_56day",
        "catalog__num_rating_4_By_num_rating_7_days",
        "catalog__net_orders_By_gross_orders_7_days",
        "rtos_by_gross_orders_28day",
        "avg_ratings_56day",
        "total_s2d_delay_by_total_orders_28day",
        "nqp_by_nqd",
        "num_rating_5_by_num_rating",
        "count_reviews_with_helpful_by_num_review_28day",
        "rtos_by_gross_orders_56day",
        "user_cancelled_by_net_orders_28day",
        "catalog__return_orders_By_sub_orders_28_days",
        "wfr_orders_by_sub_orders",
        "num_review_by_num_rating_28day",
        "wfr_orders_by_sub_orders_28day",
        "num_review_by_num_rating_90day",
        "catalog__num_rating_1_By_num_rating_5_56_days",
        "catalog__num_rating_3_By_num_rating_7_days",
        "nqp_7day",
        "sscat_standardized_cat_predicted_nqd_wd_sigmoid",
        "net_orders_by_gross_orders",
        "cancellations_by_net_orders",
        "return_orders_by_sub_orders_56day",
        "cancellations_by_gross_orders",
        "catalog__rtos_By_gross_orders_7_days",
        "catalog__total_o2d_delay_By_total_orders",
        "catalog__total_o2s_delayed_orders_By_total_orders_56_days",
        "catalog__nqd_7_days",
        "catalog__num_rating_5_By_num_rating_7_days",
        "user_cancelled_by_net_orders_56day",
        "cancellations_by_net_orders_28day",
        "sscat__price_asp",
        "asp_sscat_percentile",
        "price_shipping_percent",
        "price_cheapest_duplicate_diff_percent",
        "sscat_asp_price_arp_diff_percent",
        "price_wdrp_depth_percent",
        "price_sscat_percentile",
        "price_decrease_percent_decay",
        "arp_sscat_percentile",
        "price_discount_percent",
        "catalog__price_decrease_pct",
        "mrp_sscat_percentile",
        "price_increase_percent_decay",
        "sscat_asp_price_arp_diff",
        "price_discount",
        "catalog__user_risk_weighted_orders_90_days",
        "od_between_25p_to_50p_user_api_user_orders_percentage_90day",
        "high_risk_user_orders_percentage",
        "od_less_than_25p_user_api_user_orders_percentage_90day",
        "od_2_4_order_users_orders_percentage_90day",
        "od_more_than_75p_user_aov_user_orders_percentage_90day",
        "od_20_plus_order_users_orders_percentage_90day",
        "avg_orders_weighted_aov_90day",
        "low_risk_user_orders_percentage",
        "od_5_10_order_users_orders_percentage",
        "od_2_4_order_users_orders_percentage",
        "low_risk_user_orders_percentage_90day",
        "od_10_20_order_users_orders_percentage",
        "catalog__between_50p_to_75p_user_aov_user_orders_percentage_90_days",
        "od_0_1_order_users_orders_percentage_90day",
        "avg_orders_weighted_api_90day",
        "od_less_than_25p_user_aov_user_orders_percentage_90day",
        "od_0_1_order_users_orders_percentage",
        "od_5_10_order_users_orders_percentage_90day",
        "od_between_25p_to_50p_user_aov_user_orders_percentage_90day",
        "catalog__high_risk_user_orders_percentage_90_days",
        "od_20_plus_order_users_orders_percentage",
        "catalog__10_20_order_users_orders_percentage_90_days",
        "catalog__ads_clicks_by_views_56_days_percentile",
        "catalog__ads_orders_by_views_1_days_percentile_bin",
        "catalog__ads_orders_by_views_56_days_percentile_bin",
        "catalog__ads_clicks_by_views_28_days_percentile",
        "catalog__ads_orders_by_views_14_days_percentile_bin",
        "ads_interactions_timeseries_transforms_clicks_28day_percentile",
        "catalog__ads_orders_by_views_3_days_percentile",
        "catalog__ads_clicks_by_views_28_days_percentile_bin",
        "catalog__ads_orders_by_clicks_5_days_percentile",
        "ads_interactions_timeseries_transforms_orders_56day_percentile",
        "catalog__ads_orders_14_days_percentile",
        "ads_interactions_timeseries_transforms_clicks_56day_percentile",
        "catalog__ads_clicks_by_views_5_days",
        "catalog__ads_orders_by_views_7_days_percentile",
        "ads_interactions_timeseries_transforms_views_1day_percentile",
        "catalog__ads_orders_by_clicks_28_days_percentile_bin",
        "catalog__ads_orders_by_clicks_7_days_percentile_bin",
        "catalog__ads_orders_by_views_56_days_percentile",
        "ads_interactions_timeseries_transforms_clicks_7day_percentile",
        "catalog__ads_orders_by_views_7_days_percentile_bin",
        "ads_interactions_timeseries_transforms_clicks_3day_percentile",
        "catalog__ads_orders_by_views_28_days_percentile_bin",
        "catalog__ads_orders_by_clicks_1_days_percentile_bin",
        "ads_interactions_timeseries_transforms_views_56day_percentile",
        "catalog__ads_orders_by_clicks_56_days_percentile_bin",
        "ads_interactions_timeseries_transforms_views_5day_percentile",
        "catalog__ads_clicks_by_views_3_days_percentile_bin",
        "catalog__ads_orders_by_clicks_7_days_percentile",
        "catalog__ads_orders_by_views_28_days_percentile",
        "catalog__ads_clicks_by_views_7_days_percentile",
        "catalog__ads_orders_by_clicks_3_days_percentile",
        "catalog__ads_clicks_by_views_1_days_percentile",
        "catalog__ads_orders_by_clicks_3_days_percentile_bin",
        "catalog__ads_orders_by_clicks_56_days_percentile",
        "catalog__ads_orders_by_clicks_28_days_percentile",
        "catalog__ads_orders_by_clicks_14_days",
        "catalog__ads_clicks_by_views_14_days_percentile_bin",
        "ads_interactions_timeseries_transforms_orders_3day_percentile",
        "catalog__ads_orders_by_clicks_14_days_percentile",
        "ads_interactions_timeseries_transforms_orders_1day_percentile",
        "ads_interactions_timeseries_transforms_views_28day_percentile",
        "catalog__ads_clicks_by_views_1_days_percentile_bin",
        "ads_interactions_timeseries_transforms_orders_5day_percentile",
        "catalog__ads_clicks_by_views_5_days_percentile_bin",
        "ads_interactions_timeseries_transforms_orders_28day_percentile",
        "catalog__ads_orders_by_views_5_days_percentile",
        "ads_interactions_timeseries_transforms_orders_7day_percentile",
        "catalog__ads_orders_by_views_5_days_percentile_bin",
        "catalog__ads_orders_by_views_1_days_percentile",
        "catalog__ads_clicks_by_views_56_days_percentile_bin",
        "catalog__ads_clicks_by_views_14_days_percentile",
        "catalog__ads_orders_by_views_14_days_percentile",
        "ads_interactions_timeseries_transforms_views_3day_percentile",
        "ads_interactions_timeseries_transforms_clicks_5day_percentile",
        "catalog__ads_clicks_by_views_56_days",
        "catalog__ads_clicks_by_views_5_days_percentile",
        "catalog__ads_orders_by_views_3_days_percentile_bin",
        "ads_interactions_timeseries_transforms_clicks_1day_percentile",
        "ads_interactions_timeseries_transforms_views_7day_percentile",
        "catalog__ads_orders_by_clicks_5_days_percentile_bin",
        "catalog__ads_clicks_by_views_3_days_percentile",
        "catalog__ads_clicks_by_views_7_days_percentile_bin",
        "catalog__ads_orders_by_clicks_1_days_percentile",
        "catalog__ads_orders_by_clicks_14_days_percentile_bin",
        "ads__derived_search__orders_by_views_7_days_percentile",
        "ads__derived_search__orders_by_clicks_1_days_percentile_bin",
        "ads__derived_search__orders_by_views_1_days_percentile",
        "ads__derived_search__orders_by_views_28_days_percentile_bin",
        "search__clicks_by_views_3_days_percentile",
        "ads__derived_search__orders_by_clicks_7_days_percentile",
        "ads__derived_search__orders_by_views_5_days_percentile_bin",
        "ads__derived_search__orders_by_views_14_days_percentile_bin",
        "ads__derived_search__orders_by_clicks_7_days_percentile_bin",
        "ads__derived_search__orders_by_views_3_days_percentile",
        "ads__derived_search__clicks_by_views_14_days_percentile_bin",
        "search__clicks_by_views_14_days_percentile",
        "ads__derived_search__orders_by_views_5_days_percentile",
        "ads__derived_search__clicks_by_views_28_days_percentile",
        "ads__derived_search__clicks_by_views_1_days_percentile_bin",
        "ads__derived_search__orders_by_views_14_days_percentile",
        "log_reviews",
        "price_change_percent_dec",
        "rating_30day",
        "price_change_percent_inc",
        "cancel_percent",
        "price_diff_with_p70",
        "rating_90day",
        "asp",
        "final_nqd",
        "diff_bw_asp_and_arp",
        "avg_rating",
        "rto_percent",
        "return_percent",
        "odnr_score",
        "rating_60day",
        "sscat_price_clicks_by_views_56day_percentile_bin_percentage",
        "sscat_rating_orders_by_views_56day_percentile_bin_percentage",
        "rating_orders_56day_percentile",
        "sscat_rating_clicks_by_views_56day_percentile_bin_percentage",
        "rating_views_56day_percentile",
        "sscat_price_orders_by_views_56day_percentile_bin_percentage",
        "catalog_rating",
        "sscat_price_orders_by_clicks_56day_percentile_bin_percentage",
        "price_clicks_56day_percentile",
        "price_orders_56day_percentile",
        "sscat_rating_orders_by_clicks_56day_percentile_bin_percentage",
        "price_views_56day_percentile",
        "rating_clicks_56day_percentile",
        "catalog__platform_orders_by_views_14_days__te_laplace",
        "interactions_timeseries_ratio_transforms_orders_by_clicks_laplace_1day",
        "interactions_timeseries_ratio_transforms_orders_by_views_laplace_28day",
        "interactions_timeseries_ratio_transforms_orders_by_views_laplace_7day",
        "interactions_timeseries_ratio_transforms_orders_by_views_laplace_3day",
        "interactions_timeseries_ratio_transforms_orders_by_clicks_laplace_5day",
        "interactions_timeseries_ratio_transforms_clicks_by_views_laplace_1day",
        "interactions_timeseries_ratio_transforms_clicks_by_views_laplace_5day",
        "interactions_timeseries_ratio_transforms_orders_by_views_laplace_56day",
        "interactions_timeseries_ratio_transforms_orders_by_clicks_laplace_28day",
        "interactions_timeseries_ratio_transforms_orders_by_clicks_laplace_3day",
        "interactions_timeseries_ratio_transforms_orders_by_views_laplace_1day",
        "interactions_timeseries_ratio_transforms_clicks_by_views_laplace_7day",
        "interactions_timeseries_ratio_transforms_clicks_by_views_laplace_28day",
        "interactions_timeseries_ratio_transforms_orders_by_clicks_laplace_56day",
        "interactions_timeseries_ratio_transforms_orders_by_clicks_laplace_7day",
        "interactions_timeseries_ratio_transforms_orders_by_views_laplace_5day",
        "interactions_timeseries_ratio_transforms_clicks_by_views_laplace_56day",
        "interactions_timeseries_ratio_transforms_clicks_by_views_laplace_3day",
        "catalog__platform_carts_3_days__te_log",
        "catalog__platform_carts_1_days__te_log",
        "catalog__platform_carts_14_days__te_log",
        "catalog__no_by_go_56_days",
        "gross_orders",
        "net_orders",
        "catalog__per_return",
        "cancellations",
        "catalog__nqd_56_days",
        "catalog__nqd_90_days",
        "catalog__per_qr_return",
        "catalog__avg_rating",
        "catalog__no_by_go_7_days",
        "catalog__no_by_go_28_days",
        "catalog__no_by_go_90_days",
        "search__sale_discount_factor_1",
        "search__sale_discount_factor_2",
        "clp__sale_discount_factor_2",
        "clp__sale_discount_factor_1",
        "pdp__sale_discount_factor_2",
        "pdp__sale_discount_factor_1",
        "ads_predicted_obyc_new_catalogs",
        "ads_ds_predicted_target_roi_v1",
        "ads_product_predicted_target_roi_v1",
        "shipped_rto_rate_6m",
        "shipped_rto_rate_3m",
        "rate_6m",
        "rto_timeseries_rate_6m",
        "rate_3m",
        "catalog__search_orders_by_clicks_28_days_percentile",
        "catalog__search_clicks_by_views_28_days_percentile",
        "catalog__search_views_3_days__te_log",
        "predicted_net_orders_by_gross_orders",
        "predicted_net_orders_by_gross_orders_smoothened_calibrated",
        "predicted_net_orders_by_gross_orders_smoothened",
        "views_3day",
        "views_28day",
        "orders_28day",
        "clicks_5day",
        "te_cbyv_7day",
        "te_obyv_7day",
        "te_obyv_3day",
        "orders_5day",
        "catalog_ratio_interactions_sscat_percentile_bins_te_obyv_3day",
        "te_obyc_7day",
        "clicks_28day",
        "clicks_1day",
        "te_cbyv_3day",
        "te_obyc_28day",
        "catalog_ratio_interactions_sscat_percentiles_te_cbyv_3day",
        "clicks_56day",
        "orders_56day",
        "views_56",
        "te_cbyv_56",
        "rated_orders_sscat_percentile",
        "views_7day",
        "rated_orders_sscat_percentile_bin",
        "orders_1day",
        "views_56day",
        "catalog_interactions_sscat_percentile_bins_orders_1day",
        "catalog_interactions_sscat_percentile_bins_clicks_28day",
        "te_cbyv_28day",
        "catalog_interactions_sscat_percentile_bins_orders_5day",
        "max_price_sscat_percentile",
        "te_obyc_56day",
        "catalog_interactions_sscat_percentiles_clicks_1day",
        "rating",
        "catalog_ratio_interactions_sscat_percentiles_te_cbyv_28day",
        "catalog_interactions_sscat_percentiles_clicks_5day",
        "te_obyc_56",
        "te_obyv_56day",
        "catalog_interactions_sscat_percentiles_views_28day",
        "views_1day",
        "catalog_interactions_sscat_percentile_bins_clicks_56day",
        "te_obyc_5day",
        "te_obyv_56",
        "catalog_ratio_interactions_sscat_percentiles_te_obyc_28day",
        "catalog_interactions_sscat_rating_bin_percentage_te_cbyv_56",
        "te_cbyv_56day",
        "catalog_interactions_sscat_percentile_bins_views_7day",
        "te_obyc_3day",
        "te_obyc_1day",
        "max_price_sscat_percentile_bin",
        "orders_56",
        "catalog_ratio_interactions_sscat_percentiles_te_cbyv_7day",
        "clicks_7day",
        "te_obyv_5day",
        "orders_3day",
        "te_obyv_1day",
        "te_cbyv_5day",
        "catalog_interactions_sscat_percentile_bins_views_1day",
        "catalog_ratio_interactions_sscat_percentile_bins_te_cbyv_5day",
        "te_cbyv_1day",
        "min_price_sscat_percentile_bin",
        "views_5day",
        "clicks_3day",
        "catalog_interactions_sscat_price_percentile_bin_percentage_te_obyc_56",
        "catalog_interactions_sscat_price_percentile_bin_percentage_orders_56",
        "orders_7day",
        "catalog_ratio_interactions_sscat_percentiles_te_obyv_5day",
        "min_price_sscat_percentile",
        "catalog_ratio_interactions_sscat_percentile_bins_te_obyv_1day",
        "catalog_interactions_sscat_price_percentile_bin_percentage_te_obyv_56",
        "catalog_ratio_interactions_sscat_percentile_bins_te_cbyv_1day",
        "clicks_56",
        "catalog_ratio_interactions_sscat_percentile_bins_te_obyv_56day",
        "te_obyv_28day",
        "catalog_ratio_interactions_sscat_percentile_bins_te_obyv_28day",
        "catalog_interactions_sscat_percentiles_views_56day",
        "catalog_interactions_sscat_rating_bin_percentage_clicks_56",
        "catalog_interactions_sscat_percentiles_views_5day",
        "catalog_interactions_sscat_percentile_bins_orders_28day",
        "catalog_interactions_sscat_percentiles_views_3day",
        "catalog_interactions_sscat_price_percentile_bin_percentage_views_56",
        "catalog_ratio_interactions_sscat_percentile_bins_te_obyc_3day",
        "catalog_interactions_sscat_percentile_bins_orders_3day",
        "catalog_ratio_interactions_sscat_percentile_bins_te_obyc_7day",
        "catalog_interactions_sscat_percentile_bins_orders_7day",
        "catalog_ratio_interactions_sscat_percentile_bins_te_cbyv_56day",
        "catalog_interactions_sscat_percentiles_clicks_3day",
        "catalog_interactions_sscat_percentile_bins_orders_56day",
        "catalog_ratio_interactions_sscat_percentiles_te_obyv_7day",
        "catalog_ratio_interactions_sscat_percentiles_te_obyc_5day",
        "catalog_interactions_sscat_percentiles_clicks_7day",
        "catalog_ratio_interactions_sscat_percentiles_te_obyc_1day",
        "catalog_ratio_interactions_sscat_percentile_bins_te_obyc_56day",
        "log_28day",
        "clicks_transformed_per_day_log_28day",
        "laplace_1day",
        "rating_rating_30day",
        "diff_asp_arp",
        "laplace_7day",
        "laplace_28day",
        "log_7day",
        "log_1day",
        "28day",
        "views_transformed_per_day_log_7day",
        "rating_rating_60day",
        "clicks_transformed_per_day_log_1day",
        "laplace_14day",
        "orders_transformed_per_day_log_7day",
        "log_14day",
        "orders_transformed_per_day_log_28day",
        "carts_tranformed_per_day_log_28day",
        "views_transformed_per_day_log_14day",
        "views_transformed_per_day_log_1day",
        "56day",
        "order_by_click_transformed_per_day_2_laplace_14day",
        "click_by_view_transformed_per_day_2_laplace_7day",
        "carts_tranformed_per_day_log_7day",
        "order_by_click_transformed_per_day_2_laplace_1day",
        "rating_rating_90day",
        "price_asp",
        "click_by_view_transformed_per_day_2_laplace_28day",
        "nqd_boosting_factor_gbm_model_v1",
        "nqd_boosting_factor_gbm_model_v0",
        "clp_price_aov_boosting_factor_var2",
        "clp_price_aov_boosting_factor_var1",
        "clp_price_aov_boosting_factor_var4",
        "clp_price_aov_boosting_factor_var3",
        "loyalty_boosting_factor",
        "asp_p70_adj_30day",
        "adj_asp_x_sup_rating_30day",
        "arp_p70_adj_30day",
        "adj_arp_x_sup_rating_30day",
        "orders_by_clicks_bayesian",
        "clicks_by_views_bayesian",
        "orders_by_views_bayesian",
        "orders_by_views_28day",
        "clicks_by_views_28day",
        "clicks_by_views_7day",
        "orders_by_clicks_28day",
        "clicks_by_views_3day",
        "clicks_by_views_1day",
        "clicks_by_views_14day",
        "orders_by_views_1day",
        "clp_odnr_sale_boosting_factor",
        "net_order_by_gross_order",
        "net_order_by_gross_order_smoothened",
        "clp_odnr_sale_boosting_factor_var2",
        "scaledup_boosting_factor",
        "vrs_boosting_factor",
        "nqd_boosting_factor_analytical_v2",
        "search_odnr_sale_boosting_factor",
        "nqd_boosting_factor",
        "catalog__num_rating_1_By_num_rating",
        "anon_clicks_21day",
        "anon_unique_user_clicks_21day",
        "anon_views_21day",
        "clicks_21day",
        "order_21day",
        "orderd_quantity_21day",
        "signup_views_21day",
        "unique_user_clicks_21day",
        "rating_21day",
        "nqp_56_days",
        "nqp_By_nqd_56_days",
        "catalog__ads_orders_by_clicks_7_days",
        "catalog__ads_orders_by_clicks_28_days",
        "catalog__ads_orders_by_clicks_56_days",
        "catalog__ads_clicks_by_views_7_days",
        "catalog__ads_clicks_by_views_28_days",
        "catalog__qr_orders_By_return_orders",
        "0_1__orders_per_click_56_days",
        "0_1__orders_per_click_28_days",
        "0_1__orders_per_click_14_days",
        "0_1__carts_per_clicks_56_days",
        "0_1__carts_per_clicks_28_days",
        "0_1__carts_per_clicks_14_days",
        "clicks_1_days_percentile",
        "orders_5_days__te_log",
        "clicks_14_days__te_log",
        "orders_14_days__te_log",
        "orders_28_days__te_log",
        "orders_56_days__te_log",
        "ads_clicks_by_platform_clicks_1_days",
        "predicted__rto_probability",
        "num_rating_5_By_num_rating_28_days",
        "cancellations_By_gross_orders_28_days",
        "cancellations_By_gross_orders_56_days",
        "cancellations_By_gross_orders_7_days",
        "cancellations_By_net_orders_90_days",
        "num_rating_1_By_num_rating_5",
        "rtos_By_gross_orders_90_days",
        "rtos_By_net_orders_28_days",
        "rtos_By_net_orders_56_days",
        "coec_1_days_smoothened_c_25",
        "coec_28_days_smoothened_c_25",
        "coec_56_days_smoothened_c_25",
        "coec_1_days_smoothened_c_25_percentile",
        "coec_28_days_smoothened_c_25_percentile",
        "coec_56_days_smoothened_c_25_percentile",
        "coec_1_days_smoothened_c_25_percentile_bin",
        "coec_28_days_smoothened_c_25_percentile_bin",
        "coec_56_days_smoothened_c_25_percentile_bin",
        "coec_1_days_smoothened_c_300",
        "coec_28_days_smoothened_c_300",
        "coec_56_days_smoothened_c_300",
        "coec_1_days_smoothened_c_300_percentile",
        "coec_28_days_smoothened_c_300_percentile",
        "coec_56_days_smoothened_c_300_percentile",
        "coec_1_days_smoothened_c_300_percentile_bin",
        "coec_28_days_smoothened_c_300_percentile_bin",
        "coec_56_days_smoothened_c_300_percentile_bin",
        "nqd_boosting_factor_gbm_model_v2",
        "prep_only__search__clicks_by_views_14_days",
        "prep_only__search__clicks_by_views_28_days",
        "prep_only__search__clicks_by_views_3_days",
        "prep_only__search__clicks_by_views_7_days_percentile",
        "prep_only__search__orders_by_clicks_1_days_percentile",
        "prep_only__search__orders_by_clicks_14_days_percentile",
        "prep_only__search__orders_by_clicks_7_days_percentile",
        "prep_only__search__orders_by_views_1_days_percentile",
        "prep_only__search__orders_by_views_14_days_percentile",
        "prep_only__search__orders_by_views_28_days_percentile",
        "prep_only__search__orders_by_views_3_days_percentile",
        "cod_pref_and_prep_pref__orders_by_clicks_28_days",
        "cod_pref_and_prep_pref__orders_by_clicks_28_days_percentile",
        "cod_pref_and_prep_pref__orders_by_clicks_3_days_percentile",
        "cod_pref_and_prep_pref__orders_by_views_1_days_percentile",
        "cod_pref_and_prep_pref__orders_by_views_14_days_percentile",
        "cod_pref_and_prep_pref__orders_by_views_28_days_percentile",
        "cod_pref_and_prep_pref__orders_by_views_3_days_percentile",
        "cod_pref_and_prep_pref__orders_by_views_7_days_percentile",
        "cod_pref_and_prep_pref__search__clicks_by_views_1_days_percentile",
        "cod_pref_and_prep_pref__search__clicks_by_views_14_days",
        "cod_pref_and_prep_pref__search__clicks_by_views_28_days_percentile",
        "cod_pref_and_prep_pref__search__clicks_by_views_3_days_percentile",
        "cod_pref_and_prep_pref__search__clicks_by_views_7_days_percentile",
        "cod_pref_and_prep_pref__search__orders_by_clicks_1_days_percentile",
        "cod_pref_and_prep_pref__search__orders_by_clicks_14_days_percentile",
        "cod_pref_and_prep_pref__search__orders_by_clicks_7_days_percentile",
        "cod_pref_and_prep_pref__search__orders_by_views_1_days_percentile",
        "cod_pref_and_prep_pref__search__orders_by_views_14_days_percentile",
        "cod_pref_and_prep_pref__search__orders_by_views_28_days_percentile",
        "cod_pref_and_prep_pref__search__orders_by_views_3_days_percentile",
        "prep_only__clicks_by_views_1_days_percentile",
        "prep_only__clicks_by_views_14_days_percentile",
        "prep_only__clicks_by_views_28_days_percentile",
        "prep_only__clicks_by_views_7_days_percentile",
        "prep_only__orders_by_clicks_1_days_percentile",
        "prep_only__orders_by_clicks_28_days",
        "prep_only__orders_by_clicks_3_days_percentile",
        "prep_only__orders_by_views_1_days_percentile",
        "prep_only__orders_by_views_14_days_percentile",
        "prep_only__orders_by_views_28_days_percentile",
        "prep_only__orders_by_views_3_days_percentile",
        "prep_only__orders_by_views_7_days_percentile",
        "prep_only__search__clicks_by_views_1_days_percentile",
        "cod_only__clicks_by_views_14_days_percentile",
        "cod_only__clicks_by_views_28_days_percentile",
        "cod_only__clicks_by_views_7_days_percentile",
        "cod_only__orders_by_clicks_1_days_percentile",
        "cod_only__orders_by_clicks_14_days",
        "cod_only__orders_by_clicks_28_days",
        "cod_only__orders_by_clicks_28_days_percentile",
        "cod_only__orders_by_clicks_3_days_percentile",
        "cod_only__orders_by_views_1_days_percentile",
        "cod_only__orders_by_views_14_days_percentile",
        "cod_only__orders_by_views_28_days_percentile",
        "cod_only__orders_by_views_3_days_percentile",
        "cod_only__orders_by_views_7_days_percentile",
        "cod_only__search__clicks_by_views_1_days_percentile",
        "cod_only__search__clicks_by_views_14_days_percentile",
        "cod_only__search__clicks_by_views_28_days_percentile",
        "cod_only__search__clicks_by_views_3_days",
        "cod_only__search__clicks_by_views_7_days_percentile",
        "cod_only__search__orders_by_clicks_1_days_percentile",
        "cod_only__search__orders_by_clicks_14_days_percentile",
        "cod_only__search__orders_by_clicks_7_days_percentile",
        "cod_only__search__orders_by_views_1_days_percentile",
        "cod_only__search__orders_by_views_14_days_percentile",
        "cod_only__search__orders_by_views_28_days_percentile",
        "cod_only__search__orders_by_views_3_days_percentile",
        "cod_pref_and_prep_pref__clicks_by_views_1_days_percentile",
        "cod_pref_and_prep_pref__clicks_by_views_14_days_percentile",
        "cod_pref_and_prep_pref__clicks_by_views_28_days",
        "cod_pref_and_prep_pref__clicks_by_views_7_days_percentile",
        "cod_pref_and_prep_pref__orders_by_clicks_1_days_percentile",
        "cod_pref_and_prep_pref__orders_by_clicks_14_days",
        "more_than_75p_user_api_user_orders_percentage",
        "affiliate_pred_enduser_total_orders_by_clicks",
        "cod_only__clicks_by_views_56_days",
        "cod_only__orders_by_clicks_56_days_percentile",
        "cod_only__orders_by_views_56_days_percentile",
        "cod_only__search__clicks_by_views_56_days_percentile",
        "cod_only__search__orders_by_views_56_days_percentile",
        "cod_pref_and_prep_pref__clicks_by_views_56_days",
        "cod_pref_and_prep_pref__orders_by_clicks_56_days",
        "prep_only__orders_by_clicks_56_days",
        "prep_only__orders_by_views_56_days_percentile",
        "prep_only__search__clicks_by_views_56_days",
        "num_img_review_By_num_review_28_days",
        "qr_orders_By_sub_orders_7_days",
        "return_orders_By_sub_orders_7_days"].iter()
        .map(|s| s.to_string())
        .collect();
    
    let query = Query {
        entity_label: "catalog".to_string(),
        feature_groups: vec![
            FeatureGroup {
                label: "derived_fp32".to_string(),
                feature_labels,
            },
        ],
        keys_schema: vec!["catalog_id".to_string()],
        keys: vec![
            Keys { cols: vec!["176".to_string()] },
            Keys { cols: vec!["179".to_string()] },
        ],
        metadata: HashMap::new(),
    };
    
    // Create request with timeout - use method chaining for efficiency
    let mut request = tonic::Request::new(query);
    request.set_timeout(Duration::from_secs(5));

    // Insert pre-built metadata values - AsciiMetadataValue clone is cheap (just increments ref count)
    request.metadata_mut().insert(
        "online-feature-store-auth-token",
        auth_token.clone(),
    );
    request.metadata_mut().insert(
        "online-feature-store-caller-id",
        caller_id.clone(),
    );

    // Clone client only when needed - Tonic client is internally Arc-based
    // This is the same pattern Go uses - the client is thread-safe
    let mut client = client.clone();
    let response = client.retrieve_features(request).await?;
    Ok(response.into_inner())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Configure Tokio runtime for optimal I/O performance
    // Use fewer worker threads for I/O-bound workloads to reduce context switching overhead
    let worker_threads = std::thread::available_parallelism()
        .map(|n| n.get().min(4))
        .unwrap_or(4); // Default to 4 if unavailable
    
    let rt = tokio::runtime::Builder::new_multi_thread()
        .worker_threads(worker_threads) // Limit to 4 threads max for I/O workloads
        .enable_io()
        .enable_time()
        .build()?;

    rt.block_on(async_main())
}

async fn async_main() -> Result<(), Box<dyn std::error::Error>> {
    println!("Connecting to feature store...");

    // Configure channel with optimizations for high-performance IO
    // Following article recommendations: connection multiplexing efficiency
    let channel = Endpoint::from_static("http://online-feature-store-api.int.meesho.int:80")
        // Connection timeout - how long to wait for initial connection
        .timeout(Duration::from_secs(10))
        // HTTP/2 keepalive settings for connection reuse
        // Interval between HTTP/2 Ping frames (30 seconds)
        .http2_keep_alive_interval(Duration::from_secs(30))
        // Timeout for keepalive ping acknowledgment (10 seconds)
        .keep_alive_timeout(Duration::from_secs(10))
        // Send keepalive pings even when connection is idle
        // This is critical for connection multiplexing efficiency
        .keep_alive_while_idle(true)
        // Connect - single connection handles thousands of concurrent streams
        .connect()
        .await?;

    // Create client - this is cheap to clone, uses Arc internally
    let client = RetrieveClient::new(channel);
    let state = Arc::new(AppState::new(client)?);

    let app = Router::new()
        .route("/retrieve-features", post(retrieve_features))
        .with_state(state)
        .layer(CorsLayer::permissive());

    println!("Starting rust-caller-new on http://0.0.0.0:8080");
    let listener = tokio::net::TcpListener::bind("0.0.0.0:8080").await?;
    axum::serve(listener, app).await?;

    Ok(())
}


