apiVersion: v2
name: inferflow
description: A Helm chart for the Inferflow inference orchestration service
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: BharatMLStack Team
    email: ml-oss@meesho.com
