// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: predict.proto

package predict

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Predict_InferPointWise_FullMethodName = "/Predict/InferPointWise"
	Predict_InferPairWise_FullMethodName  = "/Predict/InferPairWise"
	Predict_InferSlateWise_FullMethodName = "/Predict/InferSlateWise"
)

// PredictClient is the client API for Predict service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PredictClient interface {
	InferPointWise(ctx context.Context, in *PointWiseRequest, opts ...grpc.CallOption) (*PointWiseResponse, error)
	InferPairWise(ctx context.Context, in *PairWiseRequest, opts ...grpc.CallOption) (*PairWiseResponse, error)
	InferSlateWise(ctx context.Context, in *SlateWiseRequest, opts ...grpc.CallOption) (*SlateWiseResponse, error)
}

type predictClient struct {
	cc grpc.ClientConnInterface
}

func NewPredictClient(cc grpc.ClientConnInterface) PredictClient {
	return &predictClient{cc}
}

func (c *predictClient) InferPointWise(ctx context.Context, in *PointWiseRequest, opts ...grpc.CallOption) (*PointWiseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PointWiseResponse)
	err := c.cc.Invoke(ctx, Predict_InferPointWise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictClient) InferPairWise(ctx context.Context, in *PairWiseRequest, opts ...grpc.CallOption) (*PairWiseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairWiseResponse)
	err := c.cc.Invoke(ctx, Predict_InferPairWise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictClient) InferSlateWise(ctx context.Context, in *SlateWiseRequest, opts ...grpc.CallOption) (*SlateWiseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlateWiseResponse)
	err := c.cc.Invoke(ctx, Predict_InferSlateWise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PredictServer is the server API for Predict service.
// All implementations must embed UnimplementedPredictServer
// for forward compatibility.
type PredictServer interface {
	InferPointWise(context.Context, *PointWiseRequest) (*PointWiseResponse, error)
	InferPairWise(context.Context, *PairWiseRequest) (*PairWiseResponse, error)
	InferSlateWise(context.Context, *SlateWiseRequest) (*SlateWiseResponse, error)
	mustEmbedUnimplementedPredictServer()
}

// UnimplementedPredictServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPredictServer struct{}

func (UnimplementedPredictServer) InferPointWise(context.Context, *PointWiseRequest) (*PointWiseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InferPointWise not implemented")
}
func (UnimplementedPredictServer) InferPairWise(context.Context, *PairWiseRequest) (*PairWiseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InferPairWise not implemented")
}
func (UnimplementedPredictServer) InferSlateWise(context.Context, *SlateWiseRequest) (*SlateWiseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InferSlateWise not implemented")
}
func (UnimplementedPredictServer) mustEmbedUnimplementedPredictServer() {}
func (UnimplementedPredictServer) testEmbeddedByValue()                 {}

// UnsafePredictServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PredictServer will
// result in compilation errors.
type UnsafePredictServer interface {
	mustEmbedUnimplementedPredictServer()
}

func RegisterPredictServer(s grpc.ServiceRegistrar, srv PredictServer) {
	// If the following call panics, it indicates UnimplementedPredictServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Predict_ServiceDesc, srv)
}

func _Predict_InferPointWise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointWiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictServer).InferPointWise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Predict_InferPointWise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictServer).InferPointWise(ctx, req.(*PointWiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Predict_InferPairWise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairWiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictServer).InferPairWise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Predict_InferPairWise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictServer).InferPairWise(ctx, req.(*PairWiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Predict_InferSlateWise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlateWiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictServer).InferSlateWise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Predict_InferSlateWise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictServer).InferSlateWise(ctx, req.(*SlateWiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Predict_ServiceDesc is the grpc.ServiceDesc for Predict service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Predict_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Predict",
	HandlerType: (*PredictServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InferPointWise",
			Handler:    _Predict_InferPointWise_Handler,
		},
		{
			MethodName: "InferPairWise",
			Handler:    _Predict_InferPairWise_Handler,
		},
		{
			MethodName: "InferSlateWise",
			Handler:    _Predict_InferSlateWise_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "predict.proto",
}
