version: '3.8'

services:
  trufflebox-ui:
    build:
      context: .
      dockerfile: DockerFile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_BASE_URL=${REACT_APP_BASE_URL:-http://localhost:9090}
        - REACT_APP_HORIZON_BASE_URL=${REACT_APP_HORIZON_BASE_URL:-http://horizon.int.meesho.int}
    container_name: trufflebox-ui
    ports:
      - "9090:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL:-http://localhost:9090}
      - REACT_APP_HORIZON_BASE_URL=${REACT_APP_HORIZON_BASE_URL:-http://horizon.int.meesho.int}
    restart: unless-stopped