// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: time_series.proto

package timeseries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InteractionType int32

const (
	InteractionType_CLICK InteractionType = 0
	InteractionType_ORDER InteractionType = 1
)

// Enum value maps for InteractionType.
var (
	InteractionType_name = map[int32]string{
		0: "CLICK",
		1: "ORDER",
	}
	InteractionType_value = map[string]int32{
		"CLICK": 0,
		"ORDER": 1,
	}
)

func (x InteractionType) Enum() *InteractionType {
	p := new(InteractionType)
	*p = x
	return p
}

func (x InteractionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractionType) Descriptor() protoreflect.EnumDescriptor {
	return file_time_series_proto_enumTypes[0].Descriptor()
}

func (InteractionType) Type() protoreflect.EnumType {
	return &file_time_series_proto_enumTypes[0]
}

func (x InteractionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractionType.Descriptor instead.
func (InteractionType) EnumDescriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{0}
}

type PersistClickDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data          []*ClickData           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistClickDataRequest) Reset() {
	*x = PersistClickDataRequest{}
	mi := &file_time_series_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistClickDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistClickDataRequest) ProtoMessage() {}

func (x *PersistClickDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistClickDataRequest.ProtoReflect.Descriptor instead.
func (*PersistClickDataRequest) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{0}
}

func (x *PersistClickDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PersistClickDataRequest) GetData() []*ClickData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClickData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogId     int32                  `protobuf:"varint,1,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickData) Reset() {
	*x = ClickData{}
	mi := &file_time_series_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickData) ProtoMessage() {}

func (x *ClickData) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickData.ProtoReflect.Descriptor instead.
func (*ClickData) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{1}
}

func (x *ClickData) GetCatalogId() int32 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

func (x *ClickData) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ClickData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClickData) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type PersistOrderDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data          []*OrderData           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistOrderDataRequest) Reset() {
	*x = PersistOrderDataRequest{}
	mi := &file_time_series_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistOrderDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistOrderDataRequest) ProtoMessage() {}

func (x *PersistOrderDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistOrderDataRequest.ProtoReflect.Descriptor instead.
func (*PersistOrderDataRequest) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{2}
}

func (x *PersistOrderDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PersistOrderDataRequest) GetData() []*OrderData {
	if x != nil {
		return x.Data
	}
	return nil
}

type OrderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogId     int32                  `protobuf:"varint,1,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SubOrderNum   string                 `protobuf:"bytes,3,opt,name=sub_order_num,json=subOrderNum,proto3" json:"sub_order_num,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderData) Reset() {
	*x = OrderData{}
	mi := &file_time_series_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderData) ProtoMessage() {}

func (x *OrderData) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderData.ProtoReflect.Descriptor instead.
func (*OrderData) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{3}
}

func (x *OrderData) GetCatalogId() int32 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

func (x *OrderData) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderData) GetSubOrderNum() string {
	if x != nil {
		return x.SubOrderNum
	}
	return ""
}

func (x *OrderData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OrderData) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type PersistDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistDataResponse) Reset() {
	*x = PersistDataResponse{}
	mi := &file_time_series_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistDataResponse) ProtoMessage() {}

func (x *PersistDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistDataResponse.ProtoReflect.Descriptor instead.
func (*PersistDataResponse) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{4}
}

func (x *PersistDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RetrieveDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTimestamp int64                  `protobuf:"varint,2,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   int64                  `protobuf:"varint,3,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetrieveDataRequest) Reset() {
	*x = RetrieveDataRequest{}
	mi := &file_time_series_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDataRequest) ProtoMessage() {}

func (x *RetrieveDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDataRequest.ProtoReflect.Descriptor instead.
func (*RetrieveDataRequest) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{5}
}

func (x *RetrieveDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RetrieveDataRequest) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *RetrieveDataRequest) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *RetrieveDataRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RetrieveInteractionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InteractionTypes []InteractionType      `protobuf:"varint,2,rep,packed,name=interaction_types,json=interactionTypes,proto3,enum=proto.InteractionType" json:"interaction_types,omitempty"`
	StartTimestamp   int64                  `protobuf:"varint,3,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp     int64                  `protobuf:"varint,4,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	Limit            int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RetrieveInteractionsRequest) Reset() {
	*x = RetrieveInteractionsRequest{}
	mi := &file_time_series_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveInteractionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveInteractionsRequest) ProtoMessage() {}

func (x *RetrieveInteractionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveInteractionsRequest.ProtoReflect.Descriptor instead.
func (*RetrieveInteractionsRequest) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{6}
}

func (x *RetrieveInteractionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RetrieveInteractionsRequest) GetInteractionTypes() []InteractionType {
	if x != nil {
		return x.InteractionTypes
	}
	return nil
}

func (x *RetrieveInteractionsRequest) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *RetrieveInteractionsRequest) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *RetrieveInteractionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RetrieveInteractionsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Data          map[string]*InteractionData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveInteractionsResponse) Reset() {
	*x = RetrieveInteractionsResponse{}
	mi := &file_time_series_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveInteractionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveInteractionsResponse) ProtoMessage() {}

func (x *RetrieveInteractionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveInteractionsResponse.ProtoReflect.Descriptor instead.
func (*RetrieveInteractionsResponse) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{7}
}

func (x *RetrieveInteractionsResponse) GetData() map[string]*InteractionData {
	if x != nil {
		return x.Data
	}
	return nil
}

type InteractionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClickEvents   []*ClickEvent          `protobuf:"bytes,1,rep,name=click_events,json=clickEvents,proto3" json:"click_events,omitempty"`
	OrderEvents   []*OrderEvent          `protobuf:"bytes,2,rep,name=order_events,json=orderEvents,proto3" json:"order_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionData) Reset() {
	*x = InteractionData{}
	mi := &file_time_series_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionData) ProtoMessage() {}

func (x *InteractionData) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionData.ProtoReflect.Descriptor instead.
func (*InteractionData) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{8}
}

func (x *InteractionData) GetClickEvents() []*ClickEvent {
	if x != nil {
		return x.ClickEvents
	}
	return nil
}

func (x *InteractionData) GetOrderEvents() []*OrderEvent {
	if x != nil {
		return x.OrderEvents
	}
	return nil
}

type RetrieveClickDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ClickEvent          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveClickDataResponse) Reset() {
	*x = RetrieveClickDataResponse{}
	mi := &file_time_series_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveClickDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveClickDataResponse) ProtoMessage() {}

func (x *RetrieveClickDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveClickDataResponse.ProtoReflect.Descriptor instead.
func (*RetrieveClickDataResponse) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{9}
}

func (x *RetrieveClickDataResponse) GetData() []*ClickEvent {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClickEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogId     int32                  `protobuf:"varint,2,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickEvent) Reset() {
	*x = ClickEvent{}
	mi := &file_time_series_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickEvent) ProtoMessage() {}

func (x *ClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickEvent.ProtoReflect.Descriptor instead.
func (*ClickEvent) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{10}
}

func (x *ClickEvent) GetCatalogId() int32 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

func (x *ClickEvent) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ClickEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClickEvent) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type RetrieveOrderDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*OrderEvent          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveOrderDataResponse) Reset() {
	*x = RetrieveOrderDataResponse{}
	mi := &file_time_series_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveOrderDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveOrderDataResponse) ProtoMessage() {}

func (x *RetrieveOrderDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveOrderDataResponse.ProtoReflect.Descriptor instead.
func (*RetrieveOrderDataResponse) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{11}
}

func (x *RetrieveOrderDataResponse) GetData() []*OrderEvent {
	if x != nil {
		return x.Data
	}
	return nil
}

type OrderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogId     int32                  `protobuf:"varint,2,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SubOrderNum   string                 `protobuf:"bytes,4,opt,name=sub_order_num,json=subOrderNum,proto3" json:"sub_order_num,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	mi := &file_time_series_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_time_series_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_time_series_proto_rawDescGZIP(), []int{12}
}

func (x *OrderEvent) GetCatalogId() int32 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

func (x *OrderEvent) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderEvent) GetSubOrderNum() string {
	if x != nil {
		return x.SubOrderNum
	}
	return ""
}

func (x *OrderEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OrderEvent) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

var File_time_series_proto protoreflect.FileDescriptor

const file_time_series_proto_rawDesc = "" +
	"\n" +
	"\x11time_series.proto\x12\x05proto\"X\n" +
	"\x17PersistClickDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x04data\x18\x02 \x03(\v2\x10.proto.ClickDataR\x04data\"\x83\x01\n" +
	"\tClickData\x12\x1d\n" +
	"\n" +
	"catalog_id\x18\x01 \x01(\x05R\tcatalogId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\"X\n" +
	"\x17PersistOrderDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x04data\x18\x02 \x03(\v2\x10.proto.OrderDataR\x04data\"\xa7\x01\n" +
	"\tOrderData\x12\x1d\n" +
	"\n" +
	"catalog_id\x18\x01 \x01(\x05R\tcatalogId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\x12\"\n" +
	"\rsub_order_num\x18\x03 \x01(\tR\vsubOrderNum\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"/\n" +
	"\x13PersistDataResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x92\x01\n" +
	"\x13RetrieveDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fstart_timestamp\x18\x02 \x01(\x03R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x03 \x01(\x03R\fendTimestamp\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xdf\x01\n" +
	"\x1bRetrieveInteractionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12C\n" +
	"\x11interaction_types\x18\x02 \x03(\x0e2\x16.proto.InteractionTypeR\x10interactionTypes\x12'\n" +
	"\x0fstart_timestamp\x18\x03 \x01(\x03R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x04 \x01(\x03R\fendTimestamp\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\xb2\x01\n" +
	"\x1cRetrieveInteractionsResponse\x12A\n" +
	"\x04data\x18\x01 \x03(\v2-.proto.RetrieveInteractionsResponse.DataEntryR\x04data\x1aO\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.proto.InteractionDataR\x05value:\x028\x01\"}\n" +
	"\x0fInteractionData\x124\n" +
	"\fclick_events\x18\x01 \x03(\v2\x11.proto.ClickEventR\vclickEvents\x124\n" +
	"\forder_events\x18\x02 \x03(\v2\x11.proto.OrderEventR\vorderEvents\"B\n" +
	"\x19RetrieveClickDataResponse\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.proto.ClickEventR\x04data\"\x84\x01\n" +
	"\n" +
	"ClickEvent\x12\x1d\n" +
	"\n" +
	"catalog_id\x18\x02 \x01(\x05R\tcatalogId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"B\n" +
	"\x19RetrieveOrderDataResponse\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.proto.OrderEventR\x04data\"\xa8\x01\n" +
	"\n" +
	"OrderEvent\x12\x1d\n" +
	"\n" +
	"catalog_id\x18\x02 \x01(\x05R\tcatalogId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12\"\n" +
	"\rsub_order_num\x18\x04 \x01(\tR\vsubOrderNum\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata*'\n" +
	"\x0fInteractionType\x12\t\n" +
	"\x05CLICK\x10\x00\x12\t\n" +
	"\x05ORDER\x10\x012\xe4\x03\n" +
	"!InteractionStoreTimeSeriesService\x12P\n" +
	"\x10PersistClickData\x12\x1e.proto.PersistClickDataRequest\x1a\x1a.proto.PersistDataResponse\"\x00\x12P\n" +
	"\x10PersistOrderData\x12\x1e.proto.PersistOrderDataRequest\x1a\x1a.proto.PersistDataResponse\"\x00\x12[\n" +
	"\x19RetrieveClickInteractions\x12\x1a.proto.RetrieveDataRequest\x1a .proto.RetrieveClickDataResponse\"\x00\x12[\n" +
	"\x19RetrieveOrderInteractions\x12\x1a.proto.RetrieveDataRequest\x1a .proto.RetrieveOrderDataResponse\"\x00\x12a\n" +
	"\x14RetrieveInteractions\x12\".proto.RetrieveInteractionsRequest\x1a#.proto.RetrieveInteractionsResponse\"\x00BOZMgithub.com/Meesho/BharatMLStack/go-sdk/pkg/proto/interaction-store/timeseriesb\x06proto3"

var (
	file_time_series_proto_rawDescOnce sync.Once
	file_time_series_proto_rawDescData []byte
)

func file_time_series_proto_rawDescGZIP() []byte {
	file_time_series_proto_rawDescOnce.Do(func() {
		file_time_series_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_time_series_proto_rawDesc), len(file_time_series_proto_rawDesc)))
	})
	return file_time_series_proto_rawDescData
}

var file_time_series_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_time_series_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_time_series_proto_goTypes = []any{
	(InteractionType)(0),                 // 0: proto.InteractionType
	(*PersistClickDataRequest)(nil),      // 1: proto.PersistClickDataRequest
	(*ClickData)(nil),                    // 2: proto.ClickData
	(*PersistOrderDataRequest)(nil),      // 3: proto.PersistOrderDataRequest
	(*OrderData)(nil),                    // 4: proto.OrderData
	(*PersistDataResponse)(nil),          // 5: proto.PersistDataResponse
	(*RetrieveDataRequest)(nil),          // 6: proto.RetrieveDataRequest
	(*RetrieveInteractionsRequest)(nil),  // 7: proto.RetrieveInteractionsRequest
	(*RetrieveInteractionsResponse)(nil), // 8: proto.RetrieveInteractionsResponse
	(*InteractionData)(nil),              // 9: proto.InteractionData
	(*RetrieveClickDataResponse)(nil),    // 10: proto.RetrieveClickDataResponse
	(*ClickEvent)(nil),                   // 11: proto.ClickEvent
	(*RetrieveOrderDataResponse)(nil),    // 12: proto.RetrieveOrderDataResponse
	(*OrderEvent)(nil),                   // 13: proto.OrderEvent
	nil,                                  // 14: proto.RetrieveInteractionsResponse.DataEntry
}
var file_time_series_proto_depIdxs = []int32{
	2,  // 0: proto.PersistClickDataRequest.data:type_name -> proto.ClickData
	4,  // 1: proto.PersistOrderDataRequest.data:type_name -> proto.OrderData
	0,  // 2: proto.RetrieveInteractionsRequest.interaction_types:type_name -> proto.InteractionType
	14, // 3: proto.RetrieveInteractionsResponse.data:type_name -> proto.RetrieveInteractionsResponse.DataEntry
	11, // 4: proto.InteractionData.click_events:type_name -> proto.ClickEvent
	13, // 5: proto.InteractionData.order_events:type_name -> proto.OrderEvent
	11, // 6: proto.RetrieveClickDataResponse.data:type_name -> proto.ClickEvent
	13, // 7: proto.RetrieveOrderDataResponse.data:type_name -> proto.OrderEvent
	9,  // 8: proto.RetrieveInteractionsResponse.DataEntry.value:type_name -> proto.InteractionData
	1,  // 9: proto.InteractionStoreTimeSeriesService.PersistClickData:input_type -> proto.PersistClickDataRequest
	3,  // 10: proto.InteractionStoreTimeSeriesService.PersistOrderData:input_type -> proto.PersistOrderDataRequest
	6,  // 11: proto.InteractionStoreTimeSeriesService.RetrieveClickInteractions:input_type -> proto.RetrieveDataRequest
	6,  // 12: proto.InteractionStoreTimeSeriesService.RetrieveOrderInteractions:input_type -> proto.RetrieveDataRequest
	7,  // 13: proto.InteractionStoreTimeSeriesService.RetrieveInteractions:input_type -> proto.RetrieveInteractionsRequest
	5,  // 14: proto.InteractionStoreTimeSeriesService.PersistClickData:output_type -> proto.PersistDataResponse
	5,  // 15: proto.InteractionStoreTimeSeriesService.PersistOrderData:output_type -> proto.PersistDataResponse
	10, // 16: proto.InteractionStoreTimeSeriesService.RetrieveClickInteractions:output_type -> proto.RetrieveClickDataResponse
	12, // 17: proto.InteractionStoreTimeSeriesService.RetrieveOrderInteractions:output_type -> proto.RetrieveOrderDataResponse
	8,  // 18: proto.InteractionStoreTimeSeriesService.RetrieveInteractions:output_type -> proto.RetrieveInteractionsResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_time_series_proto_init() }
func file_time_series_proto_init() {
	if File_time_series_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_time_series_proto_rawDesc), len(file_time_series_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_time_series_proto_goTypes,
		DependencyIndexes: file_time_series_proto_depIdxs,
		EnumInfos:         file_time_series_proto_enumTypes,
		MessageInfos:      file_time_series_proto_msgTypes,
	}.Build()
	File_time_series_proto = out.File
	file_time_series_proto_goTypes = nil
	file_time_series_proto_depIdxs = nil
}
