// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: numerix.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Numerix_Compute_FullMethodName = "/numerix.Numerix/Compute"
)

// NumerixClient is the client API for Numerix service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NumerixClient interface {
	Compute(ctx context.Context, in *NumerixRequestProto, opts ...grpc.CallOption) (*NumerixResponseProto, error)
}

type numerixClient struct {
	cc grpc.ClientConnInterface
}

func NewNumerixClient(cc grpc.ClientConnInterface) NumerixClient {
	return &numerixClient{cc}
}

func (c *numerixClient) Compute(ctx context.Context, in *NumerixRequestProto, opts ...grpc.CallOption) (*NumerixResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NumerixResponseProto)
	err := c.cc.Invoke(ctx, Numerix_Compute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NumerixServer is the server API for Numerix service.
// All implementations must embed UnimplementedNumerixServer
// for forward compatibility.
type NumerixServer interface {
	Compute(context.Context, *NumerixRequestProto) (*NumerixResponseProto, error)
	mustEmbedUnimplementedNumerixServer()
}

// UnimplementedNumerixServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNumerixServer struct{}

func (UnimplementedNumerixServer) Compute(context.Context, *NumerixRequestProto) (*NumerixResponseProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compute not implemented")
}
func (UnimplementedNumerixServer) mustEmbedUnimplementedNumerixServer() {}
func (UnimplementedNumerixServer) testEmbeddedByValue()                 {}

// UnsafeNumerixServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NumerixServer will
// result in compilation errors.
type UnsafeNumerixServer interface {
	mustEmbedUnimplementedNumerixServer()
}

func RegisterNumerixServer(s grpc.ServiceRegistrar, srv NumerixServer) {
	// If the following call pancis, it indicates UnimplementedNumerixServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Numerix_ServiceDesc, srv)
}

func _Numerix_Compute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumerixRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumerixServer).Compute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Numerix_Compute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumerixServer).Compute(ctx, req.(*NumerixRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

// Numerix_ServiceDesc is the grpc.ServiceDesc for Numerix service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Numerix_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "numerix.Numerix",
	HandlerType: (*NumerixServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compute",
			Handler:    _Numerix_Compute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "numerix.proto",
}
