// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: numerix.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumerixRequestProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntityScoreData *EntityScoreData       `protobuf:"bytes,1,opt,name=entity_score_data,json=entityScoreData,proto3" json:"entity_score_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NumerixRequestProto) Reset() {
	*x = NumerixRequestProto{}
	mi := &file_numerix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumerixRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumerixRequestProto) ProtoMessage() {}

func (x *NumerixRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_numerix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumerixRequestProto.ProtoReflect.Descriptor instead.
func (*NumerixRequestProto) Descriptor() ([]byte, []int) {
	return file_numerix_proto_rawDescGZIP(), []int{0}
}

func (x *NumerixRequestProto) GetEntityScoreData() *EntityScoreData {
	if x != nil {
		return x.EntityScoreData
	}
	return nil
}

type EntityScoreData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        []string               `protobuf:"bytes,1,rep,name=schema,proto3" json:"schema,omitempty"`
	EntityScores  []*Score               `protobuf:"bytes,2,rep,name=entity_scores,json=entityScores,proto3" json:"entity_scores,omitempty"`
	ComputeId     string                 `protobuf:"bytes,3,opt,name=compute_id,json=computeId,proto3" json:"compute_id,omitempty"`
	DataType      *string                `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3,oneof" json:"data_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityScoreData) Reset() {
	*x = EntityScoreData{}
	mi := &file_numerix_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityScoreData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityScoreData) ProtoMessage() {}

func (x *EntityScoreData) ProtoReflect() protoreflect.Message {
	mi := &file_numerix_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityScoreData.ProtoReflect.Descriptor instead.
func (*EntityScoreData) Descriptor() ([]byte, []int) {
	return file_numerix_proto_rawDescGZIP(), []int{1}
}

func (x *EntityScoreData) GetSchema() []string {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *EntityScoreData) GetEntityScores() []*Score {
	if x != nil {
		return x.EntityScores
	}
	return nil
}

func (x *EntityScoreData) GetComputeId() string {
	if x != nil {
		return x.ComputeId
	}
	return ""
}

func (x *EntityScoreData) GetDataType() string {
	if x != nil && x.DataType != nil {
		return *x.DataType
	}
	return ""
}

type Score struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MatrixFormat:
	//
	//	*Score_StringData
	//	*Score_ByteData
	MatrixFormat  isScore_MatrixFormat `protobuf_oneof:"matrix_format"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Score) Reset() {
	*x = Score{}
	mi := &file_numerix_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_numerix_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_numerix_proto_rawDescGZIP(), []int{2}
}

func (x *Score) GetMatrixFormat() isScore_MatrixFormat {
	if x != nil {
		return x.MatrixFormat
	}
	return nil
}

func (x *Score) GetStringData() *StringList {
	if x != nil {
		if x, ok := x.MatrixFormat.(*Score_StringData); ok {
			return x.StringData
		}
	}
	return nil
}

func (x *Score) GetByteData() *ByteList {
	if x != nil {
		if x, ok := x.MatrixFormat.(*Score_ByteData); ok {
			return x.ByteData
		}
	}
	return nil
}

type isScore_MatrixFormat interface {
	isScore_MatrixFormat()
}

type Score_StringData struct {
	StringData *StringList `protobuf:"bytes,1,opt,name=string_data,json=stringData,proto3,oneof"`
}

type Score_ByteData struct {
	ByteData *ByteList `protobuf:"bytes,2,opt,name=byte_data,json=byteData,proto3,oneof"`
}

func (*Score_StringData) isScore_MatrixFormat() {}

func (*Score_ByteData) isScore_MatrixFormat() {}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_numerix_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_numerix_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_numerix_proto_rawDescGZIP(), []int{3}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ByteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByteList) Reset() {
	*x = ByteList{}
	mi := &file_numerix_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteList) ProtoMessage() {}

func (x *ByteList) ProtoReflect() protoreflect.Message {
	mi := &file_numerix_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteList.ProtoReflect.Descriptor instead.
func (*ByteList) Descriptor() ([]byte, []int) {
	return file_numerix_proto_rawDescGZIP(), []int{4}
}

func (x *ByteList) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type NumerixResponseProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*NumerixResponseProto_ComputationScoreData
	//	*NumerixResponseProto_Error
	Response      isNumerixResponseProto_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumerixResponseProto) Reset() {
	*x = NumerixResponseProto{}
	mi := &file_numerix_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumerixResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumerixResponseProto) ProtoMessage() {}

func (x *NumerixResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_numerix_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumerixResponseProto.ProtoReflect.Descriptor instead.
func (*NumerixResponseProto) Descriptor() ([]byte, []int) {
	return file_numerix_proto_rawDescGZIP(), []int{5}
}

func (x *NumerixResponseProto) GetResponse() isNumerixResponseProto_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *NumerixResponseProto) GetComputationScoreData() *ComputationScoreData {
	if x != nil {
		if x, ok := x.Response.(*NumerixResponseProto_ComputationScoreData); ok {
			return x.ComputationScoreData
		}
	}
	return nil
}

func (x *NumerixResponseProto) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*NumerixResponseProto_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isNumerixResponseProto_Response interface {
	isNumerixResponseProto_Response()
}

type NumerixResponseProto_ComputationScoreData struct {
	ComputationScoreData *ComputationScoreData `protobuf:"bytes,1,opt,name=computation_score_data,json=computationScoreData,proto3,oneof"`
}

type NumerixResponseProto_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*NumerixResponseProto_ComputationScoreData) isNumerixResponseProto_Response() {}

func (*NumerixResponseProto_Error) isNumerixResponseProto_Response() {}

type ComputationScoreData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Schema            []string               `protobuf:"bytes,1,rep,name=schema,proto3" json:"schema,omitempty"`
	ComputationScores []*Score               `protobuf:"bytes,2,rep,name=computation_scores,json=computationScores,proto3" json:"computation_scores,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ComputationScoreData) Reset() {
	*x = ComputationScoreData{}
	mi := &file_numerix_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputationScoreData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputationScoreData) ProtoMessage() {}

func (x *ComputationScoreData) ProtoReflect() protoreflect.Message {
	mi := &file_numerix_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputationScoreData.ProtoReflect.Descriptor instead.
func (*ComputationScoreData) Descriptor() ([]byte, []int) {
	return file_numerix_proto_rawDescGZIP(), []int{6}
}

func (x *ComputationScoreData) GetSchema() []string {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ComputationScoreData) GetComputationScores() []*Score {
	if x != nil {
		return x.ComputationScores
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_numerix_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_numerix_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_numerix_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_numerix_proto protoreflect.FileDescriptor

const file_numerix_proto_rawDesc = "" +
	"\n" +
	"\rnumerix.proto\x12\anumerix\"[\n" +
	"\x13NumerixRequestProto\x12D\n" +
	"\x11entity_score_data\x18\x01 \x01(\v2\x18.numerix.EntityScoreDataR\x0fentityScoreData\"\xad\x01\n" +
	"\x0fEntityScoreData\x12\x16\n" +
	"\x06schema\x18\x01 \x03(\tR\x06schema\x123\n" +
	"\rentity_scores\x18\x02 \x03(\v2\x0e.numerix.ScoreR\fentityScores\x12\x1d\n" +
	"\n" +
	"compute_id\x18\x03 \x01(\tR\tcomputeId\x12 \n" +
	"\tdata_type\x18\x04 \x01(\tH\x00R\bdataType\x88\x01\x01B\f\n" +
	"\n" +
	"_data_type\"\x82\x01\n" +
	"\x05Score\x126\n" +
	"\vstring_data\x18\x01 \x01(\v2\x13.numerix.StringListH\x00R\n" +
	"stringData\x120\n" +
	"\tbyte_data\x18\x02 \x01(\v2\x11.numerix.ByteListH\x00R\bbyteDataB\x0f\n" +
	"\rmatrix_format\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\"\n" +
	"\bByteList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"\xa1\x01\n" +
	"\x14NumerixResponseProto\x12U\n" +
	"\x16computation_score_data\x18\x01 \x01(\v2\x1d.numerix.ComputationScoreDataH\x00R\x14computationScoreData\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x0e.numerix.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"m\n" +
	"\x14ComputationScoreData\x12\x16\n" +
	"\x06schema\x18\x01 \x03(\tR\x06schema\x12=\n" +
	"\x12computation_scores\x18\x02 \x03(\v2\x0e.numerix.ScoreR\x11computationScores\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2Q\n" +
	"\aNumerix\x12F\n" +
	"\aCompute\x12\x1c.numerix.NumerixRequestProto\x1a\x1d.numerix.NumerixResponseProtoB\x15Z\x13../../numerix/protob\x06proto3"

var (
	file_numerix_proto_rawDescOnce sync.Once
	file_numerix_proto_rawDescData []byte
)

func file_numerix_proto_rawDescGZIP() []byte {
	file_numerix_proto_rawDescOnce.Do(func() {
		file_numerix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_numerix_proto_rawDesc), len(file_numerix_proto_rawDesc)))
	})
	return file_numerix_proto_rawDescData
}

var file_numerix_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_numerix_proto_goTypes = []any{
	(*NumerixRequestProto)(nil),  // 0: numerix.NumerixRequestProto
	(*EntityScoreData)(nil),      // 1: numerix.EntityScoreData
	(*Score)(nil),                // 2: numerix.Score
	(*StringList)(nil),           // 3: numerix.StringList
	(*ByteList)(nil),             // 4: numerix.ByteList
	(*NumerixResponseProto)(nil), // 5: numerix.NumerixResponseProto
	(*ComputationScoreData)(nil), // 6: numerix.ComputationScoreData
	(*Error)(nil),                // 7: numerix.Error
}
var file_numerix_proto_depIdxs = []int32{
	1, // 0: numerix.NumerixRequestProto.entity_score_data:type_name -> numerix.EntityScoreData
	2, // 1: numerix.EntityScoreData.entity_scores:type_name -> numerix.Score
	3, // 2: numerix.Score.string_data:type_name -> numerix.StringList
	4, // 3: numerix.Score.byte_data:type_name -> numerix.ByteList
	6, // 4: numerix.NumerixResponseProto.computation_score_data:type_name -> numerix.ComputationScoreData
	7, // 5: numerix.NumerixResponseProto.error:type_name -> numerix.Error
	2, // 6: numerix.ComputationScoreData.computation_scores:type_name -> numerix.Score
	0, // 7: numerix.Numerix.Compute:input_type -> numerix.NumerixRequestProto
	5, // 8: numerix.Numerix.Compute:output_type -> numerix.NumerixResponseProto
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_numerix_proto_init() }
func file_numerix_proto_init() {
	if File_numerix_proto != nil {
		return
	}
	file_numerix_proto_msgTypes[1].OneofWrappers = []any{}
	file_numerix_proto_msgTypes[2].OneofWrappers = []any{
		(*Score_StringData)(nil),
		(*Score_ByteData)(nil),
	}
	file_numerix_proto_msgTypes[5].OneofWrappers = []any{
		(*NumerixResponseProto_ComputationScoreData)(nil),
		(*NumerixResponseProto_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_numerix_proto_rawDesc), len(file_numerix_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_numerix_proto_goTypes,
		DependencyIndexes: file_numerix_proto_depIdxs,
		MessageInfos:      file_numerix_proto_msgTypes,
	}.Build()
	File_numerix_proto = out.File
	file_numerix_proto_goTypes = nil
	file_numerix_proto_depIdxs = nil
}
