// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: inferflow.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Inferflow_RetrieveModelScore_FullMethodName = "/Inferflow/RetrieveModelScore"
)

// InferflowClient is the client API for Inferflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferflowClient interface {
	RetrieveModelScore(ctx context.Context, in *InferflowRequestProto, opts ...grpc.CallOption) (*InferflowResponseProto, error)
}

type inferflowClient struct {
	cc grpc.ClientConnInterface
}

func NewInferflowClient(cc grpc.ClientConnInterface) InferflowClient {
	return &inferflowClient{cc}
}

func (c *inferflowClient) RetrieveModelScore(ctx context.Context, in *InferflowRequestProto, opts ...grpc.CallOption) (*InferflowResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferflowResponseProto)
	err := c.cc.Invoke(ctx, Inferflow_RetrieveModelScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferflowServer is the server API for Inferflow service.
// All implementations must embed UnimplementedInferflowServer
// for forward compatibility.
type InferflowServer interface {
	RetrieveModelScore(context.Context, *InferflowRequestProto) (*InferflowResponseProto, error)
	mustEmbedUnimplementedInferflowServer()
}

// UnimplementedInferflowServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferflowServer struct{}

func (UnimplementedInferflowServer) RetrieveModelScore(context.Context, *InferflowRequestProto) (*InferflowResponseProto, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveModelScore not implemented")
}
func (UnimplementedInferflowServer) mustEmbedUnimplementedInferflowServer() {}
func (UnimplementedInferflowServer) testEmbeddedByValue()                   {}

// UnsafeInferflowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferflowServer will
// result in compilation errors.
type UnsafeInferflowServer interface {
	mustEmbedUnimplementedInferflowServer()
}

func RegisterInferflowServer(s grpc.ServiceRegistrar, srv InferflowServer) {
	// If the following call panics, it indicates UnimplementedInferflowServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Inferflow_ServiceDesc, srv)
}

func _Inferflow_RetrieveModelScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferflowRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferflowServer).RetrieveModelScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inferflow_RetrieveModelScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferflowServer).RetrieveModelScore(ctx, req.(*InferflowRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

// Inferflow_ServiceDesc is the grpc.ServiceDesc for Inferflow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inferflow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Inferflow",
	HandlerType: (*InferflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveModelScore",
			Handler:    _Inferflow_RetrieveModelScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inferflow.proto",
}
