// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: inferflow_logging.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InferflowLog is the message structure for inference logging
type InferflowLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrackingId    string                 `protobuf:"bytes,2,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	ModelConfigId string                 `protobuf:"bytes,3,opt,name=model_config_id,json=modelConfigId,proto3" json:"model_config_id,omitempty"`
	Entities      []string               `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`
	Features      []*PerEntityFeatures   `protobuf:"bytes,5,rep,name=features,proto3" json:"features,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ParentEntity  []string               `protobuf:"bytes,7,rep,name=parent_entity,json=parentEntity,proto3" json:"parent_entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferflowLog) Reset() {
	*x = InferflowLog{}
	mi := &file_inferflow_logging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferflowLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferflowLog) ProtoMessage() {}

func (x *InferflowLog) ProtoReflect() protoreflect.Message {
	mi := &file_inferflow_logging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferflowLog.ProtoReflect.Descriptor instead.
func (*InferflowLog) Descriptor() ([]byte, []int) {
	return file_inferflow_logging_proto_rawDescGZIP(), []int{0}
}

func (x *InferflowLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InferflowLog) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *InferflowLog) GetModelConfigId() string {
	if x != nil {
		return x.ModelConfigId
	}
	return ""
}

func (x *InferflowLog) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *InferflowLog) GetFeatures() []*PerEntityFeatures {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *InferflowLog) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InferflowLog) GetParentEntity() []string {
	if x != nil {
		return x.ParentEntity
	}
	return nil
}

type PerEntityFeatures struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EncodedFeatures []byte                 `protobuf:"bytes,1,opt,name=encoded_features,json=encodedFeatures,proto3" json:"encoded_features,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PerEntityFeatures) Reset() {
	*x = PerEntityFeatures{}
	mi := &file_inferflow_logging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerEntityFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerEntityFeatures) ProtoMessage() {}

func (x *PerEntityFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_inferflow_logging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerEntityFeatures.ProtoReflect.Descriptor instead.
func (*PerEntityFeatures) Descriptor() ([]byte, []int) {
	return file_inferflow_logging_proto_rawDescGZIP(), []int{1}
}

func (x *PerEntityFeatures) GetEncodedFeatures() []byte {
	if x != nil {
		return x.EncodedFeatures
	}
	return nil
}

var File_inferflow_logging_proto protoreflect.FileDescriptor

const file_inferflow_logging_proto_rawDesc = "" +
	"\n" +
	"\x17inferflow_logging.proto\"\xfd\x01\n" +
	"\fInferflowLog\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtracking_id\x18\x02 \x01(\tR\n" +
	"trackingId\x12&\n" +
	"\x0fmodel_config_id\x18\x03 \x01(\tR\rmodelConfigId\x12\x1a\n" +
	"\bentities\x18\x04 \x03(\tR\bentities\x12.\n" +
	"\bfeatures\x18\x05 \x03(\v2\x12.PerEntityFeaturesR\bfeatures\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\fR\bmetadata\x12#\n" +
	"\rparent_entity\x18\a \x03(\tR\fparentEntity\">\n" +
	"\x11PerEntityFeatures\x12)\n" +
	"\x10encoded_features\x18\x01 \x01(\fR\x0fencodedFeaturesB\tZ\a../grpcb\x06proto3"

var (
	file_inferflow_logging_proto_rawDescOnce sync.Once
	file_inferflow_logging_proto_rawDescData []byte
)

func file_inferflow_logging_proto_rawDescGZIP() []byte {
	file_inferflow_logging_proto_rawDescOnce.Do(func() {
		file_inferflow_logging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inferflow_logging_proto_rawDesc), len(file_inferflow_logging_proto_rawDesc)))
	})
	return file_inferflow_logging_proto_rawDescData
}

var file_inferflow_logging_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_inferflow_logging_proto_goTypes = []any{
	(*InferflowLog)(nil),      // 0: InferflowLog
	(*PerEntityFeatures)(nil), // 1: PerEntityFeatures
}
var file_inferflow_logging_proto_depIdxs = []int32{
	1, // 0: InferflowLog.features:type_name -> PerEntityFeatures
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inferflow_logging_proto_init() }
func file_inferflow_logging_proto_init() {
	if File_inferflow_logging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inferflow_logging_proto_rawDesc), len(file_inferflow_logging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inferflow_logging_proto_goTypes,
		DependencyIndexes: file_inferflow_logging_proto_depIdxs,
		MessageInfos:      file_inferflow_logging_proto_msgTypes,
	}.Build()
	File_inferflow_logging_proto = out.File
	file_inferflow_logging_proto_goTypes = nil
	file_inferflow_logging_proto_depIdxs = nil
}
