// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: kafka_request.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KafkaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *KafkaEventValue       `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Headers       *anypb.Any             `protobuf:"bytes,2,opt,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KafkaRequest) Reset() {
	*x = KafkaRequest{}
	mi := &file_kafka_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaRequest) ProtoMessage() {}

func (x *KafkaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaRequest.ProtoReflect.Descriptor instead.
func (*KafkaRequest) Descriptor() ([]byte, []int) {
	return file_kafka_request_proto_rawDescGZIP(), []int{0}
}

func (x *KafkaRequest) GetValue() *KafkaEventValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KafkaRequest) GetHeaders() *anypb.Any {
	if x != nil {
		return x.Headers
	}
	return nil
}

type KafkaEventValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Properties    *anypb.Any             `protobuf:"bytes,4,opt,name=properties,proto3" json:"properties,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KafkaEventValue) Reset() {
	*x = KafkaEventValue{}
	mi := &file_kafka_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaEventValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaEventValue) ProtoMessage() {}

func (x *KafkaEventValue) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaEventValue.ProtoReflect.Descriptor instead.
func (*KafkaEventValue) Descriptor() ([]byte, []int) {
	return file_kafka_request_proto_rawDescGZIP(), []int{1}
}

func (x *KafkaEventValue) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *KafkaEventValue) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *KafkaEventValue) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *KafkaEventValue) GetProperties() *anypb.Any {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *KafkaEventValue) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_kafka_request_proto protoreflect.FileDescriptor

const file_kafka_request_proto_rawDesc = "" +
	"\n" +
	"\x13kafka_request.proto\x1a\x19google/protobuf/any.proto\"f\n" +
	"\fKafkaRequest\x12&\n" +
	"\x05value\x18\x01 \x01(\v2\x10.KafkaEventValueR\x05value\x12.\n" +
	"\aheaders\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\aheaders\"\xb9\x01\n" +
	"\x0fKafkaEventValue\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x124\n" +
	"\n" +
	"properties\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\n" +
	"properties\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userIdB\tZ\a../grpcb\x06proto3"

var (
	file_kafka_request_proto_rawDescOnce sync.Once
	file_kafka_request_proto_rawDescData []byte
)

func file_kafka_request_proto_rawDescGZIP() []byte {
	file_kafka_request_proto_rawDescOnce.Do(func() {
		file_kafka_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kafka_request_proto_rawDesc), len(file_kafka_request_proto_rawDesc)))
	})
	return file_kafka_request_proto_rawDescData
}

var file_kafka_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kafka_request_proto_goTypes = []any{
	(*KafkaRequest)(nil),    // 0: KafkaRequest
	(*KafkaEventValue)(nil), // 1: KafkaEventValue
	(*anypb.Any)(nil),       // 2: google.protobuf.Any
}
var file_kafka_request_proto_depIdxs = []int32{
	1, // 0: KafkaRequest.value:type_name -> KafkaEventValue
	2, // 1: KafkaRequest.headers:type_name -> google.protobuf.Any
	2, // 2: KafkaEventValue.properties:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kafka_request_proto_init() }
func file_kafka_request_proto_init() {
	if File_kafka_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kafka_request_proto_rawDesc), len(file_kafka_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafka_request_proto_goTypes,
		DependencyIndexes: file_kafka_request_proto_depIdxs,
		MessageInfos:      file_kafka_request_proto_msgTypes,
	}.Build()
	File_kafka_request_proto = out.File
	file_kafka_request_proto_goTypes = nil
	file_kafka_request_proto_depIdxs = nil
}
