// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: inferflow.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request
type InferflowRequestProto struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Entities      []*InferflowRequestProto_Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	ModelConfigId string                          `protobuf:"bytes,2,opt,name=model_config_id,json=modelConfigId,proto3" json:"model_config_id,omitempty"`
	TrackingId    string                          `protobuf:"bytes,3,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferflowRequestProto) Reset() {
	*x = InferflowRequestProto{}
	mi := &file_inferflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferflowRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferflowRequestProto) ProtoMessage() {}

func (x *InferflowRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_inferflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferflowRequestProto.ProtoReflect.Descriptor instead.
func (*InferflowRequestProto) Descriptor() ([]byte, []int) {
	return file_inferflow_proto_rawDescGZIP(), []int{0}
}

func (x *InferflowRequestProto) GetEntities() []*InferflowRequestProto_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *InferflowRequestProto) GetModelConfigId() string {
	if x != nil {
		return x.ModelConfigId
	}
	return ""
}

func (x *InferflowRequestProto) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

// Response
type InferflowResponseProto struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	ComponentData []*InferflowResponseProto_ComponentData `protobuf:"bytes,1,rep,name=component_data,json=componentData,proto3" json:"component_data,omitempty"`
	Error         *InferflowResponseProto_Error           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferflowResponseProto) Reset() {
	*x = InferflowResponseProto{}
	mi := &file_inferflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferflowResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferflowResponseProto) ProtoMessage() {}

func (x *InferflowResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_inferflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferflowResponseProto.ProtoReflect.Descriptor instead.
func (*InferflowResponseProto) Descriptor() ([]byte, []int) {
	return file_inferflow_proto_rawDescGZIP(), []int{1}
}

func (x *InferflowResponseProto) GetComponentData() []*InferflowResponseProto_ComponentData {
	if x != nil {
		return x.ComponentData
	}
	return nil
}

func (x *InferflowResponseProto) GetError() *InferflowResponseProto_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type InferflowRequestProto_Entity struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Entity        string                                  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Ids           []string                                `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	Features      []*InferflowRequestProto_Entity_Feature `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferflowRequestProto_Entity) Reset() {
	*x = InferflowRequestProto_Entity{}
	mi := &file_inferflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferflowRequestProto_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferflowRequestProto_Entity) ProtoMessage() {}

func (x *InferflowRequestProto_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_inferflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferflowRequestProto_Entity.ProtoReflect.Descriptor instead.
func (*InferflowRequestProto_Entity) Descriptor() ([]byte, []int) {
	return file_inferflow_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InferflowRequestProto_Entity) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *InferflowRequestProto_Entity) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *InferflowRequestProto_Entity) GetFeatures() []*InferflowRequestProto_Entity_Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

type InferflowRequestProto_Entity_Feature struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IdsFeatureValue []string               `protobuf:"bytes,2,rep,name=ids_feature_value,json=idsFeatureValue,proto3" json:"ids_feature_value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InferflowRequestProto_Entity_Feature) Reset() {
	*x = InferflowRequestProto_Entity_Feature{}
	mi := &file_inferflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferflowRequestProto_Entity_Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferflowRequestProto_Entity_Feature) ProtoMessage() {}

func (x *InferflowRequestProto_Entity_Feature) ProtoReflect() protoreflect.Message {
	mi := &file_inferflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferflowRequestProto_Entity_Feature.ProtoReflect.Descriptor instead.
func (*InferflowRequestProto_Entity_Feature) Descriptor() ([]byte, []int) {
	return file_inferflow_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *InferflowRequestProto_Entity_Feature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InferflowRequestProto_Entity_Feature) GetIdsFeatureValue() []string {
	if x != nil {
		return x.IdsFeatureValue
	}
	return nil
}

type InferflowResponseProto_ComponentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []string               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferflowResponseProto_ComponentData) Reset() {
	*x = InferflowResponseProto_ComponentData{}
	mi := &file_inferflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferflowResponseProto_ComponentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferflowResponseProto_ComponentData) ProtoMessage() {}

func (x *InferflowResponseProto_ComponentData) ProtoReflect() protoreflect.Message {
	mi := &file_inferflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferflowResponseProto_ComponentData.ProtoReflect.Descriptor instead.
func (*InferflowResponseProto_ComponentData) Descriptor() ([]byte, []int) {
	return file_inferflow_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InferflowResponseProto_ComponentData) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

type InferflowResponseProto_Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferflowResponseProto_Error) Reset() {
	*x = InferflowResponseProto_Error{}
	mi := &file_inferflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferflowResponseProto_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferflowResponseProto_Error) ProtoMessage() {}

func (x *InferflowResponseProto_Error) ProtoReflect() protoreflect.Message {
	mi := &file_inferflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferflowResponseProto_Error.ProtoReflect.Descriptor instead.
func (*InferflowResponseProto_Error) Descriptor() ([]byte, []int) {
	return file_inferflow_proto_rawDescGZIP(), []int{1, 1}
}

func (x *InferflowResponseProto_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_inferflow_proto protoreflect.FileDescriptor

const file_inferflow_proto_rawDesc = "" +
	"\n" +
	"\x0finferflow.proto\x12\tinferflow\"\xf2\x02\n" +
	"\x15InferflowRequestProto\x12C\n" +
	"\bentities\x18\x01 \x03(\v2'.inferflow.InferflowRequestProto.EntityR\bentities\x12&\n" +
	"\x0fmodel_config_id\x18\x02 \x01(\tR\rmodelConfigId\x12\x1f\n" +
	"\vtracking_id\x18\x03 \x01(\tR\n" +
	"trackingId\x1a\xca\x01\n" +
	"\x06Entity\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x12K\n" +
	"\bfeatures\x18\x03 \x03(\v2/.inferflow.InferflowRequestProto.Entity.FeatureR\bfeatures\x1aI\n" +
	"\aFeature\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x11ids_feature_value\x18\x02 \x03(\tR\x0fidsFeatureValue\"\xf7\x01\n" +
	"\x16InferflowResponseProto\x12V\n" +
	"\x0ecomponent_data\x18\x01 \x03(\v2/.inferflow.InferflowResponseProto.ComponentDataR\rcomponentData\x12=\n" +
	"\x05error\x18\x02 \x01(\v2'.inferflow.InferflowResponseProto.ErrorR\x05error\x1a#\n" +
	"\rComponentData\x12\x12\n" +
	"\x04data\x18\x01 \x03(\tR\x04data\x1a!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2o\n" +
	"\x10InferflowService\x12[\n" +
	"\x12RetrieveModelScore\x12 .inferflow.InferflowRequestProto\x1a!.inferflow.InferflowResponseProto\"\x00BSZQgithub.com/meesho/BharatMLStack/horizon/internal/inferflow/handler/proto/protogenb\x06proto3"

var (
	file_inferflow_proto_rawDescOnce sync.Once
	file_inferflow_proto_rawDescData []byte
)

func file_inferflow_proto_rawDescGZIP() []byte {
	file_inferflow_proto_rawDescOnce.Do(func() {
		file_inferflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inferflow_proto_rawDesc), len(file_inferflow_proto_rawDesc)))
	})
	return file_inferflow_proto_rawDescData
}

var file_inferflow_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_inferflow_proto_goTypes = []any{
	(*InferflowRequestProto)(nil),                // 0: inferflow.InferflowRequestProto
	(*InferflowResponseProto)(nil),               // 1: inferflow.InferflowResponseProto
	(*InferflowRequestProto_Entity)(nil),         // 2: inferflow.InferflowRequestProto.Entity
	(*InferflowRequestProto_Entity_Feature)(nil), // 3: inferflow.InferflowRequestProto.Entity.Feature
	(*InferflowResponseProto_ComponentData)(nil), // 4: inferflow.InferflowResponseProto.ComponentData
	(*InferflowResponseProto_Error)(nil),         // 5: inferflow.InferflowResponseProto.Error
}
var file_inferflow_proto_depIdxs = []int32{
	2, // 0: inferflow.InferflowRequestProto.entities:type_name -> inferflow.InferflowRequestProto.Entity
	4, // 1: inferflow.InferflowResponseProto.component_data:type_name -> inferflow.InferflowResponseProto.ComponentData
	5, // 2: inferflow.InferflowResponseProto.error:type_name -> inferflow.InferflowResponseProto.Error
	3, // 3: inferflow.InferflowRequestProto.Entity.features:type_name -> inferflow.InferflowRequestProto.Entity.Feature
	0, // 4: inferflow.InferflowService.RetrieveModelScore:input_type -> inferflow.InferflowRequestProto
	1, // 5: inferflow.InferflowService.RetrieveModelScore:output_type -> inferflow.InferflowResponseProto
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_inferflow_proto_init() }
func file_inferflow_proto_init() {
	if File_inferflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inferflow_proto_rawDesc), len(file_inferflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inferflow_proto_goTypes,
		DependencyIndexes: file_inferflow_proto_depIdxs,
		MessageInfos:      file_inferflow_proto_msgTypes,
	}.Build()
	File_inferflow_proto = out.File
	file_inferflow_proto_goTypes = nil
	file_inferflow_proto_depIdxs = nil
}
