// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: inferflow.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferflowService_RetrieveModelScore_FullMethodName = "/inferflow.InferflowService/RetrieveModelScore"
)

// InferflowServiceClient is the client API for InferflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferflowServiceClient interface {
	RetrieveModelScore(ctx context.Context, in *InferflowRequestProto, opts ...grpc.CallOption) (*InferflowResponseProto, error)
}

type inferflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferflowServiceClient(cc grpc.ClientConnInterface) InferflowServiceClient {
	return &inferflowServiceClient{cc}
}

func (c *inferflowServiceClient) RetrieveModelScore(ctx context.Context, in *InferflowRequestProto, opts ...grpc.CallOption) (*InferflowResponseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferflowResponseProto)
	err := c.cc.Invoke(ctx, InferflowService_RetrieveModelScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferflowServiceServer is the server API for InferflowService service.
// All implementations must embed UnimplementedInferflowServiceServer
// for forward compatibility.
type InferflowServiceServer interface {
	RetrieveModelScore(context.Context, *InferflowRequestProto) (*InferflowResponseProto, error)
	mustEmbedUnimplementedInferflowServiceServer()
}

// UnimplementedInferflowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferflowServiceServer struct{}

func (UnimplementedInferflowServiceServer) RetrieveModelScore(context.Context, *InferflowRequestProto) (*InferflowResponseProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveModelScore not implemented")
}
func (UnimplementedInferflowServiceServer) mustEmbedUnimplementedInferflowServiceServer() {}
func (UnimplementedInferflowServiceServer) testEmbeddedByValue()                          {}

// UnsafeInferflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferflowServiceServer will
// result in compilation errors.
type UnsafeInferflowServiceServer interface {
	mustEmbedUnimplementedInferflowServiceServer()
}

func RegisterInferflowServiceServer(s grpc.ServiceRegistrar, srv InferflowServiceServer) {
	// If the following call pancis, it indicates UnimplementedInferflowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferflowService_ServiceDesc, srv)
}

func _InferflowService_RetrieveModelScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferflowRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferflowServiceServer).RetrieveModelScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferflowService_RetrieveModelScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferflowServiceServer).RetrieveModelScore(ctx, req.(*InferflowRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

// InferflowService_ServiceDesc is the grpc.ServiceDesc for InferflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inferflow.InferflowService",
	HandlerType: (*InferflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveModelScore",
			Handler:    _InferflowService_RetrieveModelScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inferflow.proto",
}
