// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: predict.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_DataTypeUnknown       DataType = 0
	DataType_DataTypeFP8E5M2       DataType = 1
	DataType_DataTypeFP8E4M3       DataType = 2
	DataType_DataTypeFP16          DataType = 3
	DataType_DataTypeFP32          DataType = 4
	DataType_DataTypeFP64          DataType = 5
	DataType_DataTypeInt8          DataType = 6
	DataType_DataTypeInt16         DataType = 7
	DataType_DataTypeInt32         DataType = 8
	DataType_DataTypeInt64         DataType = 9
	DataType_DataTypeUint8         DataType = 10
	DataType_DataTypeUint16        DataType = 11
	DataType_DataTypeUint32        DataType = 12
	DataType_DataTypeUint64        DataType = 13
	DataType_DataTypeString        DataType = 14
	DataType_DataTypeBool          DataType = 15
	DataType_DataTypeFP8E5M2Vector DataType = 16
	DataType_DataTypeFP8E4M3Vector DataType = 17
	DataType_DataTypeFP16Vector    DataType = 18
	DataType_DataTypeFP32Vector    DataType = 19
	DataType_DataTypeFP64Vector    DataType = 20
	DataType_DataTypeInt8Vector    DataType = 21
	DataType_DataTypeInt16Vector   DataType = 22
	DataType_DataTypeInt32Vector   DataType = 23
	DataType_DataTypeInt64Vector   DataType = 24
	DataType_DataTypeUint8Vector   DataType = 25
	DataType_DataTypeUint16Vector  DataType = 26
	DataType_DataTypeUint32Vector  DataType = 27
	DataType_DataTypeUint64Vector  DataType = 28
	DataType_DataTypeStringVector  DataType = 29
	DataType_DataTypeBoolVector    DataType = 30
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0:  "DataTypeUnknown",
		1:  "DataTypeFP8E5M2",
		2:  "DataTypeFP8E4M3",
		3:  "DataTypeFP16",
		4:  "DataTypeFP32",
		5:  "DataTypeFP64",
		6:  "DataTypeInt8",
		7:  "DataTypeInt16",
		8:  "DataTypeInt32",
		9:  "DataTypeInt64",
		10: "DataTypeUint8",
		11: "DataTypeUint16",
		12: "DataTypeUint32",
		13: "DataTypeUint64",
		14: "DataTypeString",
		15: "DataTypeBool",
		16: "DataTypeFP8E5M2Vector",
		17: "DataTypeFP8E4M3Vector",
		18: "DataTypeFP16Vector",
		19: "DataTypeFP32Vector",
		20: "DataTypeFP64Vector",
		21: "DataTypeInt8Vector",
		22: "DataTypeInt16Vector",
		23: "DataTypeInt32Vector",
		24: "DataTypeInt64Vector",
		25: "DataTypeUint8Vector",
		26: "DataTypeUint16Vector",
		27: "DataTypeUint32Vector",
		28: "DataTypeUint64Vector",
		29: "DataTypeStringVector",
		30: "DataTypeBoolVector",
	}
	DataType_value = map[string]int32{
		"DataTypeUnknown":       0,
		"DataTypeFP8E5M2":       1,
		"DataTypeFP8E4M3":       2,
		"DataTypeFP16":          3,
		"DataTypeFP32":          4,
		"DataTypeFP64":          5,
		"DataTypeInt8":          6,
		"DataTypeInt16":         7,
		"DataTypeInt32":         8,
		"DataTypeInt64":         9,
		"DataTypeUint8":         10,
		"DataTypeUint16":        11,
		"DataTypeUint32":        12,
		"DataTypeUint64":        13,
		"DataTypeString":        14,
		"DataTypeBool":          15,
		"DataTypeFP8E5M2Vector": 16,
		"DataTypeFP8E4M3Vector": 17,
		"DataTypeFP16Vector":    18,
		"DataTypeFP32Vector":    19,
		"DataTypeFP64Vector":    20,
		"DataTypeInt8Vector":    21,
		"DataTypeInt16Vector":   22,
		"DataTypeInt32Vector":   23,
		"DataTypeInt64Vector":   24,
		"DataTypeUint8Vector":   25,
		"DataTypeUint16Vector":  26,
		"DataTypeUint32Vector":  27,
		"DataTypeUint64Vector":  28,
		"DataTypeStringVector":  29,
		"DataTypeBoolVector":    30,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_predict_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_predict_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{0}
}

// Schema definition for a feature column
type FeatureSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType      DataType               `protobuf:"varint,2,opt,name=data_type,json=dataType,proto3,enum=DataType" json:"data_type,omitempty"`
	VectorDim     int32                  `protobuf:"varint,3,opt,name=vector_dim,json=vectorDim,proto3" json:"vector_dim,omitempty"` // 0 = scalar, >0 = fixed vector length
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureSchema) Reset() {
	*x = FeatureSchema{}
	mi := &file_predict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureSchema) ProtoMessage() {}

func (x *FeatureSchema) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureSchema.ProtoReflect.Descriptor instead.
func (*FeatureSchema) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeatureSchema) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DataTypeUnknown
}

func (x *FeatureSchema) GetVectorDim() int32 {
	if x != nil {
		return x.VectorDim
	}
	return 0
}

// A request-level context feature (user, session, device, etc.)
type ContextFeature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	DataType      DataType               `protobuf:"varint,3,opt,name=data_type,json=dataType,proto3,enum=DataType" json:"data_type,omitempty"`
	VectorDim     int32                  `protobuf:"varint,4,opt,name=vector_dim,json=vectorDim,proto3" json:"vector_dim,omitempty"` // 0 = scalar, >0 = fixed vector length
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextFeature) Reset() {
	*x = ContextFeature{}
	mi := &file_predict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextFeature) ProtoMessage() {}

func (x *ContextFeature) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextFeature.ProtoReflect.Descriptor instead.
func (*ContextFeature) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{1}
}

func (x *ContextFeature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContextFeature) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ContextFeature) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DataTypeUnknown
}

func (x *ContextFeature) GetVectorDim() int32 {
	if x != nil {
		return x.VectorDim
	}
	return 0
}

// A single entity to be scored/ranked
type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FeatureValues [][]byte               `protobuf:"bytes,2,rep,name=feature_values,json=featureValues,proto3" json:"feature_values,omitempty"` // aligned with target_input_schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_predict_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{2}
}

func (x *Target) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Target) GetFeatureValues() [][]byte {
	if x != nil {
		return x.FeatureValues
	}
	return nil
}

type TargetScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	OutputValues  [][]byte               `protobuf:"bytes,2,rep,name=output_values,json=outputValues,proto3" json:"output_values,omitempty"` // aligned with target_output_schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetScore) Reset() {
	*x = TargetScore{}
	mi := &file_predict_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetScore) ProtoMessage() {}

func (x *TargetScore) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetScore.ProtoReflect.Descriptor instead.
func (*TargetScore) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{3}
}

func (x *TargetScore) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TargetScore) GetOutputValues() [][]byte {
	if x != nil {
		return x.OutputValues
	}
	return nil
}

type PointWiseRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModelConfigId     string                 `protobuf:"bytes,1,opt,name=model_config_id,json=modelConfigId,proto3" json:"model_config_id,omitempty"`
	TrackingId        string                 `protobuf:"bytes,2,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	ContextFeatures   []*ContextFeature      `protobuf:"bytes,3,rep,name=context_features,json=contextFeatures,proto3" json:"context_features,omitempty"`
	TargetInputSchema []*FeatureSchema       `protobuf:"bytes,4,rep,name=target_input_schema,json=targetInputSchema,proto3" json:"target_input_schema,omitempty"`
	Targets           []*Target              `protobuf:"bytes,5,rep,name=targets,proto3" json:"targets,omitempty"`
	TenantId          string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PointWiseRequest) Reset() {
	*x = PointWiseRequest{}
	mi := &file_predict_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointWiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointWiseRequest) ProtoMessage() {}

func (x *PointWiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointWiseRequest.ProtoReflect.Descriptor instead.
func (*PointWiseRequest) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{4}
}

func (x *PointWiseRequest) GetModelConfigId() string {
	if x != nil {
		return x.ModelConfigId
	}
	return ""
}

func (x *PointWiseRequest) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *PointWiseRequest) GetContextFeatures() []*ContextFeature {
	if x != nil {
		return x.ContextFeatures
	}
	return nil
}

func (x *PointWiseRequest) GetTargetInputSchema() []*FeatureSchema {
	if x != nil {
		return x.TargetInputSchema
	}
	return nil
}

func (x *PointWiseRequest) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *PointWiseRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type PointWiseResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TargetOutputSchema []*FeatureSchema       `protobuf:"bytes,1,rep,name=target_output_schema,json=targetOutputSchema,proto3" json:"target_output_schema,omitempty"`
	TargetScores       []*TargetScore         `protobuf:"bytes,2,rep,name=target_scores,json=targetScores,proto3" json:"target_scores,omitempty"`
	RequestError       string                 `protobuf:"bytes,3,opt,name=request_error,json=requestError,proto3" json:"request_error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PointWiseResponse) Reset() {
	*x = PointWiseResponse{}
	mi := &file_predict_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointWiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointWiseResponse) ProtoMessage() {}

func (x *PointWiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointWiseResponse.ProtoReflect.Descriptor instead.
func (*PointWiseResponse) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{5}
}

func (x *PointWiseResponse) GetTargetOutputSchema() []*FeatureSchema {
	if x != nil {
		return x.TargetOutputSchema
	}
	return nil
}

func (x *PointWiseResponse) GetTargetScores() []*TargetScore {
	if x != nil {
		return x.TargetScores
	}
	return nil
}

func (x *PointWiseResponse) GetRequestError() string {
	if x != nil {
		return x.RequestError
	}
	return ""
}

type TargetPair struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FirstTargetIndex  int32                  `protobuf:"varint,1,opt,name=first_target_index,json=firstTargetIndex,proto3" json:"first_target_index,omitempty"`
	SecondTargetIndex int32                  `protobuf:"varint,2,opt,name=second_target_index,json=secondTargetIndex,proto3" json:"second_target_index,omitempty"`
	FeatureValues     [][]byte               `protobuf:"bytes,3,rep,name=feature_values,json=featureValues,proto3" json:"feature_values,omitempty"` // aligned with pair_input_schema
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TargetPair) Reset() {
	*x = TargetPair{}
	mi := &file_predict_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetPair) ProtoMessage() {}

func (x *TargetPair) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetPair.ProtoReflect.Descriptor instead.
func (*TargetPair) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{6}
}

func (x *TargetPair) GetFirstTargetIndex() int32 {
	if x != nil {
		return x.FirstTargetIndex
	}
	return 0
}

func (x *TargetPair) GetSecondTargetIndex() int32 {
	if x != nil {
		return x.SecondTargetIndex
	}
	return 0
}

func (x *TargetPair) GetFeatureValues() [][]byte {
	if x != nil {
		return x.FeatureValues
	}
	return nil
}

type PairWiseRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModelConfigId     string                 `protobuf:"bytes,1,opt,name=model_config_id,json=modelConfigId,proto3" json:"model_config_id,omitempty"`
	TrackingId        string                 `protobuf:"bytes,2,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	ContextFeatures   []*ContextFeature      `protobuf:"bytes,3,rep,name=context_features,json=contextFeatures,proto3" json:"context_features,omitempty"`
	TargetInputSchema []*FeatureSchema       `protobuf:"bytes,4,rep,name=target_input_schema,json=targetInputSchema,proto3" json:"target_input_schema,omitempty"`
	PairInputSchema   []*FeatureSchema       `protobuf:"bytes,5,rep,name=pair_input_schema,json=pairInputSchema,proto3" json:"pair_input_schema,omitempty"`
	Pairs             []*TargetPair          `protobuf:"bytes,6,rep,name=pairs,proto3" json:"pairs,omitempty"`
	Targets           []*Target              `protobuf:"bytes,7,rep,name=targets,proto3" json:"targets,omitempty"`
	TenantId          string                 `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PairWiseRequest) Reset() {
	*x = PairWiseRequest{}
	mi := &file_predict_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairWiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairWiseRequest) ProtoMessage() {}

func (x *PairWiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairWiseRequest.ProtoReflect.Descriptor instead.
func (*PairWiseRequest) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{7}
}

func (x *PairWiseRequest) GetModelConfigId() string {
	if x != nil {
		return x.ModelConfigId
	}
	return ""
}

func (x *PairWiseRequest) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *PairWiseRequest) GetContextFeatures() []*ContextFeature {
	if x != nil {
		return x.ContextFeatures
	}
	return nil
}

func (x *PairWiseRequest) GetTargetInputSchema() []*FeatureSchema {
	if x != nil {
		return x.TargetInputSchema
	}
	return nil
}

func (x *PairWiseRequest) GetPairInputSchema() []*FeatureSchema {
	if x != nil {
		return x.PairInputSchema
	}
	return nil
}

func (x *PairWiseRequest) GetPairs() []*TargetPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *PairWiseRequest) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *PairWiseRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type PairScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	OutputValues  [][]byte               `protobuf:"bytes,2,rep,name=output_values,json=outputValues,proto3" json:"output_values,omitempty"` // aligned with pair_output_schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairScore) Reset() {
	*x = PairScore{}
	mi := &file_predict_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairScore) ProtoMessage() {}

func (x *PairScore) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairScore.ProtoReflect.Descriptor instead.
func (*PairScore) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{8}
}

func (x *PairScore) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PairScore) GetOutputValues() [][]byte {
	if x != nil {
		return x.OutputValues
	}
	return nil
}

type PairWiseResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PairScores         []*PairScore           `protobuf:"bytes,1,rep,name=pair_scores,json=pairScores,proto3" json:"pair_scores,omitempty"`
	TargetScores       []*TargetScore         `protobuf:"bytes,2,rep,name=target_scores,json=targetScores,proto3" json:"target_scores,omitempty"`
	TargetOutputSchema []*FeatureSchema       `protobuf:"bytes,3,rep,name=target_output_schema,json=targetOutputSchema,proto3" json:"target_output_schema,omitempty"`
	PairOutputSchema   []*FeatureSchema       `protobuf:"bytes,4,rep,name=pair_output_schema,json=pairOutputSchema,proto3" json:"pair_output_schema,omitempty"`
	RequestError       string                 `protobuf:"bytes,5,opt,name=request_error,json=requestError,proto3" json:"request_error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PairWiseResponse) Reset() {
	*x = PairWiseResponse{}
	mi := &file_predict_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairWiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairWiseResponse) ProtoMessage() {}

func (x *PairWiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairWiseResponse.ProtoReflect.Descriptor instead.
func (*PairWiseResponse) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{9}
}

func (x *PairWiseResponse) GetPairScores() []*PairScore {
	if x != nil {
		return x.PairScores
	}
	return nil
}

func (x *PairWiseResponse) GetTargetScores() []*TargetScore {
	if x != nil {
		return x.TargetScores
	}
	return nil
}

func (x *PairWiseResponse) GetTargetOutputSchema() []*FeatureSchema {
	if x != nil {
		return x.TargetOutputSchema
	}
	return nil
}

func (x *PairWiseResponse) GetPairOutputSchema() []*FeatureSchema {
	if x != nil {
		return x.PairOutputSchema
	}
	return nil
}

func (x *PairWiseResponse) GetRequestError() string {
	if x != nil {
		return x.RequestError
	}
	return ""
}

type TargetSlate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetIndices []int32                `protobuf:"varint,1,rep,packed,name=target_indices,json=targetIndices,proto3" json:"target_indices,omitempty"`
	FeatureValues [][]byte               `protobuf:"bytes,2,rep,name=feature_values,json=featureValues,proto3" json:"feature_values,omitempty"` // aligned with slate_input_schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetSlate) Reset() {
	*x = TargetSlate{}
	mi := &file_predict_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetSlate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetSlate) ProtoMessage() {}

func (x *TargetSlate) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetSlate.ProtoReflect.Descriptor instead.
func (*TargetSlate) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{10}
}

func (x *TargetSlate) GetTargetIndices() []int32 {
	if x != nil {
		return x.TargetIndices
	}
	return nil
}

func (x *TargetSlate) GetFeatureValues() [][]byte {
	if x != nil {
		return x.FeatureValues
	}
	return nil
}

type SlateScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	OutputValues  [][]byte               `protobuf:"bytes,2,rep,name=output_values,json=outputValues,proto3" json:"output_values,omitempty"` // aligned with slate_output_schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlateScore) Reset() {
	*x = SlateScore{}
	mi := &file_predict_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlateScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlateScore) ProtoMessage() {}

func (x *SlateScore) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlateScore.ProtoReflect.Descriptor instead.
func (*SlateScore) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{11}
}

func (x *SlateScore) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SlateScore) GetOutputValues() [][]byte {
	if x != nil {
		return x.OutputValues
	}
	return nil
}

type SlateWiseRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModelConfigId     string                 `protobuf:"bytes,1,opt,name=model_config_id,json=modelConfigId,proto3" json:"model_config_id,omitempty"`
	TrackingId        string                 `protobuf:"bytes,2,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	ContextFeatures   []*ContextFeature      `protobuf:"bytes,3,rep,name=context_features,json=contextFeatures,proto3" json:"context_features,omitempty"`
	TargetInputSchema []*FeatureSchema       `protobuf:"bytes,4,rep,name=target_input_schema,json=targetInputSchema,proto3" json:"target_input_schema,omitempty"`
	SlateInputSchema  []*FeatureSchema       `protobuf:"bytes,5,rep,name=slate_input_schema,json=slateInputSchema,proto3" json:"slate_input_schema,omitempty"`
	Slates            []*TargetSlate         `protobuf:"bytes,6,rep,name=slates,proto3" json:"slates,omitempty"`
	Targets           []*Target              `protobuf:"bytes,7,rep,name=targets,proto3" json:"targets,omitempty"`
	TenantId          string                 `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SlateWiseRequest) Reset() {
	*x = SlateWiseRequest{}
	mi := &file_predict_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlateWiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlateWiseRequest) ProtoMessage() {}

func (x *SlateWiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlateWiseRequest.ProtoReflect.Descriptor instead.
func (*SlateWiseRequest) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{12}
}

func (x *SlateWiseRequest) GetModelConfigId() string {
	if x != nil {
		return x.ModelConfigId
	}
	return ""
}

func (x *SlateWiseRequest) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *SlateWiseRequest) GetContextFeatures() []*ContextFeature {
	if x != nil {
		return x.ContextFeatures
	}
	return nil
}

func (x *SlateWiseRequest) GetTargetInputSchema() []*FeatureSchema {
	if x != nil {
		return x.TargetInputSchema
	}
	return nil
}

func (x *SlateWiseRequest) GetSlateInputSchema() []*FeatureSchema {
	if x != nil {
		return x.SlateInputSchema
	}
	return nil
}

func (x *SlateWiseRequest) GetSlates() []*TargetSlate {
	if x != nil {
		return x.Slates
	}
	return nil
}

func (x *SlateWiseRequest) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *SlateWiseRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type SlateWiseResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SlateScores        []*SlateScore          `protobuf:"bytes,1,rep,name=slate_scores,json=slateScores,proto3" json:"slate_scores,omitempty"`
	TargetScores       []*TargetScore         `protobuf:"bytes,2,rep,name=target_scores,json=targetScores,proto3" json:"target_scores,omitempty"`
	TargetOutputSchema []*FeatureSchema       `protobuf:"bytes,3,rep,name=target_output_schema,json=targetOutputSchema,proto3" json:"target_output_schema,omitempty"`
	SlateOutputSchema  []*FeatureSchema       `protobuf:"bytes,4,rep,name=slate_output_schema,json=slateOutputSchema,proto3" json:"slate_output_schema,omitempty"`
	RequestError       string                 `protobuf:"bytes,5,opt,name=request_error,json=requestError,proto3" json:"request_error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SlateWiseResponse) Reset() {
	*x = SlateWiseResponse{}
	mi := &file_predict_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlateWiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlateWiseResponse) ProtoMessage() {}

func (x *SlateWiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlateWiseResponse.ProtoReflect.Descriptor instead.
func (*SlateWiseResponse) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{13}
}

func (x *SlateWiseResponse) GetSlateScores() []*SlateScore {
	if x != nil {
		return x.SlateScores
	}
	return nil
}

func (x *SlateWiseResponse) GetTargetScores() []*TargetScore {
	if x != nil {
		return x.TargetScores
	}
	return nil
}

func (x *SlateWiseResponse) GetTargetOutputSchema() []*FeatureSchema {
	if x != nil {
		return x.TargetOutputSchema
	}
	return nil
}

func (x *SlateWiseResponse) GetSlateOutputSchema() []*FeatureSchema {
	if x != nil {
		return x.SlateOutputSchema
	}
	return nil
}

func (x *SlateWiseResponse) GetRequestError() string {
	if x != nil {
		return x.RequestError
	}
	return ""
}

var File_predict_proto protoreflect.FileDescriptor

const file_predict_proto_rawDesc = "" +
	"\n" +
	"\rpredict.proto\"j\n" +
	"\rFeatureSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\tdata_type\x18\x02 \x01(\x0e2\t.DataTypeR\bdataType\x12\x1d\n" +
	"\n" +
	"vector_dim\x18\x03 \x01(\x05R\tvectorDim\"\x81\x01\n" +
	"\x0eContextFeature\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12&\n" +
	"\tdata_type\x18\x03 \x01(\x0e2\t.DataTypeR\bdataType\x12\x1d\n" +
	"\n" +
	"vector_dim\x18\x04 \x01(\x05R\tvectorDim\"?\n" +
	"\x06Target\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0efeature_values\x18\x02 \x03(\fR\rfeatureValues\"H\n" +
	"\vTargetScore\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12#\n" +
	"\routput_values\x18\x02 \x03(\fR\foutputValues\"\x97\x02\n" +
	"\x10PointWiseRequest\x12&\n" +
	"\x0fmodel_config_id\x18\x01 \x01(\tR\rmodelConfigId\x12\x1f\n" +
	"\vtracking_id\x18\x02 \x01(\tR\n" +
	"trackingId\x12:\n" +
	"\x10context_features\x18\x03 \x03(\v2\x0f.ContextFeatureR\x0fcontextFeatures\x12>\n" +
	"\x13target_input_schema\x18\x04 \x03(\v2\x0e.FeatureSchemaR\x11targetInputSchema\x12!\n" +
	"\atargets\x18\x05 \x03(\v2\a.TargetR\atargets\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"\xad\x01\n" +
	"\x11PointWiseResponse\x12@\n" +
	"\x14target_output_schema\x18\x01 \x03(\v2\x0e.FeatureSchemaR\x12targetOutputSchema\x121\n" +
	"\rtarget_scores\x18\x02 \x03(\v2\f.TargetScoreR\ftargetScores\x12#\n" +
	"\rrequest_error\x18\x03 \x01(\tR\frequestError\"\x91\x01\n" +
	"\n" +
	"TargetPair\x12,\n" +
	"\x12first_target_index\x18\x01 \x01(\x05R\x10firstTargetIndex\x12.\n" +
	"\x13second_target_index\x18\x02 \x01(\x05R\x11secondTargetIndex\x12%\n" +
	"\x0efeature_values\x18\x03 \x03(\fR\rfeatureValues\"\xf5\x02\n" +
	"\x0fPairWiseRequest\x12&\n" +
	"\x0fmodel_config_id\x18\x01 \x01(\tR\rmodelConfigId\x12\x1f\n" +
	"\vtracking_id\x18\x02 \x01(\tR\n" +
	"trackingId\x12:\n" +
	"\x10context_features\x18\x03 \x03(\v2\x0f.ContextFeatureR\x0fcontextFeatures\x12>\n" +
	"\x13target_input_schema\x18\x04 \x03(\v2\x0e.FeatureSchemaR\x11targetInputSchema\x12:\n" +
	"\x11pair_input_schema\x18\x05 \x03(\v2\x0e.FeatureSchemaR\x0fpairInputSchema\x12!\n" +
	"\x05pairs\x18\x06 \x03(\v2\v.TargetPairR\x05pairs\x12!\n" +
	"\atargets\x18\a \x03(\v2\a.TargetR\atargets\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantId\"F\n" +
	"\tPairScore\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12#\n" +
	"\routput_values\x18\x02 \x03(\fR\foutputValues\"\x97\x02\n" +
	"\x10PairWiseResponse\x12+\n" +
	"\vpair_scores\x18\x01 \x03(\v2\n" +
	".PairScoreR\n" +
	"pairScores\x121\n" +
	"\rtarget_scores\x18\x02 \x03(\v2\f.TargetScoreR\ftargetScores\x12@\n" +
	"\x14target_output_schema\x18\x03 \x03(\v2\x0e.FeatureSchemaR\x12targetOutputSchema\x12<\n" +
	"\x12pair_output_schema\x18\x04 \x03(\v2\x0e.FeatureSchemaR\x10pairOutputSchema\x12#\n" +
	"\rrequest_error\x18\x05 \x01(\tR\frequestError\"[\n" +
	"\vTargetSlate\x12%\n" +
	"\x0etarget_indices\x18\x01 \x03(\x05R\rtargetIndices\x12%\n" +
	"\x0efeature_values\x18\x02 \x03(\fR\rfeatureValues\"G\n" +
	"\n" +
	"SlateScore\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12#\n" +
	"\routput_values\x18\x02 \x03(\fR\foutputValues\"\xfb\x02\n" +
	"\x10SlateWiseRequest\x12&\n" +
	"\x0fmodel_config_id\x18\x01 \x01(\tR\rmodelConfigId\x12\x1f\n" +
	"\vtracking_id\x18\x02 \x01(\tR\n" +
	"trackingId\x12:\n" +
	"\x10context_features\x18\x03 \x03(\v2\x0f.ContextFeatureR\x0fcontextFeatures\x12>\n" +
	"\x13target_input_schema\x18\x04 \x03(\v2\x0e.FeatureSchemaR\x11targetInputSchema\x12<\n" +
	"\x12slate_input_schema\x18\x05 \x03(\v2\x0e.FeatureSchemaR\x10slateInputSchema\x12$\n" +
	"\x06slates\x18\x06 \x03(\v2\f.TargetSlateR\x06slates\x12!\n" +
	"\atargets\x18\a \x03(\v2\a.TargetR\atargets\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantId\"\x9d\x02\n" +
	"\x11SlateWiseResponse\x12.\n" +
	"\fslate_scores\x18\x01 \x03(\v2\v.SlateScoreR\vslateScores\x121\n" +
	"\rtarget_scores\x18\x02 \x03(\v2\f.TargetScoreR\ftargetScores\x12@\n" +
	"\x14target_output_schema\x18\x03 \x03(\v2\x0e.FeatureSchemaR\x12targetOutputSchema\x12>\n" +
	"\x13slate_output_schema\x18\x04 \x03(\v2\x0e.FeatureSchemaR\x11slateOutputSchema\x12#\n" +
	"\rrequest_error\x18\x05 \x01(\tR\frequestError*\xb9\x05\n" +
	"\bDataType\x12\x13\n" +
	"\x0fDataTypeUnknown\x10\x00\x12\x13\n" +
	"\x0fDataTypeFP8E5M2\x10\x01\x12\x13\n" +
	"\x0fDataTypeFP8E4M3\x10\x02\x12\x10\n" +
	"\fDataTypeFP16\x10\x03\x12\x10\n" +
	"\fDataTypeFP32\x10\x04\x12\x10\n" +
	"\fDataTypeFP64\x10\x05\x12\x10\n" +
	"\fDataTypeInt8\x10\x06\x12\x11\n" +
	"\rDataTypeInt16\x10\a\x12\x11\n" +
	"\rDataTypeInt32\x10\b\x12\x11\n" +
	"\rDataTypeInt64\x10\t\x12\x11\n" +
	"\rDataTypeUint8\x10\n" +
	"\x12\x12\n" +
	"\x0eDataTypeUint16\x10\v\x12\x12\n" +
	"\x0eDataTypeUint32\x10\f\x12\x12\n" +
	"\x0eDataTypeUint64\x10\r\x12\x12\n" +
	"\x0eDataTypeString\x10\x0e\x12\x10\n" +
	"\fDataTypeBool\x10\x0f\x12\x19\n" +
	"\x15DataTypeFP8E5M2Vector\x10\x10\x12\x19\n" +
	"\x15DataTypeFP8E4M3Vector\x10\x11\x12\x16\n" +
	"\x12DataTypeFP16Vector\x10\x12\x12\x16\n" +
	"\x12DataTypeFP32Vector\x10\x13\x12\x16\n" +
	"\x12DataTypeFP64Vector\x10\x14\x12\x16\n" +
	"\x12DataTypeInt8Vector\x10\x15\x12\x17\n" +
	"\x13DataTypeInt16Vector\x10\x16\x12\x17\n" +
	"\x13DataTypeInt32Vector\x10\x17\x12\x17\n" +
	"\x13DataTypeInt64Vector\x10\x18\x12\x17\n" +
	"\x13DataTypeUint8Vector\x10\x19\x12\x18\n" +
	"\x14DataTypeUint16Vector\x10\x1a\x12\x18\n" +
	"\x14DataTypeUint32Vector\x10\x1b\x12\x18\n" +
	"\x14DataTypeUint64Vector\x10\x1c\x12\x18\n" +
	"\x14DataTypeStringVector\x10\x1d\x12\x16\n" +
	"\x12DataTypeBoolVector\x10\x1e2\xb7\x01\n" +
	"\aPredict\x129\n" +
	"\x0eInferPointWise\x12\x11.PointWiseRequest\x1a\x12.PointWiseResponse\"\x00\x126\n" +
	"\rInferPairWise\x12\x10.PairWiseRequest\x1a\x11.PairWiseResponse\"\x00\x129\n" +
	"\x0eInferSlateWise\x12\x11.SlateWiseRequest\x1a\x12.SlateWiseResponse\"\x00B\x11Z\x0f../grpc/predictb\x06proto3"

var (
	file_predict_proto_rawDescOnce sync.Once
	file_predict_proto_rawDescData []byte
)

func file_predict_proto_rawDescGZIP() []byte {
	file_predict_proto_rawDescOnce.Do(func() {
		file_predict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_predict_proto_rawDesc), len(file_predict_proto_rawDesc)))
	})
	return file_predict_proto_rawDescData
}

var file_predict_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_predict_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_predict_proto_goTypes = []any{
	(DataType)(0),             // 0: DataType
	(*FeatureSchema)(nil),     // 1: FeatureSchema
	(*ContextFeature)(nil),    // 2: ContextFeature
	(*Target)(nil),            // 3: Target
	(*TargetScore)(nil),       // 4: TargetScore
	(*PointWiseRequest)(nil),  // 5: PointWiseRequest
	(*PointWiseResponse)(nil), // 6: PointWiseResponse
	(*TargetPair)(nil),        // 7: TargetPair
	(*PairWiseRequest)(nil),   // 8: PairWiseRequest
	(*PairScore)(nil),         // 9: PairScore
	(*PairWiseResponse)(nil),  // 10: PairWiseResponse
	(*TargetSlate)(nil),       // 11: TargetSlate
	(*SlateScore)(nil),        // 12: SlateScore
	(*SlateWiseRequest)(nil),  // 13: SlateWiseRequest
	(*SlateWiseResponse)(nil), // 14: SlateWiseResponse
}
var file_predict_proto_depIdxs = []int32{
	0,  // 0: FeatureSchema.data_type:type_name -> DataType
	0,  // 1: ContextFeature.data_type:type_name -> DataType
	2,  // 2: PointWiseRequest.context_features:type_name -> ContextFeature
	1,  // 3: PointWiseRequest.target_input_schema:type_name -> FeatureSchema
	3,  // 4: PointWiseRequest.targets:type_name -> Target
	1,  // 5: PointWiseResponse.target_output_schema:type_name -> FeatureSchema
	4,  // 6: PointWiseResponse.target_scores:type_name -> TargetScore
	2,  // 7: PairWiseRequest.context_features:type_name -> ContextFeature
	1,  // 8: PairWiseRequest.target_input_schema:type_name -> FeatureSchema
	1,  // 9: PairWiseRequest.pair_input_schema:type_name -> FeatureSchema
	7,  // 10: PairWiseRequest.pairs:type_name -> TargetPair
	3,  // 11: PairWiseRequest.targets:type_name -> Target
	9,  // 12: PairWiseResponse.pair_scores:type_name -> PairScore
	4,  // 13: PairWiseResponse.target_scores:type_name -> TargetScore
	1,  // 14: PairWiseResponse.target_output_schema:type_name -> FeatureSchema
	1,  // 15: PairWiseResponse.pair_output_schema:type_name -> FeatureSchema
	2,  // 16: SlateWiseRequest.context_features:type_name -> ContextFeature
	1,  // 17: SlateWiseRequest.target_input_schema:type_name -> FeatureSchema
	1,  // 18: SlateWiseRequest.slate_input_schema:type_name -> FeatureSchema
	11, // 19: SlateWiseRequest.slates:type_name -> TargetSlate
	3,  // 20: SlateWiseRequest.targets:type_name -> Target
	12, // 21: SlateWiseResponse.slate_scores:type_name -> SlateScore
	4,  // 22: SlateWiseResponse.target_scores:type_name -> TargetScore
	1,  // 23: SlateWiseResponse.target_output_schema:type_name -> FeatureSchema
	1,  // 24: SlateWiseResponse.slate_output_schema:type_name -> FeatureSchema
	5,  // 25: Predict.InferPointWise:input_type -> PointWiseRequest
	8,  // 26: Predict.InferPairWise:input_type -> PairWiseRequest
	13, // 27: Predict.InferSlateWise:input_type -> SlateWiseRequest
	6,  // 28: Predict.InferPointWise:output_type -> PointWiseResponse
	10, // 29: Predict.InferPairWise:output_type -> PairWiseResponse
	14, // 30: Predict.InferSlateWise:output_type -> SlateWiseResponse
	28, // [28:31] is the sub-list for method output_type
	25, // [25:28] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_predict_proto_init() }
func file_predict_proto_init() {
	if File_predict_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_predict_proto_rawDesc), len(file_predict_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_predict_proto_goTypes,
		DependencyIndexes: file_predict_proto_depIdxs,
		EnumInfos:         file_predict_proto_enumTypes,
		MessageInfos:      file_predict_proto_msgTypes,
	}.Build()
	File_predict_proto = out.File
	file_predict_proto_goTypes = nil
	file_predict_proto_depIdxs = nil
}
