// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: skye.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkyeSimilarCandidateService_GetSimilarCandidates_FullMethodName = "/SkyeSimilarCandidateService/getSimilarCandidates"
)

// SkyeSimilarCandidateServiceClient is the client API for SkyeSimilarCandidateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkyeSimilarCandidateServiceClient interface {
	GetSimilarCandidates(ctx context.Context, in *SkyeRequest, opts ...grpc.CallOption) (*SkyeResponse, error)
}

type skyeSimilarCandidateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkyeSimilarCandidateServiceClient(cc grpc.ClientConnInterface) SkyeSimilarCandidateServiceClient {
	return &skyeSimilarCandidateServiceClient{cc}
}

func (c *skyeSimilarCandidateServiceClient) GetSimilarCandidates(ctx context.Context, in *SkyeRequest, opts ...grpc.CallOption) (*SkyeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkyeResponse)
	err := c.cc.Invoke(ctx, SkyeSimilarCandidateService_GetSimilarCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkyeSimilarCandidateServiceServer is the server API for SkyeSimilarCandidateService service.
// All implementations must embed UnimplementedSkyeSimilarCandidateServiceServer
// for forward compatibility.
type SkyeSimilarCandidateServiceServer interface {
	GetSimilarCandidates(context.Context, *SkyeRequest) (*SkyeResponse, error)
	mustEmbedUnimplementedSkyeSimilarCandidateServiceServer()
}

// UnimplementedSkyeSimilarCandidateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkyeSimilarCandidateServiceServer struct{}

func (UnimplementedSkyeSimilarCandidateServiceServer) GetSimilarCandidates(context.Context, *SkyeRequest) (*SkyeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSimilarCandidates not implemented")
}
func (UnimplementedSkyeSimilarCandidateServiceServer) mustEmbedUnimplementedSkyeSimilarCandidateServiceServer() {
}
func (UnimplementedSkyeSimilarCandidateServiceServer) testEmbeddedByValue() {}

// UnsafeSkyeSimilarCandidateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkyeSimilarCandidateServiceServer will
// result in compilation errors.
type UnsafeSkyeSimilarCandidateServiceServer interface {
	mustEmbedUnimplementedSkyeSimilarCandidateServiceServer()
}

func RegisterSkyeSimilarCandidateServiceServer(s grpc.ServiceRegistrar, srv SkyeSimilarCandidateServiceServer) {
	// If the following call pancis, it indicates UnimplementedSkyeSimilarCandidateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkyeSimilarCandidateService_ServiceDesc, srv)
}

func _SkyeSimilarCandidateService_GetSimilarCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkyeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyeSimilarCandidateServiceServer).GetSimilarCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyeSimilarCandidateService_GetSimilarCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyeSimilarCandidateServiceServer).GetSimilarCandidates(ctx, req.(*SkyeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkyeSimilarCandidateService_ServiceDesc is the grpc.ServiceDesc for SkyeSimilarCandidateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkyeSimilarCandidateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SkyeSimilarCandidateService",
	HandlerType: (*SkyeSimilarCandidateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getSimilarCandidates",
			Handler:    _SkyeSimilarCandidateService_GetSimilarCandidates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skye.proto",
}

const (
	SkyeEmbeddingService_GetCandidateEmbeddingScores_FullMethodName = "/SkyeEmbeddingService/getCandidateEmbeddingScores"
	SkyeEmbeddingService_GetEmbeddingsForCandidates_FullMethodName  = "/SkyeEmbeddingService/getEmbeddingsForCandidates"
)

// SkyeEmbeddingServiceClient is the client API for SkyeEmbeddingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkyeEmbeddingServiceClient interface {
	GetCandidateEmbeddingScores(ctx context.Context, in *EmbeddingDotProductRequest, opts ...grpc.CallOption) (*EmbeddingDotProductResponse, error)
	GetEmbeddingsForCandidates(ctx context.Context, in *SkyeBulkEmbeddingRequest, opts ...grpc.CallOption) (*SkyeBulkEmbeddingResponse, error)
}

type skyeEmbeddingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkyeEmbeddingServiceClient(cc grpc.ClientConnInterface) SkyeEmbeddingServiceClient {
	return &skyeEmbeddingServiceClient{cc}
}

func (c *skyeEmbeddingServiceClient) GetCandidateEmbeddingScores(ctx context.Context, in *EmbeddingDotProductRequest, opts ...grpc.CallOption) (*EmbeddingDotProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingDotProductResponse)
	err := c.cc.Invoke(ctx, SkyeEmbeddingService_GetCandidateEmbeddingScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyeEmbeddingServiceClient) GetEmbeddingsForCandidates(ctx context.Context, in *SkyeBulkEmbeddingRequest, opts ...grpc.CallOption) (*SkyeBulkEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkyeBulkEmbeddingResponse)
	err := c.cc.Invoke(ctx, SkyeEmbeddingService_GetEmbeddingsForCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkyeEmbeddingServiceServer is the server API for SkyeEmbeddingService service.
// All implementations must embed UnimplementedSkyeEmbeddingServiceServer
// for forward compatibility.
type SkyeEmbeddingServiceServer interface {
	GetCandidateEmbeddingScores(context.Context, *EmbeddingDotProductRequest) (*EmbeddingDotProductResponse, error)
	GetEmbeddingsForCandidates(context.Context, *SkyeBulkEmbeddingRequest) (*SkyeBulkEmbeddingResponse, error)
	mustEmbedUnimplementedSkyeEmbeddingServiceServer()
}

// UnimplementedSkyeEmbeddingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkyeEmbeddingServiceServer struct{}

func (UnimplementedSkyeEmbeddingServiceServer) GetCandidateEmbeddingScores(context.Context, *EmbeddingDotProductRequest) (*EmbeddingDotProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCandidateEmbeddingScores not implemented")
}
func (UnimplementedSkyeEmbeddingServiceServer) GetEmbeddingsForCandidates(context.Context, *SkyeBulkEmbeddingRequest) (*SkyeBulkEmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmbeddingsForCandidates not implemented")
}
func (UnimplementedSkyeEmbeddingServiceServer) mustEmbedUnimplementedSkyeEmbeddingServiceServer() {}
func (UnimplementedSkyeEmbeddingServiceServer) testEmbeddedByValue()                              {}

// UnsafeSkyeEmbeddingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkyeEmbeddingServiceServer will
// result in compilation errors.
type UnsafeSkyeEmbeddingServiceServer interface {
	mustEmbedUnimplementedSkyeEmbeddingServiceServer()
}

func RegisterSkyeEmbeddingServiceServer(s grpc.ServiceRegistrar, srv SkyeEmbeddingServiceServer) {
	// If the following call pancis, it indicates UnimplementedSkyeEmbeddingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkyeEmbeddingService_ServiceDesc, srv)
}

func _SkyeEmbeddingService_GetCandidateEmbeddingScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingDotProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyeEmbeddingServiceServer).GetCandidateEmbeddingScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyeEmbeddingService_GetCandidateEmbeddingScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyeEmbeddingServiceServer).GetCandidateEmbeddingScores(ctx, req.(*EmbeddingDotProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyeEmbeddingService_GetEmbeddingsForCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkyeBulkEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyeEmbeddingServiceServer).GetEmbeddingsForCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyeEmbeddingService_GetEmbeddingsForCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyeEmbeddingServiceServer).GetEmbeddingsForCandidates(ctx, req.(*SkyeBulkEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkyeEmbeddingService_ServiceDesc is the grpc.ServiceDesc for SkyeEmbeddingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkyeEmbeddingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SkyeEmbeddingService",
	HandlerType: (*SkyeEmbeddingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getCandidateEmbeddingScores",
			Handler:    _SkyeEmbeddingService_GetCandidateEmbeddingScores_Handler,
		},
		{
			MethodName: "getEmbeddingsForCandidates",
			Handler:    _SkyeEmbeddingService_GetEmbeddingsForCandidates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skye.proto",
}
