{{- if ( default false (.Values.disasterRecovery).enabled ) }}
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
{{- if .Values.externalSecret.annotations }}
  annotations:
{{ toYaml .Values.externalSecret.annotations | indent 4 }}
{{- end }}
  {{- if  .Values.deployment.enabled }}
  name: {{ .Values.deployment.envFrom.secretRef }}-dr
  {{- else if .Values.cron.enabled }}
  name: {{ .Values.cron.envFrom.secretRef }}-dr
  {{- end}}
  namespace: {{ .Values.namespace }}
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      key: {{- if and .Values.infrastructure.vault.drPathReplacement.from .Values.infrastructure.vault.drPathReplacement.to }}
        {{ .Values.externalSecret.path | replace .Values.infrastructure.vault.drPathReplacement.from .Values.infrastructure.vault.drPathReplacement.to }}
      {{- else }}
        {{ .Values.externalSecret.path | replace "org/prd/" "org/dr/" }}
      {{- end }}
  refreshInterval: 15s
  secretStoreRef:
    kind: {{ .Values.infrastructure.secretStore.kind | default "ClusterSecretStore" }}
    name: {{ .Values.infrastructure.secretStore.name | default "vault-backend" }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    {{- if  .Values.deployment.enabled }}
    name: {{ .Values.deployment.envFrom.secretRef }}-dr
    {{- else if .Values.cron.enabled }}
    name: {{ .Values.cron.envFrom.secretRef }}-dr
    {{- end}}
{{- end }}
{{- end }}