package handler

type Config interface {
	RegisterStore(StoreRegisterRequest) (RequestStatus, error)
	ApproveStoreRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetStores() (StoreListResponse, error)
	GetAllStoreRequests() (StoreRequestListResponse, error)
	RegisterEntity(EntityRegisterRequest) (RequestStatus, error)
	ApproveEntityRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetEntities() (EntityListResponse, error)
	GetAllEntityRequests() (EntityRequestListResponse, error)
	RegisterModel(ModelRegisterRequest) (RequestStatus, error)
	ApproveModelRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetModels() (ModelListResponse, error)
	GetAllModelRequests() (ModelRequestListResponse, error)
	RegisterVariant(VariantRegisterRequest) (RequestStatus, error)
	ApproveVariantRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetVariants(string, string) (VariantListResponse, error)
	GetAllVariantRequests() (VariantRequestListResponse, error)
	RegisterFilter(FilterRegisterRequest) (RequestStatus, error)
	ApproveFilterRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetFilters(string) (FilterListResponse, error)
	GetAllFilters() (AllFiltersListResponse, error)
	GetAllFilterRequests() (FilterRequestListResponse, error)
	// OnboardVariant(VariantOnboardingRequest) (RequestStatus, error)
	// ApproveVariantOnboardingRequest(int, ApprovalRequest) (ApprovalResponse, error)
	// GetAllVariantOnboardingRequests() (VariantOnboardingRequestListResponse, error)
	GetVariantOnboardingTasks() (VariantOnboardingTaskListResponse, error)
	RegisterJobFrequency(JobFrequencyRegisterRequest) (RequestStatus, error)
	ApproveJobFrequencyRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetJobFrequencies() (JobFrequencyListResponse, error)
	GetAllJobFrequencyRequests() (JobFrequencyRequestListResponse, error)
	GetMQIdTopics() (MQIdTopicsResponse, error)
	GetVariantsList() (VariantsListResponse, error)
	ScaleUpVariant(VariantScaleUpRequest) (RequestStatus, error)
	ApproveVariantScaleUpRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetAllVariantScaleUpRequests() (VariantScaleUpRequestListResponse, error)
	GetVariantScaleUpTasks() (VariantScaleUpTaskListResponse, error)
	TestVariant(VariantTestRequest) (VariantTestResponse, error)
	GenerateTestRequest(TestRequestGenerationRequest) (TestRequestGenerationResponse, error)
}
