package handler

type Config interface {
	RegisterStore(StoreRegisterRequest) (RequestStatus, error)
	ApproveStoreRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetStores() (StoreListResponse, error)
	GetAllStoreRequests() (StoreRequestListResponse, error)
	RegisterEntity(EntityRegisterRequest) (RequestStatus, error)
	ApproveEntityRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetEntities() (EntityListResponse, error)
	GetAllEntityRequests() (EntityRequestListResponse, error)
	RegisterModel(ModelRegisterRequest) (RequestStatus, error)
	EditModel(ModelEditRequest) (RequestStatus, error)
	ApproveModelRequest(int, ApprovalRequest) (ApprovalResponse, error)
	ApproveModelEditRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetModels() (ModelListResponse, error)
	GetAllModelRequests() (ModelRequestListResponse, error)
	RegisterVariant(VariantRegisterRequest) (RequestStatus, error)
	EditVariant(VariantEditRequest) (RequestStatus, error)
	ApproveVariantRequest(int, ApprovalRequest) (ApprovalResponse, error)
	ApproveVariantEditRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetVariants(string, string) (VariantListResponse, error)
	GetAllVariantRequests() (VariantRequestListResponse, error)
	RegisterFilter(FilterRegisterRequest) (RequestStatus, error)
	ApproveFilterRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetFilters(string) (FilterListResponse, error)
	GetAllFilterRequests() (FilterRequestListResponse, error)
	// CreateQdrantCluster(QdrantClusterRequest) (RequestStatus, error)
	// ApproveQdrantClusterRequest(int, ApprovalRequest) (ApprovalResponse, error)
	// GetQdrantClusters() (ClusterListResponse, error)
	PromoteVariant(VariantPromotionRequest) (RequestStatus, error)
	ApproveVariantPromotionRequest(int, ApprovalRequest) (ApprovalResponse, error)
	OnboardVariant(VariantOnboardingRequest) (RequestStatus, error)
	ApproveVariantOnboardingRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetAllVariantOnboardingRequests() (VariantOnboardingRequestListResponse, error)
	GetVariantOnboardingTasks() (VariantOnboardingTaskListResponse, error)
	RegisterJobFrequency(JobFrequencyRegisterRequest) (RequestStatus, error)
	ApproveJobFrequencyRequest(int, ApprovalRequest) (ApprovalResponse, error)
	GetJobFrequencies() (JobFrequencyListResponse, error)
	GetAllJobFrequencyRequests() (JobFrequencyRequestListResponse, error)
	GetMQIdTopics() (MQIdTopicsResponse, error)
	GetVariantsList() (VariantsListResponse, error)
}
