// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: skye.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter_Operator int32

const (
	Filter_IN          Filter_Operator = 0
	Filter_NIN         Filter_Operator = 1
	Filter_EX          Filter_Operator = 2
	Filter_SEARCH      Filter_Operator = 3
	Filter_LTE         Filter_Operator = 4
	Filter_GTE         Filter_Operator = 5
	Filter_BTWE        Filter_Operator = 6
	Filter_BTW         Filter_Operator = 7
	Filter_LT          Filter_Operator = 8
	Filter_GT          Filter_Operator = 9
	Filter_LAST_X_DAYS Filter_Operator = 10
	Filter_WTHN        Filter_Operator = 11
)

// Enum value maps for Filter_Operator.
var (
	Filter_Operator_name = map[int32]string{
		0:  "IN",
		1:  "NIN",
		2:  "EX",
		3:  "SEARCH",
		4:  "LTE",
		5:  "GTE",
		6:  "BTWE",
		7:  "BTW",
		8:  "LT",
		9:  "GT",
		10: "LAST_X_DAYS",
		11: "WTHN",
	}
	Filter_Operator_value = map[string]int32{
		"IN":          0,
		"NIN":         1,
		"EX":          2,
		"SEARCH":      3,
		"LTE":         4,
		"GTE":         5,
		"BTWE":        6,
		"BTW":         7,
		"LT":          8,
		"GT":          9,
		"LAST_X_DAYS": 10,
		"WTHN":        11,
	}
)

func (x Filter_Operator) Enum() *Filter_Operator {
	p := new(Filter_Operator)
	*p = x
	return p
}

func (x Filter_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Filter_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_skye_proto_enumTypes[0].Descriptor()
}

func (Filter_Operator) Type() protoreflect.EnumType {
	return &file_skye_proto_enumTypes[0]
}

func (x Filter_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Filter_Operator.Descriptor instead.
func (Filter_Operator) EnumDescriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{3, 0}
}

type SkyeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity        string       `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	CandidateIds  []string     `protobuf:"bytes,2,rep,name=candidateIds,proto3" json:"candidateIds,omitempty"`
	Limit         int32        `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	ModelName     string       `protobuf:"bytes,4,opt,name=modelName,proto3" json:"modelName,omitempty"`
	Variant       string       `protobuf:"bytes,5,opt,name=variant,proto3" json:"variant,omitempty"`
	Filters       []*Filters   `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty"`
	Attribute     []string     `protobuf:"bytes,7,rep,name=attribute,proto3" json:"attribute,omitempty"`
	Embeddings    []*Embedding `protobuf:"bytes,8,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	GlobalFilters *Filters     `protobuf:"bytes,9,opt,name=globalFilters,proto3" json:"globalFilters,omitempty"`
}

func (x *SkyeRequest) Reset() {
	*x = SkyeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkyeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkyeRequest) ProtoMessage() {}

func (x *SkyeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkyeRequest.ProtoReflect.Descriptor instead.
func (*SkyeRequest) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{0}
}

func (x *SkyeRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *SkyeRequest) GetCandidateIds() []string {
	if x != nil {
		return x.CandidateIds
	}
	return nil
}

func (x *SkyeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SkyeRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *SkyeRequest) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *SkyeRequest) GetFilters() []*Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SkyeRequest) GetAttribute() []string {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *SkyeRequest) GetEmbeddings() []*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *SkyeRequest) GetGlobalFilters() *Filters {
	if x != nil {
		return x.GlobalFilters
	}
	return nil
}

type Embedding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Embedding []float64 `protobuf:"fixed64,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{1}
}

func (x *Embedding) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type Filters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter []*Filter `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty"`
}

func (x *Filters) Reset() {
	*x = Filters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{2}
}

func (x *Filters) GetFilter() []*Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field  string          `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Op     Filter_Operator `protobuf:"varint,2,opt,name=op,proto3,enum=Filter_Operator" json:"op,omitempty"`
	Values []string        `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{3}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetOp() Filter_Operator {
	if x != nil {
		return x.Op
	}
	return Filter_IN
}

func (x *Filter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type CandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candidates []*CandidateResponse_Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
}

func (x *CandidateResponse) Reset() {
	*x = CandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateResponse) ProtoMessage() {}

func (x *CandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateResponse.ProtoReflect.Descriptor instead.
func (*CandidateResponse) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{4}
}

func (x *CandidateResponse) GetCandidates() []*CandidateResponse_Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type SkyeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*CandidateResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *SkyeResponse) Reset() {
	*x = SkyeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkyeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkyeResponse) ProtoMessage() {}

func (x *SkyeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkyeResponse.ProtoReflect.Descriptor instead.
func (*SkyeResponse) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{5}
}

func (x *SkyeResponse) GetResponses() []*CandidateResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type EmbeddingDotProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity       string    `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	CandidateIds []string  `protobuf:"bytes,2,rep,name=candidateIds,proto3" json:"candidateIds,omitempty"`
	Embedding    []float64 `protobuf:"fixed64,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	ModelName    string    `protobuf:"bytes,4,opt,name=modelName,proto3" json:"modelName,omitempty"`
	Variant      string    `protobuf:"bytes,5,opt,name=variant,proto3" json:"variant,omitempty"`
}

func (x *EmbeddingDotProductRequest) Reset() {
	*x = EmbeddingDotProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbeddingDotProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingDotProductRequest) ProtoMessage() {}

func (x *EmbeddingDotProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingDotProductRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingDotProductRequest) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{6}
}

func (x *EmbeddingDotProductRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *EmbeddingDotProductRequest) GetCandidateIds() []string {
	if x != nil {
		return x.CandidateIds
	}
	return nil
}

func (x *EmbeddingDotProductRequest) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbeddingDotProductRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *EmbeddingDotProductRequest) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type CandidateEmbeddingScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CandidateId string  `protobuf:"bytes,1,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	Score       float64 `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *CandidateEmbeddingScore) Reset() {
	*x = CandidateEmbeddingScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandidateEmbeddingScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateEmbeddingScore) ProtoMessage() {}

func (x *CandidateEmbeddingScore) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateEmbeddingScore.ProtoReflect.Descriptor instead.
func (*CandidateEmbeddingScore) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{7}
}

func (x *CandidateEmbeddingScore) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *CandidateEmbeddingScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type EmbeddingDotProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CandidateEmbeddingScores []*CandidateEmbeddingScore `protobuf:"bytes,1,rep,name=candidateEmbeddingScores,proto3" json:"candidateEmbeddingScores,omitempty"`
}

func (x *EmbeddingDotProductResponse) Reset() {
	*x = EmbeddingDotProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbeddingDotProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingDotProductResponse) ProtoMessage() {}

func (x *EmbeddingDotProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingDotProductResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingDotProductResponse) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{8}
}

func (x *EmbeddingDotProductResponse) GetCandidateEmbeddingScores() []*CandidateEmbeddingScore {
	if x != nil {
		return x.CandidateEmbeddingScores
	}
	return nil
}

type SkyeBulkEmbeddingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity       string   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	CandidateIds []string `protobuf:"bytes,2,rep,name=candidateIds,proto3" json:"candidateIds,omitempty"`
	ModelName    string   `protobuf:"bytes,4,opt,name=modelName,proto3" json:"modelName,omitempty"`
	Variant      string   `protobuf:"bytes,5,opt,name=variant,proto3" json:"variant,omitempty"`
}

func (x *SkyeBulkEmbeddingRequest) Reset() {
	*x = SkyeBulkEmbeddingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkyeBulkEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkyeBulkEmbeddingRequest) ProtoMessage() {}

func (x *SkyeBulkEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkyeBulkEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*SkyeBulkEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{9}
}

func (x *SkyeBulkEmbeddingRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *SkyeBulkEmbeddingRequest) GetCandidateIds() []string {
	if x != nil {
		return x.CandidateIds
	}
	return nil
}

func (x *SkyeBulkEmbeddingRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *SkyeBulkEmbeddingRequest) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type SkyeBulkEmbeddingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CandidatesEmbedding []*CandidateEmbedding `protobuf:"bytes,1,rep,name=candidatesEmbedding,proto3" json:"candidatesEmbedding,omitempty"`
}

func (x *SkyeBulkEmbeddingResponse) Reset() {
	*x = SkyeBulkEmbeddingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkyeBulkEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkyeBulkEmbeddingResponse) ProtoMessage() {}

func (x *SkyeBulkEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkyeBulkEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*SkyeBulkEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{10}
}

func (x *SkyeBulkEmbeddingResponse) GetCandidatesEmbedding() []*CandidateEmbedding {
	if x != nil {
		return x.CandidatesEmbedding
	}
	return nil
}

type CandidateEmbedding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Embedding       []float64 `protobuf:"fixed64,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	SearchEmbedding []float64 `protobuf:"fixed64,3,rep,packed,name=searchEmbedding,proto3" json:"searchEmbedding,omitempty"`
}

func (x *CandidateEmbedding) Reset() {
	*x = CandidateEmbedding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandidateEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateEmbedding) ProtoMessage() {}

func (x *CandidateEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateEmbedding.ProtoReflect.Descriptor instead.
func (*CandidateEmbedding) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{11}
}

func (x *CandidateEmbedding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CandidateEmbedding) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *CandidateEmbedding) GetSearchEmbedding() []float64 {
	if x != nil {
		return x.SearchEmbedding
	}
	return nil
}

type CandidateResponse_Candidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta *CandidateResponse_Candidate_Meta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *CandidateResponse_Candidate) Reset() {
	*x = CandidateResponse_Candidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandidateResponse_Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateResponse_Candidate) ProtoMessage() {}

func (x *CandidateResponse_Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateResponse_Candidate.ProtoReflect.Descriptor instead.
func (*CandidateResponse_Candidate) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CandidateResponse_Candidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CandidateResponse_Candidate) GetMeta() *CandidateResponse_Candidate_Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CandidateResponse_Candidate_Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score         float64           `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	AttributesMap map[string]string `protobuf:"bytes,2,rep,name=attributesMap,proto3" json:"attributesMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CandidateResponse_Candidate_Meta) Reset() {
	*x = CandidateResponse_Candidate_Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skye_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandidateResponse_Candidate_Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateResponse_Candidate_Meta) ProtoMessage() {}

func (x *CandidateResponse_Candidate_Meta) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateResponse_Candidate_Meta.ProtoReflect.Descriptor instead.
func (*CandidateResponse_Candidate_Meta) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *CandidateResponse_Candidate_Meta) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CandidateResponse_Candidate_Meta) GetAttributesMap() map[string]string {
	if x != nil {
		return x.AttributesMap
	}
	return nil
}

var File_skye_proto protoreflect.FileDescriptor

var file_skye_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x6b, 0x79, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb5, 0x02, 0x0a,
	0x0b, 0x53, 0x6b, 0x79, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x73, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x0a, 0x65, 0x6d, 0x62, 0x65,
	0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x69, 0x6e, 0x67, 0x73, 0x12, 0x2e, 0x0a, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x22, 0x29, 0x0a, 0x09, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x22,
	0x2a, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xd9, 0x01, 0x0a, 0x06,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x20, 0x0a, 0x02,
	0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x7f, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x49,
	0x4e, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x45, 0x58, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x45, 0x41, 0x52, 0x43, 0x48, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x54, 0x45, 0x10, 0x04,
	0x12, 0x07, 0x0a, 0x03, 0x47, 0x54, 0x45, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x54, 0x57,
	0x45, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x54, 0x57, 0x10, 0x07, 0x12, 0x06, 0x0a, 0x02,
	0x4c, 0x54, 0x10, 0x08, 0x12, 0x06, 0x0a, 0x02, 0x47, 0x54, 0x10, 0x09, 0x12, 0x0f, 0x0a, 0x0b,
	0x4c, 0x41, 0x53, 0x54, 0x5f, 0x58, 0x5f, 0x44, 0x41, 0x59, 0x53, 0x10, 0x0a, 0x12, 0x08, 0x0a,
	0x04, 0x57, 0x54, 0x48, 0x4e, 0x10, 0x0b, 0x22, 0xe3, 0x02, 0x0a, 0x11, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a,
	0x0a, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x0a, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x8f, 0x02, 0x0a, 0x09,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x04, 0x6d, 0x65, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x1a, 0xba, 0x01, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x5a, 0x0a, 0x0d, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x4d, 0x61, 0x70,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x1a, 0x40, 0x0a, 0x12, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x40, 0x0a,
	0x0c, 0x53, 0x6b, 0x79, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a,
	0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22,
	0xae, 0x01, 0x0a, 0x1a, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x44, 0x6f, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x65,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74,
	0x22, 0x51, 0x0a, 0x17, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x62,
	0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0x73, 0x0a, 0x1b, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x44, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x54, 0x0a, 0x18, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x18,
	0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69,
	0x6e, 0x67, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x18, 0x53, 0x6b, 0x79,
	0x65, 0x42, 0x75, 0x6c, 0x6b, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x22, 0x0a,
	0x0c, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x22, 0x62, 0x0a, 0x19, 0x53, 0x6b, 0x79,
	0x65, 0x42, 0x75, 0x6c, 0x6b, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x13, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x13, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x6c, 0x0a,
	0x12, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x6d, 0x62, 0x65, 0x64,
	0x64, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x32, 0x52, 0x0a, 0x1b, 0x53,
	0x6b, 0x79, 0x65, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x14, 0x67, 0x65,
	0x74, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x12, 0x0c, 0x2e, 0x53, 0x6b, 0x79, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0d, 0x2e, 0x53, 0x6b, 0x79, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0xc5, 0x01, 0x0a, 0x14, 0x53, 0x6b, 0x79, 0x65, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x1b, 0x67, 0x65, 0x74, 0x43,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x69, 0x6e, 0x67, 0x44, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x44, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x53, 0x0a, 0x1a, 0x67, 0x65, 0x74, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69,
	0x6e, 0x67, 0x73, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x12, 0x19, 0x2e, 0x53, 0x6b, 0x79, 0x65, 0x42, 0x75, 0x6c, 0x6b, 0x45, 0x6d, 0x62, 0x65, 0x64,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x53, 0x6b,
	0x79, 0x65, 0x42, 0x75, 0x6c, 0x6b, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_skye_proto_rawDescOnce sync.Once
	file_skye_proto_rawDescData = file_skye_proto_rawDesc
)

func file_skye_proto_rawDescGZIP() []byte {
	file_skye_proto_rawDescOnce.Do(func() {
		file_skye_proto_rawDescData = protoimpl.X.CompressGZIP(file_skye_proto_rawDescData)
	})
	return file_skye_proto_rawDescData
}

var file_skye_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_skye_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_skye_proto_goTypes = []any{
	(Filter_Operator)(0),                     // 0: Filter.Operator
	(*SkyeRequest)(nil),                      // 1: SkyeRequest
	(*Embedding)(nil),                        // 2: Embedding
	(*Filters)(nil),                          // 3: Filters
	(*Filter)(nil),                           // 4: Filter
	(*CandidateResponse)(nil),                // 5: CandidateResponse
	(*SkyeResponse)(nil),                     // 6: SkyeResponse
	(*EmbeddingDotProductRequest)(nil),       // 7: EmbeddingDotProductRequest
	(*CandidateEmbeddingScore)(nil),          // 8: CandidateEmbeddingScore
	(*EmbeddingDotProductResponse)(nil),      // 9: EmbeddingDotProductResponse
	(*SkyeBulkEmbeddingRequest)(nil),         // 10: SkyeBulkEmbeddingRequest
	(*SkyeBulkEmbeddingResponse)(nil),        // 11: SkyeBulkEmbeddingResponse
	(*CandidateEmbedding)(nil),               // 12: CandidateEmbedding
	(*CandidateResponse_Candidate)(nil),      // 13: CandidateResponse.Candidate
	(*CandidateResponse_Candidate_Meta)(nil), // 14: CandidateResponse.Candidate.Meta
	nil,                                      // 15: CandidateResponse.Candidate.Meta.AttributesMapEntry
}
var file_skye_proto_depIdxs = []int32{
	3,  // 0: SkyeRequest.filters:type_name -> Filters
	2,  // 1: SkyeRequest.embeddings:type_name -> Embedding
	3,  // 2: SkyeRequest.globalFilters:type_name -> Filters
	4,  // 3: Filters.filter:type_name -> Filter
	0,  // 4: Filter.op:type_name -> Filter.Operator
	13, // 5: CandidateResponse.candidates:type_name -> CandidateResponse.Candidate
	5,  // 6: SkyeResponse.responses:type_name -> CandidateResponse
	8,  // 7: EmbeddingDotProductResponse.candidateEmbeddingScores:type_name -> CandidateEmbeddingScore
	12, // 8: SkyeBulkEmbeddingResponse.candidatesEmbedding:type_name -> CandidateEmbedding
	14, // 9: CandidateResponse.Candidate.meta:type_name -> CandidateResponse.Candidate.Meta
	15, // 10: CandidateResponse.Candidate.Meta.attributesMap:type_name -> CandidateResponse.Candidate.Meta.AttributesMapEntry
	1,  // 11: SkyeSimilarCandidateService.getSimilarCandidates:input_type -> SkyeRequest
	7,  // 12: SkyeEmbeddingService.getCandidateEmbeddingScores:input_type -> EmbeddingDotProductRequest
	10, // 13: SkyeEmbeddingService.getEmbeddingsForCandidates:input_type -> SkyeBulkEmbeddingRequest
	6,  // 14: SkyeSimilarCandidateService.getSimilarCandidates:output_type -> SkyeResponse
	9,  // 15: SkyeEmbeddingService.getCandidateEmbeddingScores:output_type -> EmbeddingDotProductResponse
	11, // 16: SkyeEmbeddingService.getEmbeddingsForCandidates:output_type -> SkyeBulkEmbeddingResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_skye_proto_init() }
func file_skye_proto_init() {
	if File_skye_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_skye_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SkyeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Embedding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Filters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SkyeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*EmbeddingDotProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CandidateEmbeddingScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*EmbeddingDotProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SkyeBulkEmbeddingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SkyeBulkEmbeddingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*CandidateEmbedding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*CandidateResponse_Candidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skye_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CandidateResponse_Candidate_Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_skye_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_skye_proto_goTypes,
		DependencyIndexes: file_skye_proto_depIdxs,
		EnumInfos:         file_skye_proto_enumTypes,
		MessageInfos:      file_skye_proto_msgTypes,
	}.Build()
	File_skye_proto = out.File
	file_skye_proto_rawDesc = nil
	file_skye_proto_goTypes = nil
	file_skye_proto_depIdxs = nil
}
