// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: pkg/proto/time_series.proto

package timeseries

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InteractionStoreTimeSeriesService_PersistClickData_FullMethodName          = "/proto.InteractionStoreTimeSeriesService/PersistClickData"
	InteractionStoreTimeSeriesService_PersistOrderData_FullMethodName          = "/proto.InteractionStoreTimeSeriesService/PersistOrderData"
	InteractionStoreTimeSeriesService_RetrieveClickInteractions_FullMethodName = "/proto.InteractionStoreTimeSeriesService/RetrieveClickInteractions"
	InteractionStoreTimeSeriesService_RetrieveOrderInteractions_FullMethodName = "/proto.InteractionStoreTimeSeriesService/RetrieveOrderInteractions"
	InteractionStoreTimeSeriesService_RetrieveInteractions_FullMethodName      = "/proto.InteractionStoreTimeSeriesService/RetrieveInteractions"
)

// InteractionStoreTimeSeriesServiceClient is the client API for InteractionStoreTimeSeriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InteractionStoreTimeSeriesServiceClient interface {
	PersistClickData(ctx context.Context, in *PersistClickDataRequest, opts ...grpc.CallOption) (*PersistDataResponse, error)
	PersistOrderData(ctx context.Context, in *PersistOrderDataRequest, opts ...grpc.CallOption) (*PersistDataResponse, error)
	RetrieveClickInteractions(ctx context.Context, in *RetrieveDataRequest, opts ...grpc.CallOption) (*RetrieveClickDataResponse, error)
	RetrieveOrderInteractions(ctx context.Context, in *RetrieveDataRequest, opts ...grpc.CallOption) (*RetrieveOrderDataResponse, error)
	RetrieveInteractions(ctx context.Context, in *RetrieveInteractionsRequest, opts ...grpc.CallOption) (*RetrieveInteractionsResponse, error)
}

type interactionStoreTimeSeriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionStoreTimeSeriesServiceClient(cc grpc.ClientConnInterface) InteractionStoreTimeSeriesServiceClient {
	return &interactionStoreTimeSeriesServiceClient{cc}
}

func (c *interactionStoreTimeSeriesServiceClient) PersistClickData(ctx context.Context, in *PersistClickDataRequest, opts ...grpc.CallOption) (*PersistDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersistDataResponse)
	err := c.cc.Invoke(ctx, InteractionStoreTimeSeriesService_PersistClickData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionStoreTimeSeriesServiceClient) PersistOrderData(ctx context.Context, in *PersistOrderDataRequest, opts ...grpc.CallOption) (*PersistDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersistDataResponse)
	err := c.cc.Invoke(ctx, InteractionStoreTimeSeriesService_PersistOrderData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionStoreTimeSeriesServiceClient) RetrieveClickInteractions(ctx context.Context, in *RetrieveDataRequest, opts ...grpc.CallOption) (*RetrieveClickDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveClickDataResponse)
	err := c.cc.Invoke(ctx, InteractionStoreTimeSeriesService_RetrieveClickInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionStoreTimeSeriesServiceClient) RetrieveOrderInteractions(ctx context.Context, in *RetrieveDataRequest, opts ...grpc.CallOption) (*RetrieveOrderDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveOrderDataResponse)
	err := c.cc.Invoke(ctx, InteractionStoreTimeSeriesService_RetrieveOrderInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionStoreTimeSeriesServiceClient) RetrieveInteractions(ctx context.Context, in *RetrieveInteractionsRequest, opts ...grpc.CallOption) (*RetrieveInteractionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveInteractionsResponse)
	err := c.cc.Invoke(ctx, InteractionStoreTimeSeriesService_RetrieveInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionStoreTimeSeriesServiceServer is the server API for InteractionStoreTimeSeriesService service.
// All implementations must embed UnimplementedInteractionStoreTimeSeriesServiceServer
// for forward compatibility.
type InteractionStoreTimeSeriesServiceServer interface {
	PersistClickData(context.Context, *PersistClickDataRequest) (*PersistDataResponse, error)
	PersistOrderData(context.Context, *PersistOrderDataRequest) (*PersistDataResponse, error)
	RetrieveClickInteractions(context.Context, *RetrieveDataRequest) (*RetrieveClickDataResponse, error)
	RetrieveOrderInteractions(context.Context, *RetrieveDataRequest) (*RetrieveOrderDataResponse, error)
	RetrieveInteractions(context.Context, *RetrieveInteractionsRequest) (*RetrieveInteractionsResponse, error)
	mustEmbedUnimplementedInteractionStoreTimeSeriesServiceServer()
}

// UnimplementedInteractionStoreTimeSeriesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionStoreTimeSeriesServiceServer struct{}

func (UnimplementedInteractionStoreTimeSeriesServiceServer) PersistClickData(context.Context, *PersistClickDataRequest) (*PersistDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PersistClickData not implemented")
}
func (UnimplementedInteractionStoreTimeSeriesServiceServer) PersistOrderData(context.Context, *PersistOrderDataRequest) (*PersistDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PersistOrderData not implemented")
}
func (UnimplementedInteractionStoreTimeSeriesServiceServer) RetrieveClickInteractions(context.Context, *RetrieveDataRequest) (*RetrieveClickDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveClickInteractions not implemented")
}
func (UnimplementedInteractionStoreTimeSeriesServiceServer) RetrieveOrderInteractions(context.Context, *RetrieveDataRequest) (*RetrieveOrderDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveOrderInteractions not implemented")
}
func (UnimplementedInteractionStoreTimeSeriesServiceServer) RetrieveInteractions(context.Context, *RetrieveInteractionsRequest) (*RetrieveInteractionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveInteractions not implemented")
}
func (UnimplementedInteractionStoreTimeSeriesServiceServer) mustEmbedUnimplementedInteractionStoreTimeSeriesServiceServer() {
}
func (UnimplementedInteractionStoreTimeSeriesServiceServer) testEmbeddedByValue() {}

// UnsafeInteractionStoreTimeSeriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionStoreTimeSeriesServiceServer will
// result in compilation errors.
type UnsafeInteractionStoreTimeSeriesServiceServer interface {
	mustEmbedUnimplementedInteractionStoreTimeSeriesServiceServer()
}

func RegisterInteractionStoreTimeSeriesServiceServer(s grpc.ServiceRegistrar, srv InteractionStoreTimeSeriesServiceServer) {
	// If the following call panics, it indicates UnimplementedInteractionStoreTimeSeriesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InteractionStoreTimeSeriesService_ServiceDesc, srv)
}

func _InteractionStoreTimeSeriesService_PersistClickData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistClickDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionStoreTimeSeriesServiceServer).PersistClickData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionStoreTimeSeriesService_PersistClickData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionStoreTimeSeriesServiceServer).PersistClickData(ctx, req.(*PersistClickDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionStoreTimeSeriesService_PersistOrderData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistOrderDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionStoreTimeSeriesServiceServer).PersistOrderData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionStoreTimeSeriesService_PersistOrderData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionStoreTimeSeriesServiceServer).PersistOrderData(ctx, req.(*PersistOrderDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionStoreTimeSeriesService_RetrieveClickInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionStoreTimeSeriesServiceServer).RetrieveClickInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionStoreTimeSeriesService_RetrieveClickInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionStoreTimeSeriesServiceServer).RetrieveClickInteractions(ctx, req.(*RetrieveDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionStoreTimeSeriesService_RetrieveOrderInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionStoreTimeSeriesServiceServer).RetrieveOrderInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionStoreTimeSeriesService_RetrieveOrderInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionStoreTimeSeriesServiceServer).RetrieveOrderInteractions(ctx, req.(*RetrieveDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InteractionStoreTimeSeriesService_RetrieveInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveInteractionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionStoreTimeSeriesServiceServer).RetrieveInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InteractionStoreTimeSeriesService_RetrieveInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionStoreTimeSeriesServiceServer).RetrieveInteractions(ctx, req.(*RetrieveInteractionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InteractionStoreTimeSeriesService_ServiceDesc is the grpc.ServiceDesc for InteractionStoreTimeSeriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InteractionStoreTimeSeriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.InteractionStoreTimeSeriesService",
	HandlerType: (*InteractionStoreTimeSeriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PersistClickData",
			Handler:    _InteractionStoreTimeSeriesService_PersistClickData_Handler,
		},
		{
			MethodName: "PersistOrderData",
			Handler:    _InteractionStoreTimeSeriesService_PersistOrderData_Handler,
		},
		{
			MethodName: "RetrieveClickInteractions",
			Handler:    _InteractionStoreTimeSeriesService_RetrieveClickInteractions_Handler,
		},
		{
			MethodName: "RetrieveOrderInteractions",
			Handler:    _InteractionStoreTimeSeriesService_RetrieveOrderInteractions_Handler,
		},
		{
			MethodName: "RetrieveInteractions",
			Handler:    _InteractionStoreTimeSeriesService_RetrieveInteractions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/time_series.proto",
}
