// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: pkg/proto/time_series.proto

package timeseries

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimeSeriesService_PersistClickData_FullMethodName          = "/proto.TimeSeriesService/PersistClickData"
	TimeSeriesService_PersistOrderData_FullMethodName          = "/proto.TimeSeriesService/PersistOrderData"
	TimeSeriesService_RetrieveClickInteractions_FullMethodName = "/proto.TimeSeriesService/RetrieveClickInteractions"
	TimeSeriesService_RetrieveOrderInteractions_FullMethodName = "/proto.TimeSeriesService/RetrieveOrderInteractions"
	TimeSeriesService_RetrieveInteractions_FullMethodName      = "/proto.TimeSeriesService/RetrieveInteractions"
)

// TimeSeriesServiceClient is the client API for TimeSeriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimeSeriesServiceClient interface {
	PersistClickData(ctx context.Context, in *PersistClickDataRequest, opts ...grpc.CallOption) (*PersistDataResponse, error)
	PersistOrderData(ctx context.Context, in *PersistOrderDataRequest, opts ...grpc.CallOption) (*PersistDataResponse, error)
	RetrieveClickInteractions(ctx context.Context, in *RetrieveDataRequest, opts ...grpc.CallOption) (*RetrieveClickDataResponse, error)
	RetrieveOrderInteractions(ctx context.Context, in *RetrieveDataRequest, opts ...grpc.CallOption) (*RetrieveOrderDataResponse, error)
	RetrieveInteractions(ctx context.Context, in *RetrieveInteractionsRequest, opts ...grpc.CallOption) (*RetrieveInteractionsResponse, error)
}

type timeSeriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeSeriesServiceClient(cc grpc.ClientConnInterface) TimeSeriesServiceClient {
	return &timeSeriesServiceClient{cc}
}

func (c *timeSeriesServiceClient) PersistClickData(ctx context.Context, in *PersistClickDataRequest, opts ...grpc.CallOption) (*PersistDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersistDataResponse)
	err := c.cc.Invoke(ctx, TimeSeriesService_PersistClickData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSeriesServiceClient) PersistOrderData(ctx context.Context, in *PersistOrderDataRequest, opts ...grpc.CallOption) (*PersistDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersistDataResponse)
	err := c.cc.Invoke(ctx, TimeSeriesService_PersistOrderData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSeriesServiceClient) RetrieveClickInteractions(ctx context.Context, in *RetrieveDataRequest, opts ...grpc.CallOption) (*RetrieveClickDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveClickDataResponse)
	err := c.cc.Invoke(ctx, TimeSeriesService_RetrieveClickInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSeriesServiceClient) RetrieveOrderInteractions(ctx context.Context, in *RetrieveDataRequest, opts ...grpc.CallOption) (*RetrieveOrderDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveOrderDataResponse)
	err := c.cc.Invoke(ctx, TimeSeriesService_RetrieveOrderInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeSeriesServiceClient) RetrieveInteractions(ctx context.Context, in *RetrieveInteractionsRequest, opts ...grpc.CallOption) (*RetrieveInteractionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveInteractionsResponse)
	err := c.cc.Invoke(ctx, TimeSeriesService_RetrieveInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeSeriesServiceServer is the server API for TimeSeriesService service.
// All implementations must embed UnimplementedTimeSeriesServiceServer
// for forward compatibility.
type TimeSeriesServiceServer interface {
	PersistClickData(context.Context, *PersistClickDataRequest) (*PersistDataResponse, error)
	PersistOrderData(context.Context, *PersistOrderDataRequest) (*PersistDataResponse, error)
	RetrieveClickInteractions(context.Context, *RetrieveDataRequest) (*RetrieveClickDataResponse, error)
	RetrieveOrderInteractions(context.Context, *RetrieveDataRequest) (*RetrieveOrderDataResponse, error)
	RetrieveInteractions(context.Context, *RetrieveInteractionsRequest) (*RetrieveInteractionsResponse, error)
	mustEmbedUnimplementedTimeSeriesServiceServer()
}

// UnimplementedTimeSeriesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimeSeriesServiceServer struct{}

func (UnimplementedTimeSeriesServiceServer) PersistClickData(context.Context, *PersistClickDataRequest) (*PersistDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PersistClickData not implemented")
}
func (UnimplementedTimeSeriesServiceServer) PersistOrderData(context.Context, *PersistOrderDataRequest) (*PersistDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PersistOrderData not implemented")
}
func (UnimplementedTimeSeriesServiceServer) RetrieveClickInteractions(context.Context, *RetrieveDataRequest) (*RetrieveClickDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveClickInteractions not implemented")
}
func (UnimplementedTimeSeriesServiceServer) RetrieveOrderInteractions(context.Context, *RetrieveDataRequest) (*RetrieveOrderDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveOrderInteractions not implemented")
}
func (UnimplementedTimeSeriesServiceServer) RetrieveInteractions(context.Context, *RetrieveInteractionsRequest) (*RetrieveInteractionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveInteractions not implemented")
}
func (UnimplementedTimeSeriesServiceServer) mustEmbedUnimplementedTimeSeriesServiceServer() {}
func (UnimplementedTimeSeriesServiceServer) testEmbeddedByValue()                           {}

// UnsafeTimeSeriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeSeriesServiceServer will
// result in compilation errors.
type UnsafeTimeSeriesServiceServer interface {
	mustEmbedUnimplementedTimeSeriesServiceServer()
}

func RegisterTimeSeriesServiceServer(s grpc.ServiceRegistrar, srv TimeSeriesServiceServer) {
	// If the following call panics, it indicates UnimplementedTimeSeriesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimeSeriesService_ServiceDesc, srv)
}

func _TimeSeriesService_PersistClickData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistClickDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServiceServer).PersistClickData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeSeriesService_PersistClickData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServiceServer).PersistClickData(ctx, req.(*PersistClickDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSeriesService_PersistOrderData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistOrderDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServiceServer).PersistOrderData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeSeriesService_PersistOrderData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServiceServer).PersistOrderData(ctx, req.(*PersistOrderDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSeriesService_RetrieveClickInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServiceServer).RetrieveClickInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeSeriesService_RetrieveClickInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServiceServer).RetrieveClickInteractions(ctx, req.(*RetrieveDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSeriesService_RetrieveOrderInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServiceServer).RetrieveOrderInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeSeriesService_RetrieveOrderInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServiceServer).RetrieveOrderInteractions(ctx, req.(*RetrieveDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeSeriesService_RetrieveInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveInteractionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServiceServer).RetrieveInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeSeriesService_RetrieveInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServiceServer).RetrieveInteractions(ctx, req.(*RetrieveInteractionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimeSeriesService_ServiceDesc is the grpc.ServiceDesc for TimeSeriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeSeriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TimeSeriesService",
	HandlerType: (*TimeSeriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PersistClickData",
			Handler:    _TimeSeriesService_PersistClickData_Handler,
		},
		{
			MethodName: "PersistOrderData",
			Handler:    _TimeSeriesService_PersistOrderData_Handler,
		},
		{
			MethodName: "RetrieveClickInteractions",
			Handler:    _TimeSeriesService_RetrieveClickInteractions_Handler,
		},
		{
			MethodName: "RetrieveOrderInteractions",
			Handler:    _TimeSeriesService_RetrieveOrderInteractions_Handler,
		},
		{
			MethodName: "RetrieveInteractions",
			Handler:    _TimeSeriesService_RetrieveInteractions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/time_series.proto",
}
