{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "online-feature-store.fullname" . }}-gateway
  namespace: {{ .Values.gateway.namespace | quote }}
  labels:
    {{- include "online-feature-store.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: {{ range .Values.gateway.hosts }}"{{ . }}"{{ end }}
    {{- if not .Values.gateway.tls.enabled }}
    allowedRoutes:
      namespaces:
        from: Same
    {{- end }}
  {{- if .Values.gateway.tls.enabled }}
  - name: https
    port: 443
    protocol: HTTPS
    hostname: {{ range .Values.gateway.hosts }}"{{ . }}"{{ end }}
    tls:
      mode: Terminate
      certificateRefs:
      {{- range .Values.gateway.tls.certificateRefs }}
      - name: {{ .name }}
        namespace: {{ .namespace }}
      {{- end }}
    allowedRoutes:
      namespaces:
        from: Same
  {{- end }}
{{- end }}
