{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "online-feature-store.networkPolicyName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "online-feature-store.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "online-feature-store.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
  {{- toYaml .Values.networkPolicy.ingress | nindent 2 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
  {{- toYaml .Values.networkPolicy.egress | nindent 2 }}
  {{- end }}
{{- end }}
