apiVersion: v1
kind: Service
metadata:
  name: {{ include "online-feature-store.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "online-feature-store.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    {{- include "online-feature-store.selectorLabels" . | nindent 4 }}
