// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: skye.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter_Operator int32

const (
	Filter_IN          Filter_Operator = 0
	Filter_NIN         Filter_Operator = 1
	Filter_EX          Filter_Operator = 2
	Filter_SEARCH      Filter_Operator = 3
	Filter_LTE         Filter_Operator = 4
	Filter_GTE         Filter_Operator = 5
	Filter_BTWE        Filter_Operator = 6
	Filter_BTW         Filter_Operator = 7
	Filter_LT          Filter_Operator = 8
	Filter_GT          Filter_Operator = 9
	Filter_LAST_X_DAYS Filter_Operator = 10
	Filter_WTHN        Filter_Operator = 11
)

// Enum value maps for Filter_Operator.
var (
	Filter_Operator_name = map[int32]string{
		0:  "IN",
		1:  "NIN",
		2:  "EX",
		3:  "SEARCH",
		4:  "LTE",
		5:  "GTE",
		6:  "BTWE",
		7:  "BTW",
		8:  "LT",
		9:  "GT",
		10: "LAST_X_DAYS",
		11: "WTHN",
	}
	Filter_Operator_value = map[string]int32{
		"IN":          0,
		"NIN":         1,
		"EX":          2,
		"SEARCH":      3,
		"LTE":         4,
		"GTE":         5,
		"BTWE":        6,
		"BTW":         7,
		"LT":          8,
		"GT":          9,
		"LAST_X_DAYS": 10,
		"WTHN":        11,
	}
)

func (x Filter_Operator) Enum() *Filter_Operator {
	p := new(Filter_Operator)
	*p = x
	return p
}

func (x Filter_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Filter_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_skye_proto_enumTypes[0].Descriptor()
}

func (Filter_Operator) Type() protoreflect.EnumType {
	return &file_skye_proto_enumTypes[0]
}

func (x Filter_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Filter_Operator.Descriptor instead.
func (Filter_Operator) EnumDescriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{3, 0}
}

type SkyeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	CandidateIds  []string               `protobuf:"bytes,2,rep,name=candidateIds,proto3" json:"candidateIds,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	ModelName     string                 `protobuf:"bytes,4,opt,name=modelName,proto3" json:"modelName,omitempty"`
	Variant       string                 `protobuf:"bytes,5,opt,name=variant,proto3" json:"variant,omitempty"`
	Filters       []*Filters             `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty"`
	Attribute     []string               `protobuf:"bytes,7,rep,name=attribute,proto3" json:"attribute,omitempty"`
	Embeddings    []*Embedding           `protobuf:"bytes,8,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	GlobalFilters *Filters               `protobuf:"bytes,9,opt,name=globalFilters,proto3" json:"globalFilters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkyeRequest) Reset() {
	*x = SkyeRequest{}
	mi := &file_skye_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkyeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkyeRequest) ProtoMessage() {}

func (x *SkyeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkyeRequest.ProtoReflect.Descriptor instead.
func (*SkyeRequest) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{0}
}

func (x *SkyeRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *SkyeRequest) GetCandidateIds() []string {
	if x != nil {
		return x.CandidateIds
	}
	return nil
}

func (x *SkyeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SkyeRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *SkyeRequest) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *SkyeRequest) GetFilters() []*Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SkyeRequest) GetAttribute() []string {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *SkyeRequest) GetEmbeddings() []*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *SkyeRequest) GetGlobalFilters() *Filters {
	if x != nil {
		return x.GlobalFilters
	}
	return nil
}

type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float64              `protobuf:"fixed64,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_skye_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{1}
}

func (x *Embedding) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type Filters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        []*Filter              `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_skye_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{2}
}

func (x *Filters) GetFilter() []*Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Op            Filter_Operator        `protobuf:"varint,2,opt,name=op,proto3,enum=Filter_Operator" json:"op,omitempty"`
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_skye_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{3}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetOp() Filter_Operator {
	if x != nil {
		return x.Op
	}
	return Filter_IN
}

func (x *Filter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type CandidateResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Candidates    []*CandidateResponse_Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateResponse) Reset() {
	*x = CandidateResponse{}
	mi := &file_skye_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateResponse) ProtoMessage() {}

func (x *CandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateResponse.ProtoReflect.Descriptor instead.
func (*CandidateResponse) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{4}
}

func (x *CandidateResponse) GetCandidates() []*CandidateResponse_Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type SkyeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*CandidateResponse   `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkyeResponse) Reset() {
	*x = SkyeResponse{}
	mi := &file_skye_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkyeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkyeResponse) ProtoMessage() {}

func (x *SkyeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkyeResponse.ProtoReflect.Descriptor instead.
func (*SkyeResponse) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{5}
}

func (x *SkyeResponse) GetResponses() []*CandidateResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type EmbeddingDotProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	CandidateIds  []string               `protobuf:"bytes,2,rep,name=candidateIds,proto3" json:"candidateIds,omitempty"`
	Embedding     []float64              `protobuf:"fixed64,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	ModelName     string                 `protobuf:"bytes,4,opt,name=modelName,proto3" json:"modelName,omitempty"`
	Variant       string                 `protobuf:"bytes,5,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingDotProductRequest) Reset() {
	*x = EmbeddingDotProductRequest{}
	mi := &file_skye_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingDotProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingDotProductRequest) ProtoMessage() {}

func (x *EmbeddingDotProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingDotProductRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingDotProductRequest) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{6}
}

func (x *EmbeddingDotProductRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *EmbeddingDotProductRequest) GetCandidateIds() []string {
	if x != nil {
		return x.CandidateIds
	}
	return nil
}

func (x *EmbeddingDotProductRequest) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbeddingDotProductRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *EmbeddingDotProductRequest) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type CandidateEmbeddingScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateEmbeddingScore) Reset() {
	*x = CandidateEmbeddingScore{}
	mi := &file_skye_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateEmbeddingScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateEmbeddingScore) ProtoMessage() {}

func (x *CandidateEmbeddingScore) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateEmbeddingScore.ProtoReflect.Descriptor instead.
func (*CandidateEmbeddingScore) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{7}
}

func (x *CandidateEmbeddingScore) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *CandidateEmbeddingScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type EmbeddingDotProductResponse struct {
	state                    protoimpl.MessageState     `protogen:"open.v1"`
	CandidateEmbeddingScores []*CandidateEmbeddingScore `protobuf:"bytes,1,rep,name=candidateEmbeddingScores,proto3" json:"candidateEmbeddingScores,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EmbeddingDotProductResponse) Reset() {
	*x = EmbeddingDotProductResponse{}
	mi := &file_skye_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingDotProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingDotProductResponse) ProtoMessage() {}

func (x *EmbeddingDotProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingDotProductResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingDotProductResponse) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{8}
}

func (x *EmbeddingDotProductResponse) GetCandidateEmbeddingScores() []*CandidateEmbeddingScore {
	if x != nil {
		return x.CandidateEmbeddingScores
	}
	return nil
}

type SkyeBulkEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	CandidateIds  []string               `protobuf:"bytes,2,rep,name=candidateIds,proto3" json:"candidateIds,omitempty"`
	ModelName     string                 `protobuf:"bytes,4,opt,name=modelName,proto3" json:"modelName,omitempty"`
	Variant       string                 `protobuf:"bytes,5,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkyeBulkEmbeddingRequest) Reset() {
	*x = SkyeBulkEmbeddingRequest{}
	mi := &file_skye_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkyeBulkEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkyeBulkEmbeddingRequest) ProtoMessage() {}

func (x *SkyeBulkEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkyeBulkEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*SkyeBulkEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{9}
}

func (x *SkyeBulkEmbeddingRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *SkyeBulkEmbeddingRequest) GetCandidateIds() []string {
	if x != nil {
		return x.CandidateIds
	}
	return nil
}

func (x *SkyeBulkEmbeddingRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *SkyeBulkEmbeddingRequest) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type SkyeBulkEmbeddingResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CandidatesEmbedding []*CandidateEmbedding  `protobuf:"bytes,1,rep,name=candidatesEmbedding,proto3" json:"candidatesEmbedding,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SkyeBulkEmbeddingResponse) Reset() {
	*x = SkyeBulkEmbeddingResponse{}
	mi := &file_skye_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkyeBulkEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkyeBulkEmbeddingResponse) ProtoMessage() {}

func (x *SkyeBulkEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkyeBulkEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*SkyeBulkEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{10}
}

func (x *SkyeBulkEmbeddingResponse) GetCandidatesEmbedding() []*CandidateEmbedding {
	if x != nil {
		return x.CandidatesEmbedding
	}
	return nil
}

type CandidateEmbedding struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Embedding       []float64              `protobuf:"fixed64,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	SearchEmbedding []float64              `protobuf:"fixed64,3,rep,packed,name=searchEmbedding,proto3" json:"searchEmbedding,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CandidateEmbedding) Reset() {
	*x = CandidateEmbedding{}
	mi := &file_skye_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateEmbedding) ProtoMessage() {}

func (x *CandidateEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateEmbedding.ProtoReflect.Descriptor instead.
func (*CandidateEmbedding) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{11}
}

func (x *CandidateEmbedding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CandidateEmbedding) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *CandidateEmbedding) GetSearchEmbedding() []float64 {
	if x != nil {
		return x.SearchEmbedding
	}
	return nil
}

type CandidateResponse_Candidate struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Id            string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta          *CandidateResponse_Candidate_Meta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateResponse_Candidate) Reset() {
	*x = CandidateResponse_Candidate{}
	mi := &file_skye_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateResponse_Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateResponse_Candidate) ProtoMessage() {}

func (x *CandidateResponse_Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateResponse_Candidate.ProtoReflect.Descriptor instead.
func (*CandidateResponse_Candidate) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CandidateResponse_Candidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CandidateResponse_Candidate) GetMeta() *CandidateResponse_Candidate_Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CandidateResponse_Candidate_Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	AttributesMap map[string]string      `protobuf:"bytes,2,rep,name=attributesMap,proto3" json:"attributesMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateResponse_Candidate_Meta) Reset() {
	*x = CandidateResponse_Candidate_Meta{}
	mi := &file_skye_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateResponse_Candidate_Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateResponse_Candidate_Meta) ProtoMessage() {}

func (x *CandidateResponse_Candidate_Meta) ProtoReflect() protoreflect.Message {
	mi := &file_skye_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateResponse_Candidate_Meta.ProtoReflect.Descriptor instead.
func (*CandidateResponse_Candidate_Meta) Descriptor() ([]byte, []int) {
	return file_skye_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *CandidateResponse_Candidate_Meta) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CandidateResponse_Candidate_Meta) GetAttributesMap() map[string]string {
	if x != nil {
		return x.AttributesMap
	}
	return nil
}

var File_skye_proto protoreflect.FileDescriptor

const file_skye_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"skye.proto\"\xb5\x02\n" +
	"\vSkyeRequest\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\"\n" +
	"\fcandidateIds\x18\x02 \x03(\tR\fcandidateIds\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1c\n" +
	"\tmodelName\x18\x04 \x01(\tR\tmodelName\x12\x18\n" +
	"\avariant\x18\x05 \x01(\tR\avariant\x12\"\n" +
	"\afilters\x18\x06 \x03(\v2\b.FiltersR\afilters\x12\x1c\n" +
	"\tattribute\x18\a \x03(\tR\tattribute\x12*\n" +
	"\n" +
	"embeddings\x18\b \x03(\v2\n" +
	".EmbeddingR\n" +
	"embeddings\x12.\n" +
	"\rglobalFilters\x18\t \x01(\v2\b.FiltersR\rglobalFilters\")\n" +
	"\tEmbedding\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x01R\tembedding\"*\n" +
	"\aFilters\x12\x1f\n" +
	"\x06filter\x18\x01 \x03(\v2\a.FilterR\x06filter\"\xd9\x01\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12 \n" +
	"\x02op\x18\x02 \x01(\x0e2\x10.Filter.OperatorR\x02op\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"\x7f\n" +
	"\bOperator\x12\x06\n" +
	"\x02IN\x10\x00\x12\a\n" +
	"\x03NIN\x10\x01\x12\x06\n" +
	"\x02EX\x10\x02\x12\n" +
	"\n" +
	"\x06SEARCH\x10\x03\x12\a\n" +
	"\x03LTE\x10\x04\x12\a\n" +
	"\x03GTE\x10\x05\x12\b\n" +
	"\x04BTWE\x10\x06\x12\a\n" +
	"\x03BTW\x10\a\x12\x06\n" +
	"\x02LT\x10\b\x12\x06\n" +
	"\x02GT\x10\t\x12\x0f\n" +
	"\vLAST_X_DAYS\x10\n" +
	"\x12\b\n" +
	"\x04WTHN\x10\v\"\xe3\x02\n" +
	"\x11CandidateResponse\x12<\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x1c.CandidateResponse.CandidateR\n" +
	"candidates\x1a\x8f\x02\n" +
	"\tCandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x04meta\x18\x02 \x01(\v2!.CandidateResponse.Candidate.MetaR\x04meta\x1a\xba\x01\n" +
	"\x04Meta\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12Z\n" +
	"\rattributesMap\x18\x02 \x03(\v24.CandidateResponse.Candidate.Meta.AttributesMapEntryR\rattributesMap\x1a@\n" +
	"\x12AttributesMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\fSkyeResponse\x120\n" +
	"\tresponses\x18\x01 \x03(\v2\x12.CandidateResponseR\tresponses\"\xae\x01\n" +
	"\x1aEmbeddingDotProductRequest\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\"\n" +
	"\fcandidateIds\x18\x02 \x03(\tR\fcandidateIds\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x01R\tembedding\x12\x1c\n" +
	"\tmodelName\x18\x04 \x01(\tR\tmodelName\x12\x18\n" +
	"\avariant\x18\x05 \x01(\tR\avariant\"Q\n" +
	"\x17CandidateEmbeddingScore\x12 \n" +
	"\vcandidateId\x18\x01 \x01(\tR\vcandidateId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"s\n" +
	"\x1bEmbeddingDotProductResponse\x12T\n" +
	"\x18candidateEmbeddingScores\x18\x01 \x03(\v2\x18.CandidateEmbeddingScoreR\x18candidateEmbeddingScores\"\x8e\x01\n" +
	"\x18SkyeBulkEmbeddingRequest\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\"\n" +
	"\fcandidateIds\x18\x02 \x03(\tR\fcandidateIds\x12\x1c\n" +
	"\tmodelName\x18\x04 \x01(\tR\tmodelName\x12\x18\n" +
	"\avariant\x18\x05 \x01(\tR\avariant\"b\n" +
	"\x19SkyeBulkEmbeddingResponse\x12E\n" +
	"\x13candidatesEmbedding\x18\x01 \x03(\v2\x13.CandidateEmbeddingR\x13candidatesEmbedding\"l\n" +
	"\x12CandidateEmbedding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x01R\tembedding\x12(\n" +
	"\x0fsearchEmbedding\x18\x03 \x03(\x01R\x0fsearchEmbedding2R\n" +
	"\x1bSkyeSimilarCandidateService\x123\n" +
	"\x14getSimilarCandidates\x12\f.SkyeRequest\x1a\r.SkyeResponse2\xc5\x01\n" +
	"\x14SkyeEmbeddingService\x12X\n" +
	"\x1bgetCandidateEmbeddingScores\x12\x1b.EmbeddingDotProductRequest\x1a\x1c.EmbeddingDotProductResponse\x12S\n" +
	"\x1agetEmbeddingsForCandidates\x12\x19.SkyeBulkEmbeddingRequest\x1a\x1a.SkyeBulkEmbeddingResponseB\tZ\a../grpcb\x06proto3"

var (
	file_skye_proto_rawDescOnce sync.Once
	file_skye_proto_rawDescData []byte
)

func file_skye_proto_rawDescGZIP() []byte {
	file_skye_proto_rawDescOnce.Do(func() {
		file_skye_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skye_proto_rawDesc), len(file_skye_proto_rawDesc)))
	})
	return file_skye_proto_rawDescData
}

var file_skye_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_skye_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_skye_proto_goTypes = []any{
	(Filter_Operator)(0),                     // 0: Filter.Operator
	(*SkyeRequest)(nil),                      // 1: SkyeRequest
	(*Embedding)(nil),                        // 2: Embedding
	(*Filters)(nil),                          // 3: Filters
	(*Filter)(nil),                           // 4: Filter
	(*CandidateResponse)(nil),                // 5: CandidateResponse
	(*SkyeResponse)(nil),                     // 6: SkyeResponse
	(*EmbeddingDotProductRequest)(nil),       // 7: EmbeddingDotProductRequest
	(*CandidateEmbeddingScore)(nil),          // 8: CandidateEmbeddingScore
	(*EmbeddingDotProductResponse)(nil),      // 9: EmbeddingDotProductResponse
	(*SkyeBulkEmbeddingRequest)(nil),         // 10: SkyeBulkEmbeddingRequest
	(*SkyeBulkEmbeddingResponse)(nil),        // 11: SkyeBulkEmbeddingResponse
	(*CandidateEmbedding)(nil),               // 12: CandidateEmbedding
	(*CandidateResponse_Candidate)(nil),      // 13: CandidateResponse.Candidate
	(*CandidateResponse_Candidate_Meta)(nil), // 14: CandidateResponse.Candidate.Meta
	nil,                                      // 15: CandidateResponse.Candidate.Meta.AttributesMapEntry
}
var file_skye_proto_depIdxs = []int32{
	3,  // 0: SkyeRequest.filters:type_name -> Filters
	2,  // 1: SkyeRequest.embeddings:type_name -> Embedding
	3,  // 2: SkyeRequest.globalFilters:type_name -> Filters
	4,  // 3: Filters.filter:type_name -> Filter
	0,  // 4: Filter.op:type_name -> Filter.Operator
	13, // 5: CandidateResponse.candidates:type_name -> CandidateResponse.Candidate
	5,  // 6: SkyeResponse.responses:type_name -> CandidateResponse
	8,  // 7: EmbeddingDotProductResponse.candidateEmbeddingScores:type_name -> CandidateEmbeddingScore
	12, // 8: SkyeBulkEmbeddingResponse.candidatesEmbedding:type_name -> CandidateEmbedding
	14, // 9: CandidateResponse.Candidate.meta:type_name -> CandidateResponse.Candidate.Meta
	15, // 10: CandidateResponse.Candidate.Meta.attributesMap:type_name -> CandidateResponse.Candidate.Meta.AttributesMapEntry
	1,  // 11: SkyeSimilarCandidateService.getSimilarCandidates:input_type -> SkyeRequest
	7,  // 12: SkyeEmbeddingService.getCandidateEmbeddingScores:input_type -> EmbeddingDotProductRequest
	10, // 13: SkyeEmbeddingService.getEmbeddingsForCandidates:input_type -> SkyeBulkEmbeddingRequest
	6,  // 14: SkyeSimilarCandidateService.getSimilarCandidates:output_type -> SkyeResponse
	9,  // 15: SkyeEmbeddingService.getCandidateEmbeddingScores:output_type -> EmbeddingDotProductResponse
	11, // 16: SkyeEmbeddingService.getEmbeddingsForCandidates:output_type -> SkyeBulkEmbeddingResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_skye_proto_init() }
func file_skye_proto_init() {
	if File_skye_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skye_proto_rawDesc), len(file_skye_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_skye_proto_goTypes,
		DependencyIndexes: file_skye_proto_depIdxs,
		EnumInfos:         file_skye_proto_enumTypes,
		MessageInfos:      file_skye_proto_msgTypes,
	}.Build()
	File_skye_proto = out.File
	file_skye_proto_goTypes = nil
	file_skye_proto_depIdxs = nil
}
