version: '3.8'

services:
  scylla:
    image: scylladb/scylla:6.2
    container_name: scylla
    ports:
      - "9042:9042"
    volumes:
      - scylla-data:/var/lib/scylla
    command: --smp 1 --memory 512M
    networks:
      - onfs-network

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - onfs-network  

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", ""]
    networks:
      - onfs-network

  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - onfs-network

  etcd-workbench:
    image: tzfun/etcd-workbench:latest
    container_name: etcd-workbench
    ports:
      - "8081:8002"
    networks:
      - onfs-network

volumes:
  scylla-data:
  mysql-data:
networks:
  onfs-network:
    name: onfs-network
