{
 "title": "Online Feature Store",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "online-feature-store-api, online-feature-store-api-experiment,online-feature-store-api-secondary"
   },
   {
    "name": "consumer_service",
    "query": "online-feature-store-consumer-realtime,\nonline-feature-store-consumer,\nonline-feature-store-consumer-v2,\nonline-feature-store-consumer-v3,\nonline-feature-store-consumer-v4"
   }
  ]
 },
 "panels": [
  {
   "title": "Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "OK Call %age",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_requests_total_value{api!=\"/health/self\",service=\"${service}\",status=\"OK\"}))*100/sum(rate(grpc_server_requests_total_value{api!=\"/health/self\",service=\"${service}\"}))",
       "legendFormat": "OK Call %age"
      }
     ]
    },
    {
     "title": "Per Caller OK Call %age",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_requests_total_value{api!=\"/health/self\",service=\"${service}\",status=\"OK\"})) by (caller_id) *100/sum(rate(grpc_server_requests_total_value{api!=\"/health/self\",service=\"${service}\"})) by (caller_id)",
       "legendFormat": "{{caller_id}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_requests_total_value{api!=\"/health/self\",service=\"${service}\"})) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "QPS per pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_requests_total_value{api!=\"/health/self\",service=\"${service}\"})) by (kubernetes_pod_name)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "QPS Per Caller",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_requests_total_value{api!=\"/health/self\",service=\"${service}\"})) by (caller_id)",
       "legendFormat": "{{caller_id}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "avg by (method, status) (\n  avg_over_time(grpc_server_request_latency_99_9_percentile{service=\"${service}\", method=\"/retrieve.FeatureService/RetrieveDecodedResult\"}[5m])\n)",
       "legendFormat": "P99.9 - {{method}} - {{status}}"
      },
      {
       "expr": "avg by (method, status) (\n  avg_over_time(grpc_server_request_latency_99_percentile{service=\"${service}\", method=\"/retrieve.FeatureService/RetrieveDecodedResult\"}[5m])\n)",
       "legendFormat": "P99 - {{method}} - {{status}}"
      },
      {
       "expr": "avg by (method, status) (\n  avg_over_time(grpc_server_request_latency_50_percentile{service=\"${service}\", method=\"/retrieve.FeatureService/RetrieveDecodedResult\"}[5m])\n)",
       "legendFormat": "p50 - {{method}} - {{status}}"
      }
     ]
    },
    {
     "title": "P99 Latency Per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "avg by (api, status,kubernetes_pod_name) (grpc_server_request_latency_99_percentile{service=\"${service}\",status=\"OK\"})",
       "legendFormat": "P99 -- {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Overall Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "avg by (entity) (orchestrator_retrieve_latency_99_9_percentile{service=\"${service}\"})",
       "legendFormat": "P99.9 :: {{entity}}"
      },
      {
       "expr": "avg by (entity) (orchestrator_retrieve_latency_99_percentile{service=\"${service}\"})",
       "legendFormat": "P99 :: {{entity}}"
      }
     ]
    }
   ]
  },
  { "title": "In Memory Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Overall Hit Rate (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(in_memory_cache_hit_rate_value{service=\"${service}\"})*100",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Hit rate per entity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(feature_retrieve_cache_hit_value{service=\"${service}\", cache_type=\"in_memory\"})) by (entity_name) * 100/ (sum(rate(feature_retrieve_cache_hit_value{service=\"${service}\", cache_type=\"in_memory\"})) by (entity_name) + sum(rate(feature_retrieve_cache_miss_value{service=\"${service}\", cache_type=\"in_memory\"})) by (entity_name) )",
     "legendFormat": "{{entity_name}}"
    }
   ]
  },
  {
   "title": "In Memory Keys Count per entity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(feature_retrieve_cache_hit_value{service=\"${service}\", cache_type=\"in_memory\"})) by (entity_name) + \nsum(rate(feature_retrieve_cache_miss_value{service=\"${service}\", cache_type=\"in_memory\"})) by (entity_name)",
     "legendFormat": "{{entity_name}}"
    },
    {
     "expr": "sum(rate(feature_retrieve_cache_hit_value{service=\"${service}\", cache_type=\"in_memory\"})) + \nsum(rate(feature_retrieve_cache_miss_value{service=\"${service}\", cache_type=\"in_memory\"}))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Total Item Count (in Millions)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(in_memory_cache_item_count_value{service=\"${service}\"}) /1000000",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Total Expired Keys Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg(in_memory_cache_expiry_count_value{service=\"${service}\"})",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Total Evicted Keys Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "avg(in_memory_cache_evacuate_count_value{service=\"${service}\"})",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Dragonfly/Redis Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dragonfly hit rate",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(feature_retrieve_cache_hit_value{service=\"${service}\", cache_type=\"distributed\"})) by () * 100/ (sum(rate(feature_retrieve_cache_hit_value{service=\"${service}\", cache_type=\"distributed\"})) by () + sum(rate(feature_retrieve_cache_miss_value{service=\"${service}\", cache_type=\"distributed\"})) by () )",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Dragonfly hit rate per entity",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "sum(rate(feature_retrieve_cache_hit_value{service=\"${service}\", cache_type=\"distributed\"})) by (entity_name) * 100/ (sum(rate(feature_retrieve_cache_hit_value{service=\"${service}\", cache_type=\"distributed\"})) by (entity_name) + sum(rate(feature_retrieve_cache_miss_value{service=\"${service}\", cache_type=\"distributed\"})) by (entity_name) )",
       "legendFormat": "dragonfly -- {{entity_name}}"
      }
     ]
    },
    {
     "title": "Dragonfly RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(rate(feature_retrieve_cache_hit_value{service=\"${service}\", cache_type=\"distributed\"})) by (entity_name) + \nsum(rate(feature_retrieve_cache_miss_value{service=\"${service}\", cache_type=\"distributed\"})) by (entity_name)",
       "legendFormat": "{{entity_name}}"
      },
      {
       "expr": "sum(rate(feature_retrieve_cache_hit_value{service=\"${service}\", cache_type=\"distributed\"}))+ \nsum(rate(feature_retrieve_cache_miss_value{service=\"${service}\", cache_type=\"distributed\"}))",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Dragonfly latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "avg by (entity_name) (feature_retrieve_cache_latency_99_percentile{service=\"${service}\"})",
       "legendFormat": "{{entity_name}}"
      },
      {
       "expr": "avg (feature_retrieve_cache_latency_99_percentile{service=\"${service}\"})",
       "legendFormat": "TOTAL"
      }
     ]
    }
   ]
  },
  {
   "title": "Scylla",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Repository Query Count",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(db_retrieve_count_value{service=\"${service}\"}))",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Repository Query Count per entity",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "sum(rate(db_retrieve_count_value{service=\"${service}\"}))",
       "legendFormat": "TOTAL"
      },
      {
       "expr": "sum(rate(db_retrieve_count_value{service=\"${service}\"})) by (entity_label)",
       "legendFormat": "{{entity_label}}"
      }
     ]
    },
    {
     "title": "Repository p99 latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "avg(db_retrieve_latency_99_percentile{service=\"${service}\"}) by (entity_label)",
       "legendFormat": "{{entity_label}}"
      },
      {
       "expr": "avg(db_retrieve_latency_99_percentile{service=\"${service}\"})",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Repository errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "expr": "sum(rate(retrieve_failure_value{service=\"${service}\"})) by (db_type)",
       "legendFormat": "TOTAL"
      },
      {
       "expr": "sum(rate(retrieve_failure_value{service=\"${service}\"})) by (db_type, entity)",
       "legendFormat": "{{db_type}} --{{entity}}"
      }
     ]
    }
   ]
  },
  { "title": "Features", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Expired Features - Db",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(online_feature_store_retrieve_validity_value{service=\"${service}\",validity=\"expired\"})) by (entity, feature_group)",
     "legendFormat": "{{entity}}::{{feature_group}}"
    }
   ]
  },
  {
   "title": "Default Features - Db",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(online_feature_store_retrieve_validity_value{service=\"${service}\",validity=\"negative_cache\"})) by (entity,feature_group) *100/ sum(rate(online_feature_store_retrieve_validity_value{service=\"${service}\"})) by (entity,feature_group)",
     "legendFormat": "{{entity}} :: {{feature_group}}"
    }
   ]
  },
  {
   "title": "Valid Features - Db",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(online_feature_store_retrieve_validity_value{service=\"${service}\",validity=\"valid\"})) by (entity,feature_group) * 100 / sum(rate(online_feature_store_retrieve_validity_value{service=\"${service}\"})) by (entity,feature_group)",
     "legendFormat": "{{entity}} :: {{feature_group}}"
    }
   ]
  },
  { "title": "Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Total Events Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(events_consumed_value{service=\"${consumer_service}\"}))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Persist Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "avg(orchestrator_persist_latency_99_percentile{service=\"${consumer_service}\"}) by (entity)",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Successful persists per Entity per FG per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(feature_persist_value{service=\"${consumer_service}\", success=\"true\"})) by (entity)",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Failed persists per Entity per FG per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(feature_persist_value{service=\"${consumer_service}\", success=\"false\"})) by (entity)",
     "legendFormat": "persist failures -- {{entity}}"
    },
    {
     "expr": "sum(rate(serialize_psdb_data_failure_value{service=\"${consumer_service}\"})) by (entity_name)",
     "legendFormat": "data serialisation errors -- {{entity_name}}"
    }
   ]
  }
 ]
}