{{- if and .Values.deployment (.Values.deployment.enabled) (.Values.deployment.serviceAccount.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}
  labels:
{{ include "labels.common" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  {{- with .Values.deployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
