// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: p2p.proto

package p2p

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	P2PCacheService_GetClusterConfigs_FullMethodName = "/p2p.P2PCacheService/GetClusterConfigs"
)

// P2PCacheServiceClient is the client API for P2PCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type P2PCacheServiceClient interface {
	GetClusterConfigs(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ClusterTopology, error)
}

type p2PCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewP2PCacheServiceClient(cc grpc.ClientConnInterface) P2PCacheServiceClient {
	return &p2PCacheServiceClient{cc}
}

func (c *p2PCacheServiceClient) GetClusterConfigs(ctx context.Context, in *Query, opts ...grpc.CallOption) (*ClusterTopology, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterTopology)
	err := c.cc.Invoke(ctx, P2PCacheService_GetClusterConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// P2PCacheServiceServer is the server API for P2PCacheService service.
// All implementations must embed UnimplementedP2PCacheServiceServer
// for forward compatibility.
type P2PCacheServiceServer interface {
	GetClusterConfigs(context.Context, *Query) (*ClusterTopology, error)
	mustEmbedUnimplementedP2PCacheServiceServer()
}

// UnimplementedP2PCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedP2PCacheServiceServer struct{}

func (UnimplementedP2PCacheServiceServer) GetClusterConfigs(context.Context, *Query) (*ClusterTopology, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterConfigs not implemented")
}
func (UnimplementedP2PCacheServiceServer) mustEmbedUnimplementedP2PCacheServiceServer() {}
func (UnimplementedP2PCacheServiceServer) testEmbeddedByValue()                         {}

// UnsafeP2PCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to P2PCacheServiceServer will
// result in compilation errors.
type UnsafeP2PCacheServiceServer interface {
	mustEmbedUnimplementedP2PCacheServiceServer()
}

func RegisterP2PCacheServiceServer(s grpc.ServiceRegistrar, srv P2PCacheServiceServer) {
	// If the following call pancis, it indicates UnimplementedP2PCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&P2PCacheService_ServiceDesc, srv)
}

func _P2PCacheService_GetClusterConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PCacheServiceServer).GetClusterConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PCacheService_GetClusterConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PCacheServiceServer).GetClusterConfigs(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

// P2PCacheService_ServiceDesc is the grpc.ServiceDesc for P2PCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var P2PCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p2p.P2PCacheService",
	HandlerType: (*P2PCacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterConfigs",
			Handler:    _P2PCacheService_GetClusterConfigs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "p2p.proto",
}
