// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: internal/client/eigenix.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DatabaseType specifies which vector database backend to use
type DatabaseType int32

const (
	DatabaseType_HNSW_LIB DatabaseType = 0 // Use local HNSW library (in-memory)
	DatabaseType_QDRANT   DatabaseType = 1 // Use Qdrant (remote vector database)
)

// Enum value maps for DatabaseType.
var (
	DatabaseType_name = map[int32]string{
		0: "HNSW_LIB",
		1: "QDRANT",
	}
	DatabaseType_value = map[string]int32{
		"HNSW_LIB": 0,
		"QDRANT":   1,
	}
)

func (x DatabaseType) Enum() *DatabaseType {
	p := new(DatabaseType)
	*p = x
	return p
}

func (x DatabaseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatabaseType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_client_eigenix_proto_enumTypes[0].Descriptor()
}

func (DatabaseType) Type() protoreflect.EnumType {
	return &file_internal_client_eigenix_proto_enumTypes[0]
}

func (x DatabaseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatabaseType.Descriptor instead.
func (DatabaseType) EnumDescriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{0}
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_internal_client_eigenix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Point) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_internal_client_eigenix_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResult) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchResult) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type IndexInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimension           int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Space               string                 `protobuf:"bytes,3,opt,name=space,proto3" json:"space,omitempty"`
	MaxElements         int32                  `protobuf:"varint,4,opt,name=max_elements,json=maxElements,proto3" json:"max_elements,omitempty"`
	M                   int32                  `protobuf:"varint,5,opt,name=m,proto3" json:"m,omitempty"`
	EfConstruction      int32                  `protobuf:"varint,6,opt,name=ef_construction,json=efConstruction,proto3" json:"ef_construction,omitempty"`
	AllowReplaceDeleted bool                   `protobuf:"varint,7,opt,name=allow_replace_deleted,json=allowReplaceDeleted,proto3" json:"allow_replace_deleted,omitempty"`
	CurrentCount        int32                  `protobuf:"varint,8,opt,name=current_count,json=currentCount,proto3" json:"current_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IndexInfo) Reset() {
	*x = IndexInfo{}
	mi := &file_internal_client_eigenix_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexInfo) ProtoMessage() {}

func (x *IndexInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexInfo.ProtoReflect.Descriptor instead.
func (*IndexInfo) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{2}
}

func (x *IndexInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexInfo) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *IndexInfo) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *IndexInfo) GetMaxElements() int32 {
	if x != nil {
		return x.MaxElements
	}
	return 0
}

func (x *IndexInfo) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *IndexInfo) GetEfConstruction() int32 {
	if x != nil {
		return x.EfConstruction
	}
	return 0
}

func (x *IndexInfo) GetAllowReplaceDeleted() bool {
	if x != nil {
		return x.AllowReplaceDeleted
	}
	return false
}

func (x *IndexInfo) GetCurrentCount() int32 {
	if x != nil {
		return x.CurrentCount
	}
	return 0
}

type CreateIndexRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimension           int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Space               string                 `protobuf:"bytes,3,opt,name=space,proto3" json:"space,omitempty"`
	MaxElements         int32                  `protobuf:"varint,4,opt,name=max_elements,json=maxElements,proto3" json:"max_elements,omitempty"`
	M                   int32                  `protobuf:"varint,5,opt,name=m,proto3" json:"m,omitempty"`
	EfConstruction      int32                  `protobuf:"varint,6,opt,name=ef_construction,json=efConstruction,proto3" json:"ef_construction,omitempty"`
	AllowReplaceDeleted bool                   `protobuf:"varint,7,opt,name=allow_replace_deleted,json=allowReplaceDeleted,proto3" json:"allow_replace_deleted,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateIndexRequest) Reset() {
	*x = CreateIndexRequest{}
	mi := &file_internal_client_eigenix_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexRequest) ProtoMessage() {}

func (x *CreateIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexRequest.ProtoReflect.Descriptor instead.
func (*CreateIndexRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{3}
}

func (x *CreateIndexRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateIndexRequest) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CreateIndexRequest) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *CreateIndexRequest) GetMaxElements() int32 {
	if x != nil {
		return x.MaxElements
	}
	return 0
}

func (x *CreateIndexRequest) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *CreateIndexRequest) GetEfConstruction() int32 {
	if x != nil {
		return x.EfConstruction
	}
	return 0
}

func (x *CreateIndexRequest) GetAllowReplaceDeleted() bool {
	if x != nil {
		return x.AllowReplaceDeleted
	}
	return false
}

type CreateIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexResponse) Reset() {
	*x = CreateIndexResponse{}
	mi := &file_internal_client_eigenix_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexResponse) ProtoMessage() {}

func (x *CreateIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexResponse.ProtoReflect.Descriptor instead.
func (*CreateIndexResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{4}
}

func (x *CreateIndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexRequest) Reset() {
	*x = GetIndexRequest{}
	mi := &file_internal_client_eigenix_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexRequest) ProtoMessage() {}

func (x *GetIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexRequest.ProtoReflect.Descriptor instead.
func (*GetIndexRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{5}
}

func (x *GetIndexRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *IndexInfo             `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexResponse) Reset() {
	*x = GetIndexResponse{}
	mi := &file_internal_client_eigenix_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexResponse) ProtoMessage() {}

func (x *GetIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexResponse.ProtoReflect.Descriptor instead.
func (*GetIndexResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{6}
}

func (x *GetIndexResponse) GetIndex() *IndexInfo {
	if x != nil {
		return x.Index
	}
	return nil
}

type DeleteIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIndexRequest) Reset() {
	*x = DeleteIndexRequest{}
	mi := &file_internal_client_eigenix_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexRequest) ProtoMessage() {}

func (x *DeleteIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexRequest.ProtoReflect.Descriptor instead.
func (*DeleteIndexRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteIndexRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIndexResponse) Reset() {
	*x = DeleteIndexResponse{}
	mi := &file_internal_client_eigenix_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexResponse) ProtoMessage() {}

func (x *DeleteIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexResponse.ProtoReflect.Descriptor instead.
func (*DeleteIndexResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteIndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListIndicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndicesRequest) Reset() {
	*x = ListIndicesRequest{}
	mi := &file_internal_client_eigenix_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndicesRequest) ProtoMessage() {}

func (x *ListIndicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndicesRequest.ProtoReflect.Descriptor instead.
func (*ListIndicesRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{9}
}

type ListIndicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indices       []*IndexInfo           `protobuf:"bytes,1,rep,name=indices,proto3" json:"indices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndicesResponse) Reset() {
	*x = ListIndicesResponse{}
	mi := &file_internal_client_eigenix_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndicesResponse) ProtoMessage() {}

func (x *ListIndicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndicesResponse.ProtoReflect.Descriptor instead.
func (*ListIndicesResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{10}
}

func (x *ListIndicesResponse) GetIndices() []*IndexInfo {
	if x != nil {
		return x.Indices
	}
	return nil
}

type IndexOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexOperationRequest) Reset() {
	*x = IndexOperationRequest{}
	mi := &file_internal_client_eigenix_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexOperationRequest) ProtoMessage() {}

func (x *IndexOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexOperationRequest.ProtoReflect.Descriptor instead.
func (*IndexOperationRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{11}
}

func (x *IndexOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type IndexOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexOperationResponse) Reset() {
	*x = IndexOperationResponse{}
	mi := &file_internal_client_eigenix_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexOperationResponse) ProtoMessage() {}

func (x *IndexOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexOperationResponse.ProtoReflect.Descriptor instead.
func (*IndexOperationResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{12}
}

func (x *IndexOperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IndexOperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	Points        []*Point               `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointsRequest) Reset() {
	*x = PointsRequest{}
	mi := &file_internal_client_eigenix_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointsRequest) ProtoMessage() {}

func (x *PointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointsRequest.ProtoReflect.Descriptor instead.
func (*PointsRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{13}
}

func (x *PointsRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *PointsRequest) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type PointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AffectedCount int32                  `protobuf:"varint,2,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointsResponse) Reset() {
	*x = PointsResponse{}
	mi := &file_internal_client_eigenix_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointsResponse) ProtoMessage() {}

func (x *PointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointsResponse.ProtoReflect.Descriptor instead.
func (*PointsResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{14}
}

func (x *PointsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PointsResponse) GetAffectedCount() int32 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

func (x *PointsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type DeletePointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	Ids           []uint64               `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePointsRequest) Reset() {
	*x = DeletePointsRequest{}
	mi := &file_internal_client_eigenix_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePointsRequest) ProtoMessage() {}

func (x *DeletePointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePointsRequest.ProtoReflect.Descriptor instead.
func (*DeletePointsRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{15}
}

func (x *DeletePointsRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *DeletePointsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeletePointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePointsResponse) Reset() {
	*x = DeletePointsResponse{}
	mi := &file_internal_client_eigenix_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePointsResponse) ProtoMessage() {}

func (x *DeletePointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePointsResponse.ProtoReflect.Descriptor instead.
func (*DeletePointsResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{16}
}

func (x *DeletePointsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeletePointsResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	SearchParams  *SearchParams          `protobuf:"bytes,4,opt,name=search_params,json=searchParams,proto3" json:"search_params,omitempty"`
	DatabaseType  DatabaseType           `protobuf:"varint,5,opt,name=database_type,json=databaseType,proto3,enum=eigenix.DatabaseType" json:"database_type,omitempty"` // Which database backend to use
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_internal_client_eigenix_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{17}
}

func (x *SearchRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *SearchRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetSearchParams() *SearchParams {
	if x != nil {
		return x.SearchParams
	}
	return nil
}

func (x *SearchRequest) GetDatabaseType() DatabaseType {
	if x != nil {
		return x.DatabaseType
	}
	return DatabaseType_HNSW_LIB
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_internal_client_eigenix_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{18}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchParams struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UseIvf            bool                   `protobuf:"varint,1,opt,name=use_ivf,json=useIvf,proto3" json:"use_ivf,omitempty"`
	CentCount         int32                  `protobuf:"varint,2,opt,name=cent_count,json=centCount,proto3" json:"cent_count,omitempty"` // Number of centroids to search (only for IVF mode)
	SearchIndexedOnly bool                   `protobuf:"varint,3,opt,name=search_indexed_only,json=searchIndexedOnly,proto3" json:"search_indexed_only,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchParams) Reset() {
	*x = SearchParams{}
	mi := &file_internal_client_eigenix_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchParams) ProtoMessage() {}

func (x *SearchParams) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchParams.ProtoReflect.Descriptor instead.
func (*SearchParams) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{19}
}

func (x *SearchParams) GetUseIvf() bool {
	if x != nil {
		return x.UseIvf
	}
	return false
}

func (x *SearchParams) GetCentCount() int32 {
	if x != nil {
		return x.CentCount
	}
	return 0
}

func (x *SearchParams) GetSearchIndexedOnly() bool {
	if x != nil {
		return x.SearchIndexedOnly
	}
	return false
}

type BatchSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	Vectors       []*Vector              `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	SearchParams  *SearchParams          `protobuf:"bytes,4,opt,name=search_params,json=searchParams,proto3" json:"search_params,omitempty"`
	DatabaseType  DatabaseType           `protobuf:"varint,5,opt,name=database_type,json=databaseType,proto3,enum=eigenix.DatabaseType" json:"database_type,omitempty"` // Which database backend to use
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSearchRequest) Reset() {
	*x = BatchSearchRequest{}
	mi := &file_internal_client_eigenix_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSearchRequest) ProtoMessage() {}

func (x *BatchSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSearchRequest.ProtoReflect.Descriptor instead.
func (*BatchSearchRequest) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{20}
}

func (x *BatchSearchRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *BatchSearchRequest) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *BatchSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BatchSearchRequest) GetSearchParams() *SearchParams {
	if x != nil {
		return x.SearchParams
	}
	return nil
}

func (x *BatchSearchRequest) GetDatabaseType() DatabaseType {
	if x != nil {
		return x.DatabaseType
	}
	return DatabaseType_HNSW_LIB
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_internal_client_eigenix_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{21}
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type BatchSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultSets    []*SearchResultSet     `protobuf:"bytes,1,rep,name=result_sets,json=resultSets,proto3" json:"result_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSearchResponse) Reset() {
	*x = BatchSearchResponse{}
	mi := &file_internal_client_eigenix_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSearchResponse) ProtoMessage() {}

func (x *BatchSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSearchResponse.ProtoReflect.Descriptor instead.
func (*BatchSearchResponse) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{22}
}

func (x *BatchSearchResponse) GetResultSets() []*SearchResultSet {
	if x != nil {
		return x.ResultSets
	}
	return nil
}

type SearchResultSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResultSet) Reset() {
	*x = SearchResultSet{}
	mi := &file_internal_client_eigenix_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultSet) ProtoMessage() {}

func (x *SearchResultSet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_eigenix_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultSet.ProtoReflect.Descriptor instead.
func (*SearchResultSet) Descriptor() ([]byte, []int) {
	return file_internal_client_eigenix_proto_rawDescGZIP(), []int{23}
}

func (x *SearchResultSet) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_internal_client_eigenix_proto protoreflect.FileDescriptor

const file_internal_client_eigenix_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/client/eigenix.proto\x12\aeigenix\"/\n" +
	"\x05Point\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\":\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\"\x86\x02\n" +
	"\tIndexInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension\x12\x14\n" +
	"\x05space\x18\x03 \x01(\tR\x05space\x12!\n" +
	"\fmax_elements\x18\x04 \x01(\x05R\vmaxElements\x12\f\n" +
	"\x01m\x18\x05 \x01(\x05R\x01m\x12'\n" +
	"\x0fef_construction\x18\x06 \x01(\x05R\x0eefConstruction\x122\n" +
	"\x15allow_replace_deleted\x18\a \x01(\bR\x13allowReplaceDeleted\x12#\n" +
	"\rcurrent_count\x18\b \x01(\x05R\fcurrentCount\"\xea\x01\n" +
	"\x12CreateIndexRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension\x12\x14\n" +
	"\x05space\x18\x03 \x01(\tR\x05space\x12!\n" +
	"\fmax_elements\x18\x04 \x01(\x05R\vmaxElements\x12\f\n" +
	"\x01m\x18\x05 \x01(\x05R\x01m\x12'\n" +
	"\x0fef_construction\x18\x06 \x01(\x05R\x0eefConstruction\x122\n" +
	"\x15allow_replace_deleted\x18\a \x01(\bR\x13allowReplaceDeleted\"I\n" +
	"\x13CreateIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x0fGetIndexRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\x10GetIndexResponse\x12(\n" +
	"\x05index\x18\x01 \x01(\v2\x12.eigenix.IndexInfoR\x05index\"(\n" +
	"\x12DeleteIndexRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"I\n" +
	"\x13DeleteIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12ListIndicesRequest\"C\n" +
	"\x13ListIndicesResponse\x12,\n" +
	"\aindices\x18\x01 \x03(\v2\x12.eigenix.IndexInfoR\aindices\"+\n" +
	"\x15IndexOperationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"L\n" +
	"\x16IndexOperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\rPointsRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12&\n" +
	"\x06points\x18\x02 \x03(\v2\x0e.eigenix.PointR\x06points\"r\n" +
	"\x0ePointsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eaffected_count\x18\x02 \x01(\x05R\raffectedCount\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"F\n" +
	"\x13DeletePointsRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\x04R\x03ids\"U\n" +
	"\x14DeletePointsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x05R\fdeletedCount\"\xd4\x01\n" +
	"\rSearchRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12:\n" +
	"\rsearch_params\x18\x04 \x01(\v2\x15.eigenix.SearchParamsR\fsearchParams\x12:\n" +
	"\rdatabase_type\x18\x05 \x01(\x0e2\x15.eigenix.DatabaseTypeR\fdatabaseType\"A\n" +
	"\x0eSearchResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.eigenix.SearchResultR\aresults\"v\n" +
	"\fSearchParams\x12\x17\n" +
	"\ause_ivf\x18\x01 \x01(\bR\x06useIvf\x12\x1d\n" +
	"\n" +
	"cent_count\x18\x02 \x01(\x05R\tcentCount\x12.\n" +
	"\x13search_indexed_only\x18\x03 \x01(\bR\x11searchIndexedOnly\"\xec\x01\n" +
	"\x12BatchSearchRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12)\n" +
	"\avectors\x18\x02 \x03(\v2\x0f.eigenix.VectorR\avectors\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12:\n" +
	"\rsearch_params\x18\x04 \x01(\v2\x15.eigenix.SearchParamsR\fsearchParams\x12:\n" +
	"\rdatabase_type\x18\x05 \x01(\x0e2\x15.eigenix.DatabaseTypeR\fdatabaseType\" \n" +
	"\x06Vector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"P\n" +
	"\x13BatchSearchResponse\x129\n" +
	"\vresult_sets\x18\x01 \x03(\v2\x18.eigenix.SearchResultSetR\n" +
	"resultSets\"B\n" +
	"\x0fSearchResultSet\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.eigenix.SearchResultR\aresults*(\n" +
	"\fDatabaseType\x12\f\n" +
	"\bHNSW_LIB\x10\x00\x12\n" +
	"\n" +
	"\x06QDRANT\x10\x012\x9c\x06\n" +
	"\x0eEigenixService\x12H\n" +
	"\vCreateIndex\x12\x1b.eigenix.CreateIndexRequest\x1a\x1c.eigenix.CreateIndexResponse\x12?\n" +
	"\bGetIndex\x12\x18.eigenix.GetIndexRequest\x1a\x19.eigenix.GetIndexResponse\x12H\n" +
	"\vDeleteIndex\x12\x1b.eigenix.DeleteIndexRequest\x1a\x1c.eigenix.DeleteIndexResponse\x12H\n" +
	"\vListIndices\x12\x1b.eigenix.ListIndicesRequest\x1a\x1c.eigenix.ListIndicesResponse\x12L\n" +
	"\tSaveIndex\x12\x1e.eigenix.IndexOperationRequest\x1a\x1f.eigenix.IndexOperationResponse\x12L\n" +
	"\tLoadIndex\x12\x1e.eigenix.IndexOperationRequest\x1a\x1f.eigenix.IndexOperationResponse\x12<\n" +
	"\tAddPoints\x12\x16.eigenix.PointsRequest\x1a\x17.eigenix.PointsResponse\x12?\n" +
	"\fUpdatePoints\x12\x16.eigenix.PointsRequest\x1a\x17.eigenix.PointsResponse\x12K\n" +
	"\fDeletePoints\x12\x1c.eigenix.DeletePointsRequest\x1a\x1d.eigenix.DeletePointsResponse\x129\n" +
	"\x06Search\x12\x16.eigenix.SearchRequest\x1a\x17.eigenix.SearchResponse\x12H\n" +
	"\vBatchSearch\x12\x1b.eigenix.BatchSearchRequest\x1a\x1c.eigenix.BatchSearchResponseB\x11Z\x0finternal/clientb\x06proto3"

var (
	file_internal_client_eigenix_proto_rawDescOnce sync.Once
	file_internal_client_eigenix_proto_rawDescData []byte
)

func file_internal_client_eigenix_proto_rawDescGZIP() []byte {
	file_internal_client_eigenix_proto_rawDescOnce.Do(func() {
		file_internal_client_eigenix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_client_eigenix_proto_rawDesc), len(file_internal_client_eigenix_proto_rawDesc)))
	})
	return file_internal_client_eigenix_proto_rawDescData
}

var file_internal_client_eigenix_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_client_eigenix_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_internal_client_eigenix_proto_goTypes = []any{
	(DatabaseType)(0),              // 0: eigenix.DatabaseType
	(*Point)(nil),                  // 1: eigenix.Point
	(*SearchResult)(nil),           // 2: eigenix.SearchResult
	(*IndexInfo)(nil),              // 3: eigenix.IndexInfo
	(*CreateIndexRequest)(nil),     // 4: eigenix.CreateIndexRequest
	(*CreateIndexResponse)(nil),    // 5: eigenix.CreateIndexResponse
	(*GetIndexRequest)(nil),        // 6: eigenix.GetIndexRequest
	(*GetIndexResponse)(nil),       // 7: eigenix.GetIndexResponse
	(*DeleteIndexRequest)(nil),     // 8: eigenix.DeleteIndexRequest
	(*DeleteIndexResponse)(nil),    // 9: eigenix.DeleteIndexResponse
	(*ListIndicesRequest)(nil),     // 10: eigenix.ListIndicesRequest
	(*ListIndicesResponse)(nil),    // 11: eigenix.ListIndicesResponse
	(*IndexOperationRequest)(nil),  // 12: eigenix.IndexOperationRequest
	(*IndexOperationResponse)(nil), // 13: eigenix.IndexOperationResponse
	(*PointsRequest)(nil),          // 14: eigenix.PointsRequest
	(*PointsResponse)(nil),         // 15: eigenix.PointsResponse
	(*DeletePointsRequest)(nil),    // 16: eigenix.DeletePointsRequest
	(*DeletePointsResponse)(nil),   // 17: eigenix.DeletePointsResponse
	(*SearchRequest)(nil),          // 18: eigenix.SearchRequest
	(*SearchResponse)(nil),         // 19: eigenix.SearchResponse
	(*SearchParams)(nil),           // 20: eigenix.SearchParams
	(*BatchSearchRequest)(nil),     // 21: eigenix.BatchSearchRequest
	(*Vector)(nil),                 // 22: eigenix.Vector
	(*BatchSearchResponse)(nil),    // 23: eigenix.BatchSearchResponse
	(*SearchResultSet)(nil),        // 24: eigenix.SearchResultSet
}
var file_internal_client_eigenix_proto_depIdxs = []int32{
	3,  // 0: eigenix.GetIndexResponse.index:type_name -> eigenix.IndexInfo
	3,  // 1: eigenix.ListIndicesResponse.indices:type_name -> eigenix.IndexInfo
	1,  // 2: eigenix.PointsRequest.points:type_name -> eigenix.Point
	20, // 3: eigenix.SearchRequest.search_params:type_name -> eigenix.SearchParams
	0,  // 4: eigenix.SearchRequest.database_type:type_name -> eigenix.DatabaseType
	2,  // 5: eigenix.SearchResponse.results:type_name -> eigenix.SearchResult
	22, // 6: eigenix.BatchSearchRequest.vectors:type_name -> eigenix.Vector
	20, // 7: eigenix.BatchSearchRequest.search_params:type_name -> eigenix.SearchParams
	0,  // 8: eigenix.BatchSearchRequest.database_type:type_name -> eigenix.DatabaseType
	24, // 9: eigenix.BatchSearchResponse.result_sets:type_name -> eigenix.SearchResultSet
	2,  // 10: eigenix.SearchResultSet.results:type_name -> eigenix.SearchResult
	4,  // 11: eigenix.EigenixService.CreateIndex:input_type -> eigenix.CreateIndexRequest
	6,  // 12: eigenix.EigenixService.GetIndex:input_type -> eigenix.GetIndexRequest
	8,  // 13: eigenix.EigenixService.DeleteIndex:input_type -> eigenix.DeleteIndexRequest
	10, // 14: eigenix.EigenixService.ListIndices:input_type -> eigenix.ListIndicesRequest
	12, // 15: eigenix.EigenixService.SaveIndex:input_type -> eigenix.IndexOperationRequest
	12, // 16: eigenix.EigenixService.LoadIndex:input_type -> eigenix.IndexOperationRequest
	14, // 17: eigenix.EigenixService.AddPoints:input_type -> eigenix.PointsRequest
	14, // 18: eigenix.EigenixService.UpdatePoints:input_type -> eigenix.PointsRequest
	16, // 19: eigenix.EigenixService.DeletePoints:input_type -> eigenix.DeletePointsRequest
	18, // 20: eigenix.EigenixService.Search:input_type -> eigenix.SearchRequest
	21, // 21: eigenix.EigenixService.BatchSearch:input_type -> eigenix.BatchSearchRequest
	5,  // 22: eigenix.EigenixService.CreateIndex:output_type -> eigenix.CreateIndexResponse
	7,  // 23: eigenix.EigenixService.GetIndex:output_type -> eigenix.GetIndexResponse
	9,  // 24: eigenix.EigenixService.DeleteIndex:output_type -> eigenix.DeleteIndexResponse
	11, // 25: eigenix.EigenixService.ListIndices:output_type -> eigenix.ListIndicesResponse
	13, // 26: eigenix.EigenixService.SaveIndex:output_type -> eigenix.IndexOperationResponse
	13, // 27: eigenix.EigenixService.LoadIndex:output_type -> eigenix.IndexOperationResponse
	15, // 28: eigenix.EigenixService.AddPoints:output_type -> eigenix.PointsResponse
	15, // 29: eigenix.EigenixService.UpdatePoints:output_type -> eigenix.PointsResponse
	17, // 30: eigenix.EigenixService.DeletePoints:output_type -> eigenix.DeletePointsResponse
	19, // 31: eigenix.EigenixService.Search:output_type -> eigenix.SearchResponse
	23, // 32: eigenix.EigenixService.BatchSearch:output_type -> eigenix.BatchSearchResponse
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_client_eigenix_proto_init() }
func file_internal_client_eigenix_proto_init() {
	if File_internal_client_eigenix_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_client_eigenix_proto_rawDesc), len(file_internal_client_eigenix_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_client_eigenix_proto_goTypes,
		DependencyIndexes: file_internal_client_eigenix_proto_depIdxs,
		EnumInfos:         file_internal_client_eigenix_proto_enumTypes,
		MessageInfos:      file_internal_client_eigenix_proto_msgTypes,
	}.Build()
	File_internal_client_eigenix_proto = out.File
	file_internal_client_eigenix_proto_goTypes = nil
	file_internal_client_eigenix_proto_depIdxs = nil
}
