// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/client/eigenix.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EigenixService_CreateIndex_FullMethodName  = "/eigenix.EigenixService/CreateIndex"
	EigenixService_GetIndex_FullMethodName     = "/eigenix.EigenixService/GetIndex"
	EigenixService_DeleteIndex_FullMethodName  = "/eigenix.EigenixService/DeleteIndex"
	EigenixService_ListIndices_FullMethodName  = "/eigenix.EigenixService/ListIndices"
	EigenixService_SaveIndex_FullMethodName    = "/eigenix.EigenixService/SaveIndex"
	EigenixService_LoadIndex_FullMethodName    = "/eigenix.EigenixService/LoadIndex"
	EigenixService_AddPoints_FullMethodName    = "/eigenix.EigenixService/AddPoints"
	EigenixService_UpdatePoints_FullMethodName = "/eigenix.EigenixService/UpdatePoints"
	EigenixService_DeletePoints_FullMethodName = "/eigenix.EigenixService/DeletePoints"
	EigenixService_Search_FullMethodName       = "/eigenix.EigenixService/Search"
	EigenixService_BatchSearch_FullMethodName  = "/eigenix.EigenixService/BatchSearch"
)

// EigenixServiceClient is the client API for EigenixService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EigenixServiceClient interface {
	// Index management
	CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error)
	GetIndex(ctx context.Context, in *GetIndexRequest, opts ...grpc.CallOption) (*GetIndexResponse, error)
	DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error)
	ListIndices(ctx context.Context, in *ListIndicesRequest, opts ...grpc.CallOption) (*ListIndicesResponse, error)
	SaveIndex(ctx context.Context, in *IndexOperationRequest, opts ...grpc.CallOption) (*IndexOperationResponse, error)
	LoadIndex(ctx context.Context, in *IndexOperationRequest, opts ...grpc.CallOption) (*IndexOperationResponse, error)
	// Points
	AddPoints(ctx context.Context, in *PointsRequest, opts ...grpc.CallOption) (*PointsResponse, error)
	UpdatePoints(ctx context.Context, in *PointsRequest, opts ...grpc.CallOption) (*PointsResponse, error)
	DeletePoints(ctx context.Context, in *DeletePointsRequest, opts ...grpc.CallOption) (*DeletePointsResponse, error)
	// Search
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	BatchSearch(ctx context.Context, in *BatchSearchRequest, opts ...grpc.CallOption) (*BatchSearchResponse, error)
}

type eigenixServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEigenixServiceClient(cc grpc.ClientConnInterface) EigenixServiceClient {
	return &eigenixServiceClient{cc}
}

func (c *eigenixServiceClient) CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIndexResponse)
	err := c.cc.Invoke(ctx, EigenixService_CreateIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eigenixServiceClient) GetIndex(ctx context.Context, in *GetIndexRequest, opts ...grpc.CallOption) (*GetIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIndexResponse)
	err := c.cc.Invoke(ctx, EigenixService_GetIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eigenixServiceClient) DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIndexResponse)
	err := c.cc.Invoke(ctx, EigenixService_DeleteIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eigenixServiceClient) ListIndices(ctx context.Context, in *ListIndicesRequest, opts ...grpc.CallOption) (*ListIndicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIndicesResponse)
	err := c.cc.Invoke(ctx, EigenixService_ListIndices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eigenixServiceClient) SaveIndex(ctx context.Context, in *IndexOperationRequest, opts ...grpc.CallOption) (*IndexOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexOperationResponse)
	err := c.cc.Invoke(ctx, EigenixService_SaveIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eigenixServiceClient) LoadIndex(ctx context.Context, in *IndexOperationRequest, opts ...grpc.CallOption) (*IndexOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexOperationResponse)
	err := c.cc.Invoke(ctx, EigenixService_LoadIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eigenixServiceClient) AddPoints(ctx context.Context, in *PointsRequest, opts ...grpc.CallOption) (*PointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PointsResponse)
	err := c.cc.Invoke(ctx, EigenixService_AddPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eigenixServiceClient) UpdatePoints(ctx context.Context, in *PointsRequest, opts ...grpc.CallOption) (*PointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PointsResponse)
	err := c.cc.Invoke(ctx, EigenixService_UpdatePoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eigenixServiceClient) DeletePoints(ctx context.Context, in *DeletePointsRequest, opts ...grpc.CallOption) (*DeletePointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePointsResponse)
	err := c.cc.Invoke(ctx, EigenixService_DeletePoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eigenixServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, EigenixService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eigenixServiceClient) BatchSearch(ctx context.Context, in *BatchSearchRequest, opts ...grpc.CallOption) (*BatchSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSearchResponse)
	err := c.cc.Invoke(ctx, EigenixService_BatchSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EigenixServiceServer is the server API for EigenixService service.
// All implementations must embed UnimplementedEigenixServiceServer
// for forward compatibility.
type EigenixServiceServer interface {
	// Index management
	CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error)
	GetIndex(context.Context, *GetIndexRequest) (*GetIndexResponse, error)
	DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error)
	ListIndices(context.Context, *ListIndicesRequest) (*ListIndicesResponse, error)
	SaveIndex(context.Context, *IndexOperationRequest) (*IndexOperationResponse, error)
	LoadIndex(context.Context, *IndexOperationRequest) (*IndexOperationResponse, error)
	// Points
	AddPoints(context.Context, *PointsRequest) (*PointsResponse, error)
	UpdatePoints(context.Context, *PointsRequest) (*PointsResponse, error)
	DeletePoints(context.Context, *DeletePointsRequest) (*DeletePointsResponse, error)
	// Search
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	BatchSearch(context.Context, *BatchSearchRequest) (*BatchSearchResponse, error)
	mustEmbedUnimplementedEigenixServiceServer()
}

// UnimplementedEigenixServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEigenixServiceServer struct{}

func (UnimplementedEigenixServiceServer) CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIndex not implemented")
}
func (UnimplementedEigenixServiceServer) GetIndex(context.Context, *GetIndexRequest) (*GetIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndex not implemented")
}
func (UnimplementedEigenixServiceServer) DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIndex not implemented")
}
func (UnimplementedEigenixServiceServer) ListIndices(context.Context, *ListIndicesRequest) (*ListIndicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIndices not implemented")
}
func (UnimplementedEigenixServiceServer) SaveIndex(context.Context, *IndexOperationRequest) (*IndexOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveIndex not implemented")
}
func (UnimplementedEigenixServiceServer) LoadIndex(context.Context, *IndexOperationRequest) (*IndexOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadIndex not implemented")
}
func (UnimplementedEigenixServiceServer) AddPoints(context.Context, *PointsRequest) (*PointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPoints not implemented")
}
func (UnimplementedEigenixServiceServer) UpdatePoints(context.Context, *PointsRequest) (*PointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePoints not implemented")
}
func (UnimplementedEigenixServiceServer) DeletePoints(context.Context, *DeletePointsRequest) (*DeletePointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePoints not implemented")
}
func (UnimplementedEigenixServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedEigenixServiceServer) BatchSearch(context.Context, *BatchSearchRequest) (*BatchSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchSearch not implemented")
}
func (UnimplementedEigenixServiceServer) mustEmbedUnimplementedEigenixServiceServer() {}
func (UnimplementedEigenixServiceServer) testEmbeddedByValue()                        {}

// UnsafeEigenixServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EigenixServiceServer will
// result in compilation errors.
type UnsafeEigenixServiceServer interface {
	mustEmbedUnimplementedEigenixServiceServer()
}

func RegisterEigenixServiceServer(s grpc.ServiceRegistrar, srv EigenixServiceServer) {
	// If the following call pancis, it indicates UnimplementedEigenixServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EigenixService_ServiceDesc, srv)
}

func _EigenixService_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EigenixServiceServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EigenixService_CreateIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EigenixServiceServer).CreateIndex(ctx, req.(*CreateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EigenixService_GetIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EigenixServiceServer).GetIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EigenixService_GetIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EigenixServiceServer).GetIndex(ctx, req.(*GetIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EigenixService_DeleteIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EigenixServiceServer).DeleteIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EigenixService_DeleteIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EigenixServiceServer).DeleteIndex(ctx, req.(*DeleteIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EigenixService_ListIndices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIndicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EigenixServiceServer).ListIndices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EigenixService_ListIndices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EigenixServiceServer).ListIndices(ctx, req.(*ListIndicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EigenixService_SaveIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EigenixServiceServer).SaveIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EigenixService_SaveIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EigenixServiceServer).SaveIndex(ctx, req.(*IndexOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EigenixService_LoadIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EigenixServiceServer).LoadIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EigenixService_LoadIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EigenixServiceServer).LoadIndex(ctx, req.(*IndexOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EigenixService_AddPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EigenixServiceServer).AddPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EigenixService_AddPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EigenixServiceServer).AddPoints(ctx, req.(*PointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EigenixService_UpdatePoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EigenixServiceServer).UpdatePoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EigenixService_UpdatePoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EigenixServiceServer).UpdatePoints(ctx, req.(*PointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EigenixService_DeletePoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EigenixServiceServer).DeletePoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EigenixService_DeletePoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EigenixServiceServer).DeletePoints(ctx, req.(*DeletePointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EigenixService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EigenixServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EigenixService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EigenixServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EigenixService_BatchSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EigenixServiceServer).BatchSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EigenixService_BatchSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EigenixServiceServer).BatchSearch(ctx, req.(*BatchSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EigenixService_ServiceDesc is the grpc.ServiceDesc for EigenixService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EigenixService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eigenix.EigenixService",
	HandlerType: (*EigenixServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIndex",
			Handler:    _EigenixService_CreateIndex_Handler,
		},
		{
			MethodName: "GetIndex",
			Handler:    _EigenixService_GetIndex_Handler,
		},
		{
			MethodName: "DeleteIndex",
			Handler:    _EigenixService_DeleteIndex_Handler,
		},
		{
			MethodName: "ListIndices",
			Handler:    _EigenixService_ListIndices_Handler,
		},
		{
			MethodName: "SaveIndex",
			Handler:    _EigenixService_SaveIndex_Handler,
		},
		{
			MethodName: "LoadIndex",
			Handler:    _EigenixService_LoadIndex_Handler,
		},
		{
			MethodName: "AddPoints",
			Handler:    _EigenixService_AddPoints_Handler,
		},
		{
			MethodName: "UpdatePoints",
			Handler:    _EigenixService_UpdatePoints_Handler,
		},
		{
			MethodName: "DeletePoints",
			Handler:    _EigenixService_DeletePoints_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _EigenixService_Search_Handler,
		},
		{
			MethodName: "BatchSearch",
			Handler:    _EigenixService_BatchSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/client/eigenix.proto",
}
