name: Go SDK CI

on:
  pull_request:
    branches: [master, develop]
    paths: ['go-sdk/**']
  push:
    branches: [master, develop]
    paths: ['go-sdk/**']

jobs:
  build-go-sdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go-sdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-sdk-${{ hashFiles('go-sdk/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-sdk-

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: go test -v ./...

      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Display coverage
        run: go tool cover -func=coverage.out

      - name: Build SDK packages
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2023.1.7

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Check for go mod tidy
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain go.mod go.sum)" ]; then
            echo "go.mod or go.sum is not tidy"
            git diff go.mod go.sum
            exit 1
          fi 