name: Online Feature Store CI

on:
  pull_request:
    branches: [master, develop]
    paths: ['online-feature-store/**']
  push:
    branches: [master, develop]
    paths: ['online-feature-store/**']

jobs:
  build-online-feature-store:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./online-feature-store
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-ofs-${{ hashFiles('online-feature-store/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-ofs-

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build API server
        run: go build -v ./cmd/api-server

      - name: Build consumer
        run: go build -v ./cmd/consumer

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2023.1.7

      - name: Run staticcheck
        run: staticcheck ./... 