[package]
name = "rust-matrix-frame"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.12"

[lib]
name = "rust_matrix_frame"
path = "src/lib.rs"
